import test from 'node:test';
import assert from 'node:assert/strict';
import { buildReceiptHistoryVerificationReceiptIntegrityPackage, verifyReceiptHistoryVerificationReceiptIntegrityPackage, reviewReceiptHistoryVerificationReceiptIntegrityPackage } from '../src/core/receipt-history-verification-receipt-package-integrity.js';
import { buildWorkloadPresetImportAuditReviewIntegrityPackage, verifyWorkloadPresetImportAuditReviewIntegrityPackage, reviewWorkloadPresetImportAuditReviewIntegrityPackage } from '../src/core/workload-preset-import-audit-review-package-integrity.js';
import { buildSavedSearchReceiptImportHistoryPackage } from '../src/core/saved-search-receipt-import-history-package-integrity.js';
import { verifySavedSearchReceiptHistoryPackageAndRecord, savedSearchReceiptHistoryPackageVerificationReceipts, filterSavedSearchReceiptHistoryPackageVerificationReceipts, buildSavedSearchReceiptHistoryPackageVerificationReceiptPackage, clearSavedSearchReceiptHistoryPackageVerificationReceipts } from '../src/core/saved-search-receipt-history-package-verification-receipts.js';
import { filterRecoveryVerificationPackageReceipts, buildRecoveryVerificationPackageReceiptManagementPackage, clearRecoveryVerificationPackageReceipts } from '../src/core/recovery-verification-package-receipt-management.js';
import { filterCompatibilityAxeRecheckRequests, clearCompatibilityAxeRecheckRequests, buildCompatibilityAxeRecheckFreshnessEvidencePackage, verifyCompatibilityAxeRecheckFreshnessEvidencePackage } from '../src/core/compatibility-axe-recheck-management.js';

test('L121 verification-receipt package is SHA-256 protected and review-only',()=>{
  const settings={receiptImportHistoryPackageVerificationReceipts:[{at:'2026-09-08T01:00:00.000Z',format:'history-integrity-v1',algorithm:'SHA-256',result:'valid',importCount:2,receiptCount:3}]},pkg=buildReceiptHistoryVerificationReceiptIntegrityPackage(settings,{result:'valid'}),verification=verifyReceiptHistoryVerificationReceiptIntegrityPackage(pkg),review=reviewReceiptHistoryVerificationReceiptIntegrityPackage(pkg);
  assert.equal(verification.valid,true);assert.equal(review.valid,true);assert.equal(review.readOnly,true);assert.equal(review.actionsApplied,false);assert.equal(review.receiptCount,1);const text=JSON.stringify(pkg);for(const forbidden of ['sourcePackage','childId','"expected"','"actual"','rawChecksum'])assert.equal(text.includes(forbidden),false);
  const tampered=structuredClone(pkg);tampered.receipts[0].receiptCount=99;assert.equal(verifyReceiptHistoryVerificationReceiptIntegrityPackage(tampered).valid,false);
});

test('L122 preset audit-review portability stays neutral, signed and non-applying',()=>{
  const settings={workloadPresetImportHistory:[{at:'2026-09-08T02:00:00.000Z',strategy:'rename',decisions:[{status:'resolved',sourceId:'a',sourceName:'Cuối tuần',resolvedId:'a-2',resolvedName:'Cuối tuần (2)',nameConflict:true,idConflict:true}],added:[{id:'a-2',name:'Cuối tuần (2)',signature:'private-signature',config:{score:100}}]}]},pkg=buildWorkloadPresetImportAuditReviewIntegrityPackage(settings,{strategy:'rename',conflictOnly:true}),verification=verifyWorkloadPresetImportAuditReviewIntegrityPackage(pkg),review=reviewWorkloadPresetImportAuditReviewIntegrityPackage(pkg);
  assert.equal(verification.valid,true);assert.equal(review.valid,true);assert.equal(review.readOnly,true);assert.equal(review.actionsApplied,false);assert.equal(review.summary.auditCount,1);const text=JSON.stringify(pkg).toLowerCase();for(const forbidden of ['private-signature','"config"','score','rank','performance','health','childid'])assert.equal(text.includes(forbidden),false);
  const tampered=structuredClone(pkg);tampered.audits[0].decisions[0].resolvedName='Đã sửa';assert.equal(verifyWorkloadPresetImportAuditReviewIntegrityPackage(tampered).valid,false);
});

test('L123 Saved Search history-package verification receipts are bounded metadata and never restore history',()=>{
  const source={savedSearchReceiptImportHistory:[{at:'2026-09-08T03:00:00.000Z',packageFormat:'saved-source-v1',added:[{at:'2026-09-08T02:30:00.000Z',format:'saved-v1',algorithm:'SHA-256',result:'valid'}]}]},pkg=buildSavedSearchReceiptImportHistoryPackage(source),existing=Array.from({length:55},(_,i)=>({at:new Date(Date.UTC(2026,8,1,0,i)).toISOString(),format:'old',algorithm:'SHA-256',result:i%2?'valid':'invalid',importCount:1,receiptCount:1})),recorded=verifySavedSearchReceiptHistoryPackageAndRecord({savedSearchReceiptHistoryPackageVerificationReceipts:existing},pkg,'2026-09-08T04:00:00.000Z');
  const receipts=savedSearchReceiptHistoryPackageVerificationReceipts(recorded.settings);assert.equal(receipts.length,50);assert.deepEqual(Object.keys(receipts.at(-1)).sort(),['algorithm','at','format','importCount','receiptCount','result']);assert.equal(JSON.stringify(receipts).includes('saved-source-v1'),false);assert.equal(filterSavedSearchReceiptHistoryPackageVerificationReceipts(recorded.settings,{result:'valid'}).length>0,true);const exported=buildSavedSearchReceiptHistoryPackageVerificationReceiptPackage(recorded.settings,{format:receipts.at(-1).format});assert.equal(exported.receipts.length,1);assert.equal(JSON.stringify(exported).includes('criteria'),true);
  let cleared=clearSavedSearchReceiptHistoryPackageVerificationReceipts(recorded.settings,{format:receipts.at(-1).format},false);assert.equal(cleared.reason,'confirmation-required');cleared=clearSavedSearchReceiptHistoryPackageVerificationReceipts(recorded.settings,{format:receipts.at(-1).format},true);assert.equal(cleared.changed,true);assert.equal(recorded.settings.savedSearchReceiptImportHistory,undefined);
});

test('L124 Recovery package verification receipt management is metadata-only and confirmed',()=>{
  const settings={recoveryVerificationReceiptPackageVerificationReceipts:[{at:'2026-09-08T05:00:00.000Z',format:'recovery-integrity-v1',algorithm:'SHA-256',result:'valid',receiptCount:2},{at:'2026-09-08T06:00:00.000Z',format:'recovery-integrity-v1',algorithm:'SHA-256',result:'invalid',receiptCount:0}],recoveryReconciliationReports:[{childId:'private-child',payload:'private-report'}]},filtered=filterRecoveryVerificationPackageReceipts(settings,{result:'invalid'});assert.equal(filtered.length,1);const pkg=buildRecoveryVerificationPackageReceiptManagementPackage(settings,{result:'invalid'});assert.equal(pkg.receipts.length,1);const text=JSON.stringify(pkg);for(const forbidden of ['private-child','private-report','checksum','BEGIN:VCALENDAR'])assert.equal(text.includes(forbidden),false);
  let cleared=clearRecoveryVerificationPackageReceipts(settings,{result:'invalid'},false);assert.equal(cleared.reason,'confirmation-required');cleared=clearRecoveryVerificationPackageReceipts(settings,{result:'invalid'},true);assert.equal(cleared.changed,true);assert.deepEqual(cleared.settings.recoveryReconciliationReports,settings.recoveryReconciliationReports);
});

test('L125 Axe request management exports signed freshness evidence and never clears actual evidence',()=>{
  const evidence=[{module:'legacy-v110.js',flow:'axe',observed:true,active:false,at:'2026-09-08T07:00:00.000Z'}],settings={compatibilityEvidenceFreshnessPolicy:{freshDays:30},compatibilityEvidenceRecords:evidence,compatibilityAxeRecheckRequests:[{module:'legacy-v110.js',requestedAt:'2026-09-08T06:00:00.000Z',status:'passed',completedAt:'2026-09-08T07:00:00.000Z',active:false},{module:'other-v110.js',requestedAt:'2026-09-08T08:00:00.000Z',status:'pending',completedAt:null,active:null}]};
  assert.equal(filterCompatibilityAxeRecheckRequests(settings,{status:'passed'}).length,1);const pkg=buildCompatibilityAxeRecheckFreshnessEvidencePackage(settings,{status:'passed'},'2026-09-08T09:00:00.000Z'),verification=verifyCompatibilityAxeRecheckFreshnessEvidencePackage(pkg);assert.equal(verification.valid,true);assert.equal(verification.retirementAllowed,false);assert.equal(verification.actionsApplied,false);assert.equal(verification.requestCount,1);const text=JSON.stringify(pkg).toLowerCase();for(const forbidden of ['childid','score','rank','performance','healthrecords'])assert.equal(text.includes(forbidden),false);
  const tampered=structuredClone(pkg);tampered.review.retirementAllowed=true;assert.equal(verifyCompatibilityAxeRecheckFreshnessEvidencePackage(tampered).valid,false);let cleared=clearCompatibilityAxeRecheckRequests(settings,{status:'passed'},false);assert.equal(cleared.reason,'confirmation-required');cleared=clearCompatibilityAxeRecheckRequests(settings,{status:'passed'},true);assert.equal(cleared.changed,true);assert.deepEqual(cleared.settings.compatibilityEvidenceRecords,evidence);assert.equal(cleared.settings.compatibilityAxeRecheckRequests.length,1);
});
