import test from 'node:test';
import assert from 'node:assert/strict';
import { buildReceiptImportHistoryPackage } from '../src/core/receipt-import-history-package-integrity.js';
import { verifyReceiptImportHistoryPackageAndRecord, receiptImportHistoryPackageVerificationReceipts, filterReceiptImportHistoryPackageVerificationReceipts, buildReceiptImportHistoryPackageVerificationReceiptPackage, clearReceiptImportHistoryPackageVerificationReceipts } from '../src/core/receipt-import-history-package-verification-receipts.js';
import { buildWorkloadPresetImportAuditReview } from '../src/core/workload-preset-import-audit-review.js';
import { buildSavedSearchReceiptImportHistoryPackage, verifySavedSearchReceiptImportHistoryPackage, reviewSavedSearchReceiptImportHistoryPackage } from '../src/core/saved-search-receipt-import-history-package-integrity.js';
import { buildIntegrityRecoveryReconciliationVerificationReceiptPackage, verifyRecoveryReconciliationVerificationReceiptPackage, recoveryVerificationReceiptPackageVerificationReceipts, recordRecoveryVerificationReceiptPackageVerification } from '../src/core/recovery-reconciliation-verification-receipt-package-integrity.js';
import { buildCompatibilityEvidenceFreshnessReviewPackage, verifyCompatibilityEvidenceFreshnessReviewPackage, compatibilityAxeRecheckRequests, requestCompatibilityAxeRecheck, recordActualLocalAxeRecheck } from '../src/core/compatibility-evidence-freshness-review-package.js';

test('L116 history-package verification receipts are bounded metadata and manageable',()=>{
  const source={receiptImportHistory:[{id:'private-history-id',at:'2026-09-08T02:00:00.000Z',packageFormat:'source-pkg',added:[{at:'2026-09-08T01:00:00.000Z',format:'safe-v1',algorithm:'SHA-256',checksumResult:'valid'}]}]},pkg=buildReceiptImportHistoryPackage(source),recorded=verifyReceiptImportHistoryPackageAndRecord({},pkg,'2026-09-08T03:00:00.000Z');
  assert.equal(recorded.verification.valid,true);let receipts=receiptImportHistoryPackageVerificationReceipts(recorded.settings);assert.equal(receipts.length,1);assert.deepEqual(Object.keys(receipts[0]).sort(),['algorithm','at','format','importCount','receiptCount','result']);assert.equal(JSON.stringify(receipts).includes('private-history-id'),false);assert.equal(JSON.stringify(receipts).includes('checksum'),false);assert.equal(filterReceiptImportHistoryPackageVerificationReceipts(recorded.settings,{result:'valid'}).length,1);
  const exported=buildReceiptImportHistoryPackageVerificationReceiptPackage(recorded.settings,{result:'valid'});assert.equal(exported.receipts.length,1);assert.equal(JSON.stringify(exported).includes('source-pkg'),false);
  let cleared=clearReceiptImportHistoryPackageVerificationReceipts(recorded.settings,{result:'valid'},false);assert.equal(cleared.reason,'confirmation-required');cleared=clearReceiptImportHistoryPackageVerificationReceipts(recorded.settings,{result:'valid'},true);assert.equal(cleared.changed,true);assert.equal(cleared.removed,1);
});

test('L117 preset audit filters and summaries stay read-only and neutral',()=>{
  const settings={workloadPresetImportHistory:[{at:'2026-09-08T03:00:00.000Z',strategy:'rename',decisions:[{status:'resolved',sourceId:'a',sourceName:'Cuối tuần',resolvedId:'a-2',resolvedName:'Cuối tuần (2)',nameConflict:true,idConflict:true}],added:[{id:'a-2',name:'Cuối tuần (2)',signature:'internal'}]},{at:'2026-09-08T04:00:00.000Z',strategy:'skip',decisions:[{status:'conflict-skip',sourceId:'b',sourceName:'Tối',resolvedId:null,resolvedName:null,nameConflict:true,idConflict:false}],added:[]}]};
  const review=buildWorkloadPresetImportAuditReview(settings,{strategy:'rename',status:'resolved',conflictOnly:true});assert.equal(review.readOnly,true);assert.equal(review.actionsApplied,false);assert.equal(review.audits.length,1);assert.equal(review.summary.conflicts,1);assert.equal(review.summary.sourceToResolvedChanges,1);const text=JSON.stringify(review).toLowerCase();for(const forbidden of ['internal','"config"','score','rank','performance','health'])assert.equal(text.includes(forbidden),false);
});

test('L118 Saved Search receipt import-history package is SHA-256 protected and review-only',()=>{
  const settings={savedSearchReceiptImportHistory:[{id:'internal-history-id',at:'2026-09-08T05:00:00.000Z',packageFormat:'saved-package',added:[{at:'2026-09-08T04:00:00.000Z',format:'saved-v1',algorithm:'SHA-256',result:'valid'}]}]},pkg=buildSavedSearchReceiptImportHistoryPackage(settings);assert.equal(verifySavedSearchReceiptImportHistoryPackage(pkg).valid,true);const review=reviewSavedSearchReceiptImportHistoryPackage(pkg);assert.equal(review.valid,true);assert.equal(review.readOnly,true);assert.equal(review.receiptCount,1);const text=JSON.stringify(pkg);for(const forbidden of ['internal-history-id','criteria','snippet','healthRecords','nutritionLogs','"expected"','"actual"'])assert.equal(text.includes(forbidden),false);const tampered=structuredClone(pkg);tampered.imports[0].packageFormat='changed';assert.equal(verifySavedSearchReceiptImportHistoryPackage(tampered).valid,false);
});

test('L119 Recovery verification-receipt package integrity records metadata-only verification history',()=>{
  const settings={recoveryReconciliationReportVerificationReceipts:[{at:'2026-09-08T01:00:00.000Z',format:'report-v1',algorithm:'SHA-256',result:'valid',rowCount:3}]},pkg=buildIntegrityRecoveryReconciliationVerificationReceiptPackage(settings,{}),verification=verifyRecoveryReconciliationVerificationReceiptPackage(pkg);assert.equal(verification.valid,true);let next=recordRecoveryVerificationReceiptPackageVerification({},verification,'2026-09-08T06:00:00.000Z'),receipts=recoveryVerificationReceiptPackageVerificationReceipts(next);assert.equal(receipts.length,1);assert.deepEqual(Object.keys(receipts[0]).sort(),['algorithm','at','format','receiptCount','result']);const text=JSON.stringify(receipts);for(const forbidden of ['checksum','report-v1','rowCount','childId','BEGIN:VCALENDAR'])assert.equal(text.includes(forbidden),false);const tampered=structuredClone(pkg);tampered.receipts[0].rowCount=99;assert.equal(verifyRecoveryReconciliationVerificationReceiptPackage(tampered).valid,false);
});

test('L120 freshness review is signed and actual Axe PASS requires pending request plus trusted source marker',()=>{
  const settings={compatibilityEvidenceRecords:[{module:'legacy.js',flow:'overview',observed:true,active:false,at:'2026-08-01T00:00:00.000Z'}]},pkg=buildCompatibilityEvidenceFreshnessReviewPackage(settings,'2026-09-08T00:00:00.000Z'),verification=verifyCompatibilityEvidenceFreshnessReviewPackage(pkg);assert.equal(verification.valid,true);assert.equal(verification.retirementAllowed,false);assert.equal(verification.actionsApplied,false);let result=recordActualLocalAxeRecheck(settings,{module:'legacy.js',active:false,passed:true,source:'actual-local-axe'},'2026-09-08T07:00:00.000Z');assert.equal(result.changed,false);assert.equal(result.reason,'request-required');const requested=requestCompatibilityAxeRecheck(settings,'legacy.js','2026-09-08T06:30:00.000Z');assert.equal(requested.changed,true);assert.equal(compatibilityAxeRecheckRequests(requested.settings)[0].status,'pending');result=recordActualLocalAxeRecheck(requested.settings,{module:'legacy.js',active:false,passed:true,source:'manual'},'2026-09-08T07:00:00.000Z');assert.equal(result.changed,false);assert.equal(result.reason,'actual-local-axe-pass-required');result=recordActualLocalAxeRecheck(requested.settings,{module:'legacy.js',active:false,passed:true,source:'actual-local-axe'},'2026-09-08T07:00:00.000Z');assert.equal(result.changed,true);assert.equal(compatibilityAxeRecheckRequests(result.settings)[0].status,'passed');assert.equal(result.settings.compatibilityEvidenceRecords.some((item)=>item.module==='legacy.js'&&item.flow==='axe'),true);
});
