import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { readFile } from 'node:fs/promises';

async function child(page){await page.goto('/');await page.locator('#emptyAddChild').click();await page.locator('#childForm input[name="name"]').fill('V110 Child');await page.locator('#childForm input[name="dateOfBirth"]').fill('2018-01-01');await page.locator('#childForm button.primary').click();await expect(page.locator('[data-v110="receipt-verification-integrity"]')).toBeVisible();}
async function reload(page){await page.reload();await expect(page.locator('[data-v110="receipt-verification-integrity"]')).toBeVisible();}

async function downloadText(page,click){const pending=page.waitForEvent('download');await click();const file=await pending;return readFile(await file.path(),'utf8');}

test('L121 unsigned L116 export is retired and signed receipt package verifies read-only',async({page})=>{
  await child(page);await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('growup_mychildren_v1'));s.settings.receiptImportHistoryPackageVerificationReceipts=[{at:'2026-09-08T01:00:00.000Z',format:'history-v110',algorithm:'SHA-256',result:'valid',importCount:2,receiptCount:3}];localStorage.setItem('growup_mychildren_v1',JSON.stringify(s));});await reload(page);
  await expect(page.locator('#v19ExportReceiptVerificationReceipts')).toBeHidden();expect(await page.locator('#v19ExportReceiptVerificationReceipts').isDisabled()).toBe(true);await expect(page.locator('#v19ReceiptVerificationFilter')).toBeVisible();
  await page.locator('#v110ReceiptIntegrityExportForm select[name="result"]').selectOption('valid');const text=await downloadText(page,()=>page.locator('#v110ReceiptIntegrityExportForm button[type="submit"]').click());const pkg=JSON.parse(text);expect(pkg.manifest.algorithm).toBe('SHA-256');expect(pkg.receipts).toHaveLength(1);expect(text).not.toMatch(/childId|sourcePackage|"expected"|"actual"/);
  await page.locator('#v110VerifyReceiptIntegrityForm input[name="file"]').setInputFiles({name:'receipt-integrity.json',mimeType:'application/json',buffer:Buffer.from(text)});await page.locator('#v110VerifyReceiptIntegrityForm button[type="submit"]').click();await expect(page.locator('#v110ReceiptIntegrityStatus')).toContainText('HỢP LỆ');await expect(page.locator('#v110ReceiptIntegrityStatus')).toContainText('readOnly=true');
});

test('L122 preset audit review portability exports neutral SHA-256 package without mutation',async({page})=>{
  await child(page);await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('growup_mychildren_v1'));s.settings.workloadPresetImportHistory=[{at:'2026-09-08T02:00:00.000Z',strategy:'rename',decisions:[{status:'resolved',sourceId:'a',sourceName:'Cuối tuần',resolvedId:'a-2',resolvedName:'Cuối tuần (2)',nameConflict:true,idConflict:true}],added:[{id:'a-2',name:'Cuối tuần (2)',signature:'private',config:{score:99}}]}];localStorage.setItem('growup_mychildren_v1',JSON.stringify(s));});await reload(page);const before=await page.evaluate(()=>JSON.stringify(JSON.parse(localStorage.getItem('growup_mychildren_v1')).settings.workloadPresetImportHistory));await page.locator('#v110PresetAuditExportForm select[name="strategy"]').selectOption('rename');await page.locator('#v110PresetAuditExportForm input[name="conflictOnly"]').check();const text=await downloadText(page,()=>page.locator('#v110PresetAuditExportForm button[type="submit"]').click());const pkg=JSON.parse(text);expect(pkg.manifest.algorithm).toBe('SHA-256');expect(pkg.readOnly).toBe(true);expect(pkg.actionsApplied).toBe(false);expect(text.toLowerCase()).not.toMatch(/private|"config"|score|rank|performance|health|childid/);await page.locator('#v110VerifyPresetAuditPackageForm input[name="file"]').setInputFiles({name:'audit-review.json',mimeType:'application/json',buffer:Buffer.from(text)});await page.locator('#v110VerifyPresetAuditPackageForm button[type="submit"]').click();await expect(page.locator('#v110PresetAuditPackageStatus')).toContainText('HỢP LỆ');const after=await page.evaluate(()=>JSON.stringify(JSON.parse(localStorage.getItem('growup_mychildren_v1')).settings.workloadPresetImportHistory));expect(after).toBe(before);
});

test('L123 direct L118 verify is retired and managed verification receipts preserve source history',async({page})=>{
  await child(page);await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('growup_mychildren_v1'));s.settings.savedSearchReceiptImportHistory=[{id:'private-history-id',at:'2026-09-08T03:00:00.000Z',packageFormat:'saved-source-v110',added:[{at:'2026-09-08T02:30:00.000Z',format:'saved-v110',algorithm:'SHA-256',result:'valid'}]}];localStorage.setItem('growup_mychildren_v1',JSON.stringify(s));});await reload(page);await expect(page.locator('#v19VerifySavedSearchHistoryForm')).toBeHidden();const disabled=await page.locator('#v19VerifySavedSearchHistoryForm input, #v19VerifySavedSearchHistoryForm button').evaluateAll((nodes)=>nodes.every((node)=>node.disabled));expect(disabled).toBe(true);
  const sourceText=await downloadText(page,()=>page.locator('#v19ExportSavedSearchHistory').click());await page.locator('#v110VerifySavedSearchHistoryForm input[name="file"]').setInputFiles({name:'saved-history.json',mimeType:'application/json',buffer:Buffer.from(sourceText)});await page.locator('#v110VerifySavedSearchHistoryForm button[type="submit"]').click();await expect(page.locator('[data-v110="saved-search-history-verification"] .pill')).toContainText('1/50');let settings=await page.evaluate(()=>JSON.parse(localStorage.getItem('growup_mychildren_v1')).settings);expect(settings.savedSearchReceiptHistoryPackageVerificationReceipts).toHaveLength(1);expect(Object.keys(settings.savedSearchReceiptHistoryPackageVerificationReceipts[0]).sort()).toEqual(['algorithm','at','format','importCount','receiptCount','result']);expect(JSON.stringify(settings.savedSearchReceiptHistoryPackageVerificationReceipts)).not.toMatch(/private-history-id|saved-source-v110|criteria|snippet/);
  await page.locator('#v110SavedSearchVerificationFilter select[name="result"]').selectOption('valid');await page.locator('#v110SavedSearchVerificationFilter button[type="submit"]').click();await expect(page.locator('#v110SavedSearchVerificationStatus')).toContainText('1 verification receipt');const exported=await downloadText(page,()=>page.locator('#v110ExportSavedSearchVerificationReceipts').click());expect(JSON.parse(exported).receipts).toHaveLength(1);page.once('dialog',(d)=>d.accept());await page.locator('#v110ClearSavedSearchVerificationReceipts').click();await expect(page.locator('[data-v110="saved-search-history-verification"] .pill')).toContainText('0/50');settings=await page.evaluate(()=>JSON.parse(localStorage.getItem('growup_mychildren_v1')).settings);expect(settings.savedSearchReceiptImportHistory).toHaveLength(1);expect(settings.savedSearchReceiptImportHistory[0].packageFormat).toBe('saved-source-v110');
});

test('L124 Recovery verification receipt management filters exports and clears metadata only',async({page})=>{
  await child(page);await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('growup_mychildren_v1'));s.settings.recoveryVerificationReceiptPackageVerificationReceipts=[{at:'2026-09-08T04:00:00.000Z',format:'recovery-v110',algorithm:'SHA-256',result:'valid',receiptCount:2},{at:'2026-09-08T05:00:00.000Z',format:'recovery-v110',algorithm:'SHA-256',result:'invalid',receiptCount:0}];s.settings.recoveryReconciliationReportVerificationReceipts=[{at:'2026-09-08T01:00:00.000Z',format:'source-report',algorithm:'SHA-256',result:'valid',rowCount:3}];localStorage.setItem('growup_mychildren_v1',JSON.stringify(s));});await reload(page);await page.locator('#v110RecoveryVerificationFilter select[name="result"]').selectOption('invalid');await page.locator('#v110RecoveryVerificationFilter button[type="submit"]').click();await expect(page.locator('#v110RecoveryVerificationStatus')).toContainText('1 verification receipt');const text=await downloadText(page,()=>page.locator('#v110ExportRecoveryVerificationReceipts').click());expect(JSON.parse(text).receipts).toHaveLength(1);expect(text).not.toMatch(/source-report|rowCount|checksum|childId|BEGIN:VCALENDAR/);page.once('dialog',(d)=>d.accept());await page.locator('#v110ClearRecoveryVerificationReceipts').click();await expect(page.locator('[data-v110="recovery-verification-management"] .pill')).toContainText('1/50');const settings=await page.evaluate(()=>JSON.parse(localStorage.getItem('growup_mychildren_v1')).settings);expect(settings.recoveryReconciliationReportVerificationReceipts).toHaveLength(1);expect(settings.recoveryVerificationReceiptPackageVerificationReceipts).toHaveLength(1);expect(settings.recoveryVerificationReceiptPackageVerificationReceipts[0].result).toBe('valid');
});

test('L125 Axe request management preserves actual evidence and v110 overview passes Axe',async({page})=>{
  await child(page);await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('growup_mychildren_v1'));s.settings.compatibilityEvidenceRecords=[{module:'legacy-v110.js',flow:'overview',observed:true,active:false,at:'2026-09-01T00:00:00.000Z'},{module:'legacy-v110.js',flow:'axe',observed:true,active:false,at:'2026-09-08T06:00:00.000Z'}];s.settings.compatibilityAxeRecheckRequests=[{module:'legacy-v110.js',requestedAt:'2026-09-08T05:00:00.000Z',status:'passed',completedAt:'2026-09-08T06:00:00.000Z',active:false},{module:'other-v110.js',requestedAt:'2026-09-08T07:00:00.000Z',status:'pending',completedAt:null,active:null}];localStorage.setItem('growup_mychildren_v1',JSON.stringify(s));});await reload(page);const buttons=await page.locator('[data-v110="axe-recheck-management"] button').allTextContents();expect(buttons.some((label)=>/manual.*pass|đánh dấu.*pass/i.test(label))).toBe(false);await page.locator('#v110AxeManagementFilter select[name="status"]').selectOption('passed');await page.locator('#v110AxeManagementFilter button[type="submit"]').click();await expect(page.locator('#v110AxeManagementStatus')).toContainText('1 request');const text=await downloadText(page,()=>page.locator('#v110ExportAxeFreshnessEvidence').click());const pkg=JSON.parse(text);expect(pkg.manifest.algorithm).toBe('SHA-256');expect(pkg.review.retirementAllowed).toBe(false);expect(pkg.review.actionsApplied).toBe(false);expect(pkg.requests).toHaveLength(1);await page.locator('#v110VerifyAxeFreshnessEvidenceForm input[name="file"]').setInputFiles({name:'axe-evidence.json',mimeType:'application/json',buffer:Buffer.from(text)});await page.locator('#v110VerifyAxeFreshnessEvidenceForm button[type="submit"]').click();await expect(page.locator('#v110AxeManagementStatus')).toContainText('HỢP LỆ');const axe=await new AxeBuilder({page}).analyze();expect(axe.violations.filter((v)=>['serious','critical'].includes(v.impact))).toEqual([]);page.once('dialog',(d)=>d.accept());await page.locator('#v110ClearAxeRequests').click();await expect(page.locator('[data-v110="axe-recheck-management"] .pill')).toContainText('1 pending · 0 passed');const settings=await page.evaluate(()=>JSON.parse(localStorage.getItem('growup_mychildren_v1')).settings);expect(settings.compatibilityEvidenceRecords.some((item)=>item.module==='legacy-v110.js'&&item.flow==='axe')).toBe(true);expect(settings.compatibilityAxeRecheckRequests).toHaveLength(1);expect(settings.compatibilityAxeRecheckRequests[0].status).toBe('pending');
});
