import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { readFile } from 'node:fs/promises';
import { buildWorkloadPresetImportAuditPackage } from '../src/core/workload-preset-import-audit-package-integrity.js';
import { buildIntegritySavedSearchReceiptPackage } from '../src/core/saved-search-receipt-package-integrity.js';

async function child(page){await page.goto('/');await page.locator('#emptyAddChild').click();await page.locator('#childForm input[name="name"]').fill('V18 Child');await page.locator('#childForm input[name="dateOfBirth"]').fill('2018-01-01');await page.locator('#childForm button.primary').click();await expect(page.locator('[data-v18="receipt-history-package"]')).toBeVisible();}
async function reload(page){await page.reload();await expect(page.locator('[data-v18="receipt-history-package"]')).toBeVisible();}

test('L111 receipt import-history package still exports SHA-256 while direct v18 verify is retired by L116',async({page})=>{
  await child(page);const history={receiptImportHistory:[{at:'2026-09-08T02:00:00.000Z',packageFormat:'pkg-v1',added:[{at:'2026-09-08T01:00:00.000Z',format:'safe-v1',algorithm:'SHA-256',checksumResult:'valid'}]}]};await page.evaluate((x)=>{const s=JSON.parse(localStorage.getItem('growup_mychildren_v1'));s.settings={...s.settings,...x};localStorage.setItem('growup_mychildren_v1',JSON.stringify(s));},history);await reload(page);
  const dl=page.waitForEvent('download');await page.locator('#v18ExportReceiptHistory').click();const file=await dl;const text=await readFile(await file.path(),'utf8');const pkg=JSON.parse(text);expect(pkg.manifest.algorithm).toBe('SHA-256');expect(pkg.imports).toHaveLength(1);expect(text).not.toMatch(/"expected"|"actual"|"payload"|childId/);
  await expect(page.locator('#v18VerifyReceiptHistoryForm')).toBeHidden();const disabled=await page.locator('#v18VerifyReceiptHistoryForm input, #v18VerifyReceiptHistoryForm button').evaluateAll((nodes)=>nodes.every((node)=>node.disabled));expect(disabled).toBe(true);await expect(page.locator('#v18ReceiptHistoryStatus')).toContainText('Lượt 116');await expect(page.locator('[data-v19="receipt-history-verification"]')).toBeVisible();
});

test('L112 preset audit package exports source-to-resolved decisions without config/signature',async({page})=>{
  await child(page);const audit={workloadPresetImportHistory:[{at:'2026-09-08T03:00:00.000Z',strategy:'rename',decisions:[{status:'resolved',sourceId:'same',sourceName:'Cuối tuần',resolvedId:'same-2',resolvedName:'Cuối tuần (2)',nameConflict:true,idConflict:true}],added:[{id:'same-2',name:'Cuối tuần (2)',signature:'internal-signature'}]}]};await page.evaluate((x)=>{const s=JSON.parse(localStorage.getItem('growup_mychildren_v1'));s.settings={...s.settings,...x};localStorage.setItem('growup_mychildren_v1',JSON.stringify(s));},audit);await reload(page);
  const dl=page.waitForEvent('download');await page.locator('#v18ExportPresetAudit').click();const file=await dl;const text=await readFile(await file.path(),'utf8');expect(text).not.toMatch(/internal-signature|"config"|childId/);const pkg=JSON.parse(text);expect(pkg.audits[0].decisions[0].sourceId).toBe('same');expect(pkg.audits[0].decisions[0].resolvedId).toBe('same-2');
  await page.locator('#v18VerifyPresetAuditForm input[name="file"]').setInputFiles({name:'audit.json',mimeType:'application/json',buffer:Buffer.from(text)});await page.locator('#v18VerifyPresetAuditForm button[type="submit"]').click();await expect(page.locator('#v18PresetAuditStatus')).toContainText('1 conflict');
});

test('L113 Saved Search direct v17 apply is retired and v18 managed import can undo exact delta',async({page})=>{
  await child(page);await expect(page.locator('#v17SavedReceiptImportForm')).toBeHidden();const disabled=await page.locator('#v17SavedReceiptImportForm input, #v17SavedReceiptImportForm button').evaluateAll((nodes)=>nodes.every((node)=>node.disabled));expect(disabled).toBe(true);
  const pkg=buildIntegritySavedSearchReceiptPackage({savedSearchPackageVerificationReceipts:[{at:'2026-09-08T04:00:00.000Z',format:'saved-v18',algorithm:'SHA-256',result:'valid'}]});await page.locator('#v18SavedReceiptImportForm input[name="file"]').setInputFiles({name:'saved.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(pkg))});await page.locator('#v18SavedReceiptImportForm button[type="submit"]').click();await expect(page.locator('#v18ApplySavedReceipt')).toBeEnabled();await page.locator('#v18ApplySavedReceipt').click();await expect(page.locator('#v18SavedReceiptStatus')).toContainText('Gần nhất');let settings=await page.evaluate(()=>JSON.parse(localStorage.getItem('growup_mychildren_v1')).settings);expect(settings.savedSearchReceiptImportHistory).toHaveLength(1);expect(settings.savedSearchPackageVerificationReceipts.some((item)=>item.format==='saved-v18')).toBe(true);
  page.once('dialog',(d)=>d.accept());await page.locator('#v18UndoSavedReceipt').click();await expect(page.locator('#v18SavedReceiptStatus')).toContainText('Chưa có managed');settings=await page.evaluate(()=>JSON.parse(localStorage.getItem('growup_mychildren_v1')).settings);expect(settings.savedSearchReceiptImportHistory).toEqual([]);expect(settings.savedSearchPackageVerificationReceipts.some((item)=>item.format==='saved-v18')).toBe(false);
});

test('L114 recovery receipt filter and confirmed-clear remain active while unsigned export is retired by L119',async({page})=>{
  await child(page);await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('growup_mychildren_v1'));s.settings.recoveryReconciliationReportVerificationReceipts=[{at:'2026-09-08T01:00:00.000Z',format:'a',algorithm:'SHA-256',result:'valid',rowCount:2},{at:'2026-09-09T01:00:00.000Z',format:'b',algorithm:'SHA-256',result:'invalid',rowCount:4}];localStorage.setItem('growup_mychildren_v1',JSON.stringify(s));});await reload(page);await page.locator('#v18RecoveryReceiptFilter select[name="result"]').selectOption('invalid');await page.locator('#v18RecoveryReceiptFilter button[type="submit"]').click();await expect(page.locator('#v18RecoveryReceiptStatus')).toContainText('1 receipt');
  await expect(page.locator('#v18ExportRecoveryReceipts')).toBeHidden();expect(await page.locator('#v18ExportRecoveryReceipts').isDisabled()).toBe(true);await expect(page.locator('[data-v19="recovery-receipt-integrity"]')).toBeVisible();
  page.once('dialog',(d)=>d.accept());await page.locator('#v18ClearRecoveryReceipts').click();await expect(page.locator('[data-v18="recovery-receipt-management"] .pill')).toContainText('1 receipt');const receipts=await page.evaluate(()=>JSON.parse(localStorage.getItem('growup_mychildren_v1')).settings.recoveryReconciliationReportVerificationReceipts);expect(receipts).toHaveLength(1);expect(receipts[0].result).toBe('valid');
});

test('L115 freshness policy creates review-only gate and v18 overview passes Axe',async({page})=>{
  await child(page);await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('growup_mychildren_v1'));s.settings.compatibilityEvidenceRecords=[{module:'legacy-review.js',flow:'overview',observed:true,active:false,at:'2026-08-01T00:00:00.000Z'}];localStorage.setItem('growup_mychildren_v1',JSON.stringify(s));});await reload(page);await page.locator('#v18FreshnessForm input[name="freshDays"]').fill('14');await page.locator('#v18FreshnessForm button[type="submit"]').click();await expect(page.locator('[data-v18="freshness-policy"]')).toContainText('legacy-review.js');await expect(page.locator('#v18FreshnessStatus')).toContainText('retirementAllowed=false');const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('growup_mychildren_v1'));expect(state.settings.compatibilityEvidenceFreshnessPolicy.freshDays).toBe(14);expect(state.settings.compatibilityEvidenceRecords.some((item)=>item.module==='legacy-review.js')).toBe(true);
  const results=await new AxeBuilder({page}).analyze();expect(results.violations.filter((v)=>['serious','critical'].includes(v.impact))).toEqual([]);
});
