import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import { readFile } from 'node:fs/promises';
import { buildReceiptImportHistoryPackage } from '../src/core/receipt-import-history-package-integrity.js';

async function child(page){await page.goto('/');await page.locator('#emptyAddChild').click();await page.locator('#childForm input[name="name"]').fill('V19 Child');await page.locator('#childForm input[name="dateOfBirth"]').fill('2018-01-01');await page.locator('#childForm button.primary').click();await expect(page.locator('[data-v19="receipt-history-verification"]')).toBeVisible();}
async function reload(page){await page.reload();await expect(page.locator('[data-v19="receipt-history-verification"]')).toBeVisible();}

test('L116 v18 direct verify is retired and verification receipts are managed metadata only',async({page})=>{
  await child(page);await expect(page.locator('#v18VerifyReceiptHistoryForm')).toBeHidden();const oldDisabled=await page.locator('#v18VerifyReceiptHistoryForm input, #v18VerifyReceiptHistoryForm button').evaluateAll((nodes)=>nodes.every((node)=>node.disabled));expect(oldDisabled).toBe(true);
  const pkg=buildReceiptImportHistoryPackage({receiptImportHistory:[{at:'2026-09-08T02:00:00.000Z',packageFormat:'source-v19',added:[{at:'2026-09-08T01:00:00.000Z',format:'safe-v19',algorithm:'SHA-256',checksumResult:'valid'}]}]});await page.locator('#v19VerifyReceiptHistoryForm input[name="file"]').setInputFiles({name:'history.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(pkg))});await page.locator('#v19VerifyReceiptHistoryForm button[type="submit"]').click();await expect(page.locator('[data-v19="receipt-history-verification"] .pill')).toContainText('1/50');let settings=await page.evaluate(()=>JSON.parse(localStorage.getItem('growup_mychildren_v1')).settings);expect(settings.receiptImportHistoryPackageVerificationReceipts).toHaveLength(1);expect(Object.keys(settings.receiptImportHistoryPackageVerificationReceipts[0]).sort()).toEqual(['algorithm','at','format','importCount','receiptCount','result']);expect(JSON.stringify(settings.receiptImportHistoryPackageVerificationReceipts)).not.toMatch(/source-v19|checksum|payload/);
  await page.locator('#v19ReceiptVerificationFilter select[name="result"]').selectOption('valid');await page.locator('#v19ReceiptVerificationFilter button[type="submit"]').click();await expect(page.locator('#v19ReceiptVerificationStatus')).toContainText('1 verification receipt');await expect(page.locator('#v19ExportReceiptVerificationReceipts')).toBeHidden();expect(await page.locator('#v19ExportReceiptVerificationReceipts').isDisabled()).toBe(true);page.once('dialog',(d)=>d.accept());await page.locator('#v19ClearReceiptVerificationReceipts').click();await expect(page.locator('[data-v19="receipt-history-verification"] .pill')).toContainText('0/50');
});

test('L117 preset audit review filters conflict decisions without mutation',async({page})=>{
  await child(page);await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('growup_mychildren_v1'));s.settings.workloadPresetImportHistory=[{at:'2026-09-08T03:00:00.000Z',strategy:'rename',decisions:[{status:'resolved',sourceId:'a',sourceName:'Cuối tuần',resolvedId:'a-2',resolvedName:'Cuối tuần (2)',nameConflict:true,idConflict:true}],added:[{id:'a-2',name:'Cuối tuần (2)',signature:'internal'}]},{at:'2026-09-08T04:00:00.000Z',strategy:'skip',decisions:[{status:'conflict-skip',sourceId:'b',sourceName:'Tối',resolvedId:null,resolvedName:null,nameConflict:true,idConflict:false}],added:[]}];localStorage.setItem('growup_mychildren_v1',JSON.stringify(s));});await reload(page);const before=await page.evaluate(()=>JSON.stringify(JSON.parse(localStorage.getItem('growup_mychildren_v1')).settings.workloadPresetImportHistory));await page.locator('#v19PresetAuditReviewForm select[name="strategy"]').selectOption('rename');await page.locator('#v19PresetAuditReviewForm select[name="status"]').selectOption('resolved');await page.locator('#v19PresetAuditReviewForm input[name="conflictOnly"]').check();await page.locator('#v19PresetAuditReviewForm button[type="submit"]').click();await expect(page.locator('#v19PresetAuditReviewStatus')).toContainText('1 audit');await expect(page.locator('#v19PresetAuditReviewStatus')).toContainText('readOnly=true');const after=await page.evaluate(()=>JSON.stringify(JSON.parse(localStorage.getItem('growup_mychildren_v1')).settings.workloadPresetImportHistory));expect(after).toBe(before);
});

test('L118 Saved Search import-history portability exports signed package and verifies read-only',async({page})=>{
  await child(page);await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('growup_mychildren_v1'));s.settings.savedSearchReceiptImportHistory=[{id:'internal-id',at:'2026-09-08T05:00:00.000Z',packageFormat:'saved-source',added:[{at:'2026-09-08T04:00:00.000Z',format:'saved-v19',algorithm:'SHA-256',result:'valid'}]}];localStorage.setItem('growup_mychildren_v1',JSON.stringify(s));});await reload(page);const dl=page.waitForEvent('download');await page.locator('#v19ExportSavedSearchHistory').click();const file=await dl;const text=await readFile(await file.path(),'utf8');const pkg=JSON.parse(text);expect(pkg.manifest.algorithm).toBe('SHA-256');expect(pkg.imports).toHaveLength(1);expect(text).not.toMatch(/internal-id|criteria|snippet|healthRecords|nutritionLogs/);await expect(page.locator('#v19VerifySavedSearchHistoryForm')).toBeHidden();const oldDisabled=await page.locator('#v19VerifySavedSearchHistoryForm input, #v19VerifySavedSearchHistoryForm button').evaluateAll((nodes)=>nodes.every((node)=>node.disabled));expect(oldDisabled).toBe(true);
});

test('L119 unsigned v18 Recovery export is retired and signed package verification records metadata only',async({page})=>{
  await child(page);await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('growup_mychildren_v1'));s.settings.recoveryReconciliationReportVerificationReceipts=[{at:'2026-09-08T01:00:00.000Z',format:'report-v19',algorithm:'SHA-256',result:'valid',rowCount:3}];localStorage.setItem('growup_mychildren_v1',JSON.stringify(s));});await reload(page);await expect(page.locator('#v18ExportRecoveryReceipts')).toBeHidden();expect(await page.locator('#v18ExportRecoveryReceipts').isDisabled()).toBe(true);await expect(page.locator('#v18RecoveryReceiptFilter')).toBeVisible();const dl=page.waitForEvent('download');await page.locator('#v19RecoverySignedExportForm button[type="submit"]').click();const file=await dl;const text=await readFile(await file.path(),'utf8');const pkg=JSON.parse(text);expect(pkg.manifest.algorithm).toBe('SHA-256');expect(pkg.receipts).toHaveLength(1);await page.locator('#v19VerifyRecoveryReceiptPackageForm input[name="file"]').setInputFiles({name:'recovery-signed.json',mimeType:'application/json',buffer:Buffer.from(text)});await page.locator('#v19VerifyRecoveryReceiptPackageForm button[type="submit"]').click();await expect(page.locator('[data-v19="recovery-receipt-integrity"] .pill')).toContainText('1/50');const settings=await page.evaluate(()=>JSON.parse(localStorage.getItem('growup_mychildren_v1')).settings);expect(settings.recoveryVerificationReceiptPackageVerificationReceipts).toHaveLength(1);expect(Object.keys(settings.recoveryVerificationReceiptPackageVerificationReceipts[0]).sort()).toEqual(['algorithm','at','format','receiptCount','result']);expect(JSON.stringify(settings.recoveryVerificationReceiptPackageVerificationReceipts)).not.toMatch(/report-v19|rowCount|checksum|payload/);
});

test('L120 freshness review stays non-destructive and Axe PASS can only be recorded after actual local audit',async({page})=>{
  await child(page);await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('growup_mychildren_v1'));s.settings.compatibilityEvidenceRecords=[{module:'legacy-v19.js',flow:'overview',observed:true,active:false,at:'2026-08-01T00:00:00.000Z'}];localStorage.setItem('growup_mychildren_v1',JSON.stringify(s));});await reload(page);const dl=page.waitForEvent('download');await page.locator('#v19ExportFreshnessReview').click();const file=await dl;const text=await readFile(await file.path(),'utf8');const pkg=JSON.parse(text);expect(pkg.manifest.algorithm).toBe('SHA-256');expect(pkg.retirementAllowed).toBe(false);expect(pkg.actionsApplied).toBe(false);await page.locator('#v19VerifyFreshnessReviewForm input[name="file"]').setInputFiles({name:'freshness.json',mimeType:'application/json',buffer:Buffer.from(text)});await page.locator('#v19VerifyFreshnessReviewForm button[type="submit"]').click();await expect(page.locator('#v19FreshnessReviewStatus')).toContainText('retirementAllowed=false');const buttons=await page.locator('[data-v19="freshness-review-package"] button').allTextContents();expect(buttons.some((label)=>/manual.*pass|đánh dấu.*pass/i.test(label))).toBe(false);await page.locator('#v19AxeRecheckRequestForm select[name="module"]').selectOption('legacy-v19.js');await page.locator('#v19AxeRecheckRequestForm button[type="submit"]').click();await expect(page.locator('[data-v19="freshness-review-package"]')).toContainText('pending');
  const axe=await new AxeBuilder({page}).analyze();expect(axe.violations.filter((v)=>['serious','critical'].includes(v.impact))).toEqual([]);
  const recorded=await page.evaluate(async()=>{const state=JSON.parse(localStorage.getItem('growup_mychildren_v1'));const mod=await import('/src/core/compatibility-evidence-freshness-review-package.js');const result=mod.recordActualLocalAxeRecheck(state.settings||{},{module:'legacy-v19.js',active:false,passed:true,source:'actual-local-axe'},new Date().toISOString());if(result.changed){state.settings=result.settings;localStorage.setItem('growup_mychildren_v1',JSON.stringify(state));}return {changed:result.changed,reason:result.reason};});expect(recorded.changed).toBe(true);await reload(page);await expect(page.locator('[data-v19="freshness-review-package"]')).toContainText('PASS actual local Axe');const settings=await page.evaluate(()=>JSON.parse(localStorage.getItem('growup_mychildren_v1')).settings);expect(settings.compatibilityEvidenceRecords.some((item)=>item.module==='legacy-v19.js'&&item.flow==='axe')).toBe(true);expect(settings.compatibilityAxeRecheckRequests[0].status).toBe('passed');
});
