import { ageOnDate, stageForAge, bmi, todayKey, progressPercent, childTemplate, makeId } from './core/model.js';
import { loadState, saveState, exportState, validateImportedState } from './core/store.js';
import { buildInsights } from './core/insights.js';

let state = loadState();
let page = 'overview';
const app = document.querySelector('#app');

const NAV = [
  ['overview', 'Tổng quan'], ['learning', 'Học tập'], ['skills', 'Kỹ năng'], ['health', 'Sức khỏe'],
  ['physical', 'Thể chất'], ['nutrition', 'Dinh dưỡng'], ['habits', 'Thói quen'], ['assessment', 'Đánh giá'],
  ['portfolio', 'Portfolio'], ['roadmap', 'Lộ trình'], ['calendar', 'Lịch & nhắc nhở'], ['ai', 'AI cố vấn']
];

function escapeHtml(value = '') {
  return String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
}
function selectedChild() { return state.children.find((child) => child.id === state.selectedChildId) || state.children[0] || null; }
function commit(message = '') { if (state.children.length && !selectedChild()) state.selectedChildId = state.children[0].id; saveState(state); render(); if (message) toast(message); }
function updateChild(mutator, message = '') { const child = selectedChild(); if (!child) return; const idx = state.children.findIndex((item) => item.id === child.id); const copy = structuredClone(child); mutator(copy); state.children[idx] = copy; commit(message); }
function updateChildNoCommit(mutator) { const child = selectedChild(); if (!child) return; const idx = state.children.findIndex(c => c.id === child.id); const copy = structuredClone(child); mutator(copy); state.children[idx] = copy; }
function toast(text) { document.querySelector('.toast')?.remove(); const node = document.createElement('div'); node.className = 'toast'; node.textContent = text; document.body.appendChild(node); setTimeout(() => node.remove(), 2200); }
function formatDate(value) { if (!value) return '—'; const date = new Date(`${value}T00:00:00`); return Number.isNaN(date.getTime()) ? escapeHtml(value) : date.toLocaleDateString('vi-VN'); }

function shell(content, title, subtitle = '') {
  const child = selectedChild();
  const childOptions = state.children.map((item) => `<option value="${item.id}" ${item.id === child?.id ? 'selected' : ''}>${escapeHtml(item.name)}</option>`).join('');
  const nav = NAV.map(([key, label]) => `<button data-nav="${key}" class="${page === key ? 'active' : ''}">${label}</button>`).join('');
  return `<div class="shell"><aside class="sidebar"><div class="brand"><img src="./assets/icon.svg" alt=""><div><strong>GrowUP My Children</strong><small>3–18 tuổi</small></div></div><div class="child-switcher"><label><span>Hồ sơ đang xem</span>${state.children.length ? `<select id="childSelect">${childOptions}</select>` : `<div class="muted">Chưa có hồ sơ trẻ</div>`}</label></div><nav class="nav">${nav}</nav><select id="mobileNav" class="mobile-nav">${NAV.map(([key,label]) => `<option value="${key}" ${page === key ? 'selected' : ''}>${label}</option>`).join('')}</select><div class="sidebar-footer"><button id="addChildBtn">+ Thêm trẻ</button><button id="backupBtn">Sao lưu</button></div></aside><main class="main"><header class="topbar"><div><h1>${escapeHtml(title)}</h1><p>${escapeHtml(subtitle)}</p></div>${child ? `<span class="badge">${escapeHtml(child.name)} · ${ageOnDate(child.dateOfBirth)} tuổi</span>` : '<span class="badge">Bắt đầu hồ sơ đầu tiên</span>'}</header>${content}</main></div>`;
}
function emptyNoChild() { return `<div class="card"><div class="empty"><h3>Chưa có hồ sơ phát triển</h3><p>Tạo hồ sơ đầu tiên để bắt đầu theo dõi lộ trình 3–18 tuổi.</p><button class="primary" id="emptyAddChild">Tạo hồ sơ trẻ</button></div></div>`; }

function overviewPage(child) {
  if (!child) return emptyNoChild();
  const age = ageOnDate(child.dateOfBirth), stage = stageForAge(age), lastHealth = child.healthRecords.at(-1), goalProgress = progressPercent(child.learningGoals), today = todayKey();
  const habitDone = child.habits.filter((h) => h.logs?.includes(today)).length;
  const timeline = Array.from({ length: 16 }, (_, i) => i + 3).map((n, idx) => `${idx ? '<span class="timeline-line"></span>' : ''}<div class="timeline-step ${n === Math.min(18, Math.max(3, age)) ? 'current' : ''}"><div class="timeline-dot">${n}</div><small>tuổi</small></div>`).join('');
  const upcoming = child.reminders.filter((r) => !r.completed).sort((a,b) => a.date.localeCompare(b.date)).slice(0, 4);
  return `<section class="grid cards-4"><article class="card"><span class="muted">Giai đoạn</span><div class="metric" style="font-size:22px">${stage.title}</div><small>${stage.focus.slice(0,3).join(' · ')}</small></article><article class="card"><span class="muted">Mục tiêu học tập</span><div class="metric">${goalProgress}%</div><div class="progress"><span style="width:${goalProgress}%"></span></div></article><article class="card"><span class="muted">Thói quen hôm nay</span><div class="metric">${habitDone}/${child.habits.length}</div><small>hoàn thành trong ngày</small></article><article class="card"><span class="muted">Sức khỏe gần nhất</span><div class="metric" style="font-size:22px">${lastHealth ? `${lastHealth.height || '—'} cm` : 'Chưa ghi'}</div><small>${lastHealth ? `${lastHealth.weight || '—'} kg · ${formatDate(lastHealth.date)}` : 'Thêm bản ghi sức khỏe'}</small></article></section><section class="grid two-col" style="margin-top:16px"><article class="card"><h2>Timeline phát triển 3–18 tuổi</h2><div class="timeline">${timeline}</div><div class="notice">Mục tiêu dài hạn được dùng để định hướng, không đóng cứng trẻ vào một nghề hay một thành tích duy nhất.</div></article><article class="card"><h2>Sắp tới</h2>${upcoming.length ? `<div class="list">${upcoming.map(r => `<div class="item"><div><div class="item-title">${escapeHtml(r.title)}</div><small>${formatDate(r.date)}</small></div><span class="pill">${escapeHtml(r.type || 'Nhắc nhở')}</span></div>`).join('')}</div>` : '<div class="empty">Chưa có nhắc nhở.</div>'}</article></section><section class="card" style="margin-top:16px"><h2>Trọng tâm giai đoạn hiện tại</h2><div class="grid cards-3">${stage.focus.map((focus) => `<div class="item"><span>${escapeHtml(focus)}</span><span class="pill">Ưu tiên</span></div>`).join('')}</div></section>`;
}
function twoPanel(title, form, items, metaFn, type) { const list = items.map((item) => `<div class="item"><div class="item-main"><div class="item-title" style="${item.completed ? 'text-decoration:line-through;opacity:.6' : ''}">${escapeHtml(item.title)}</div><small>${metaFn(item)}</small></div><button class="${item.completed ? 'secondary' : 'primary'}" data-${type}-toggle="${item.id}">${item.completed ? 'Đã xong' : 'Hoàn thành'}</button></div>`).join(''); return `<section class="grid two-col"><article class="card"><h2>${title}</h2>${form}</article><article class="card"><h2>Danh sách</h2><div class="list">${list || '<div class="empty">Chưa có dữ liệu.</div>'}</div></article></section>`; }
function learningPage(child) { if (!child) return emptyNoChild(); return twoPanel('Mục tiêu học tập', `<form id="learningForm" class="form"><label><span>Mục tiêu</span><input name="title" required placeholder="Ví dụ: đọc 20 phút mỗi ngày"></label><div class="form-row"><label><span>Lĩnh vực</span><select name="subject"><option>Ngôn ngữ</option><option>Toán</option><option>Ngoại ngữ</option><option>Khoa học</option><option>Công nghệ/AI</option><option>Nghệ thuật</option><option>Khác</option></select></label><label><span>Hạn mục tiêu</span><input type="date" name="dueDate"></label></div><button class="primary">Thêm mục tiêu</button></form>`, child.learningGoals, (item) => `${escapeHtml(item.subject)}${item.dueDate ? ` · ${formatDate(item.dueDate)}` : ''}`, 'learning'); }
function skillsPage(child) { if (!child) return emptyNoChild(); const list = child.skills.map((s) => `<div class="item"><div class="item-main"><div class="item-title">${escapeHtml(s.name)}</div><small>Cập nhật ${formatDate(s.date)}</small></div><span class="pill">Level ${s.level}/10</span></div>`).join(''); return `<section class="grid two-col"><article class="card"><h2>Ghi nhận năng lực</h2><form id="skillForm" class="form"><label><span>Năng lực</span><input name="name" required placeholder="Logic, giao tiếp, sáng tạo..."></label><label><span>Mức hiện tại (1–10)</span><input name="level" type="number" min="1" max="10" required value="5"></label><button class="primary">Lưu đánh giá</button></form></article><article class="card"><h2>Cây năng lực</h2>${list || '<div class="empty">Chưa có đánh giá năng lực.</div>'}</article></section>`; }
function healthPage(child) { if (!child) return emptyNoChild(); const latest = child.healthRecords.at(-1), value = latest ? bmi(latest.height, latest.weight) : null; const list = child.healthRecords.slice().reverse().map((h) => `<div class="item"><div><div class="item-title">${formatDate(h.date)}</div><small>${h.height || '—'} cm · ${h.weight || '—'} kg · ngủ ${h.sleep || '—'} giờ</small></div><span class="pill">BMI ${bmi(h.height,h.weight) ?? '—'}</span></div>`).join(''); return `<div class="notice" style="margin-bottom:16px">Dữ liệu sức khỏe trong bản v1 chỉ lưu cục bộ trên thiết bị. BMI ở trẻ em không được diễn giải bằng ngưỡng BMI người lớn; đánh giá phát triển cần theo tuổi, giới và chuyên môn y tế.</div><section class="grid two-col"><article class="card"><h2>Bản ghi sức khỏe</h2><form id="healthForm" class="form"><div class="form-row"><label><span>Ngày đo</span><input name="date" type="date" required value="${todayKey()}"></label><label><span>Giấc ngủ (giờ)</span><input name="sleep" type="number" step="0.1" min="0" max="24"></label></div><div class="form-row"><label><span>Chiều cao (cm)</span><input name="height" type="number" step="0.1" min="20"></label><label><span>Cân nặng (kg)</span><input name="weight" type="number" step="0.1" min="1"></label></div><label><span>Ghi chú</span><textarea name="note" placeholder="Khám định kỳ, triệu chứng, dặn dò..."></textarea></label><button class="primary">Lưu bản ghi</button></form></article><article class="card"><h2>Theo dõi gần đây</h2>${latest ? `<p>Chiều cao: <strong>${latest.height || '—'} cm</strong></p><p>Cân nặng: <strong>${latest.weight || '—'} kg</strong></p><p>BMI tính toán: <strong>${value ?? '—'}</strong></p>` : ''}<div class="list">${list || '<div class="empty">Chưa có dữ liệu sức khỏe.</div>'}</div></article></section>`; }
function physicalPage(child) { if (!child) return emptyNoChild(); const list = child.physicalActivities.slice().reverse().map(a => `<div class="item"><div><div class="item-title">${escapeHtml(a.activity)}</div><small>${formatDate(a.date)} · ${a.minutes} phút</small></div><span class="pill">Vận động</span></div>`).join(''); return `<section class="grid two-col"><article class="card"><h2>Hoạt động thể chất</h2><form id="physicalForm" class="form"><label><span>Hoạt động</span><input name="activity" required placeholder="Bơi, chạy, đạp xe..."></label><div class="form-row"><label><span>Ngày</span><input name="date" type="date" required value="${todayKey()}"></label><label><span>Thời lượng (phút)</span><input name="minutes" type="number" min="1" max="600" required></label></div><button class="primary">Ghi hoạt động</button></form></article><article class="card"><h2>Lịch sử vận động</h2><div class="list">${list || '<div class="empty">Chưa ghi hoạt động.</div>'}</div></article></section>`; }
function nutritionPage(child) { if (!child) return emptyNoChild(); const today = todayKey(), todayLog = child.nutritionLogs.find((x) => x.date === today); const list = child.nutritionLogs.slice().reverse().slice(0,10).map(n => `<div class="item"><div><div class="item-title">${formatDate(n.date)}</div><small>Nước ${n.water || 0} cốc · Rau/trái cây ${n.plants ? 'Có' : 'Chưa'} · Protein ${n.protein ? 'Có' : 'Chưa'}</small></div><span class="pill">Nhật ký</span></div>`).join(''); return `<section class="grid two-col"><article class="card"><h2>Dinh dưỡng hôm nay</h2><form id="nutritionForm" class="form"><label><span>Số cốc nước</span><input name="water" type="number" min="0" max="30" value="${todayLog?.water ?? 0}"></label><label><input name="plants" type="checkbox" style="width:auto" ${todayLog?.plants ? 'checked' : ''}> Có rau/trái cây trong ngày</label><label><input name="protein" type="checkbox" style="width:auto" ${todayLog?.protein ? 'checked' : ''}> Có nguồn protein phù hợp</label><label><span>Ghi chú</span><textarea name="note">${escapeHtml(todayLog?.note || '')}</textarea></label><button class="primary">Lưu nhật ký hôm nay</button></form></article><article class="card"><h2>Lịch sử gần đây</h2><div class="list">${list || '<div class="empty">Chưa có nhật ký dinh dưỡng.</div>'}</div></article></section>`; }
function habitsPage(child) { if (!child) return emptyNoChild(); const today = todayKey(); const list = child.habits.map(h => { const done = h.logs?.includes(today); return `<div class="item"><div><div class="item-title">${escapeHtml(h.title)}</div><small>${escapeHtml(h.frequency || 'Hằng ngày')}</small></div><button class="${done ? 'secondary' : 'primary'}" data-habit-toggle="${h.id}">${done ? 'Đã hoàn thành' : 'Đánh dấu hôm nay'}</button></div>`; }).join(''); return `<section class="grid two-col"><article class="card"><h2>Tạo thói quen</h2><form id="habitForm" class="form"><label><span>Thói quen</span><input name="title" required placeholder="Đọc sách, ngủ đúng giờ..."></label><label><span>Tần suất</span><select name="frequency"><option>Hằng ngày</option><option>Ngày học</option><option>3 lần/tuần</option><option>Hằng tuần</option></select></label><button class="primary">Thêm thói quen</button></form></article><article class="card"><h2>Hôm nay</h2><div class="list">${list || '<div class="empty">Chưa có thói quen.</div>'}</div></article></section>`; }
function assessmentPage(child) { if (!child) return emptyNoChild(); const skillAvg = child.skills.length ? (child.skills.reduce((sum,s) => sum + Number(s.level),0) / child.skills.length).toFixed(1) : '—', goalP = progressPercent(child.learningGoals), today = todayKey(), habitP = child.habits.length ? Math.round(child.habits.filter(h => h.logs?.includes(today)).length / child.habits.length * 100) : 0; return `<section class="grid cards-3"><article class="card"><span class="muted">Mục tiêu học tập</span><div class="metric">${goalP}%</div><div class="progress"><span style="width:${goalP}%"></span></div></article><article class="card"><span class="muted">Năng lực trung bình</span><div class="metric">${skillAvg}</div><small>trên thang 10, từ các đánh giá đã nhập</small></article><article class="card"><span class="muted">Thói quen hôm nay</span><div class="metric">${habitP}%</div><small>không dùng làm điểm thưởng/phạt</small></article></section><section class="card" style="margin-top:16px"><h2>Nguyên tắc đánh giá</h2><p class="muted">GrowUP theo dõi xu hướng theo thời gian thay vì xếp hạng trẻ bằng một điểm tổng hợp duy nhất. Dữ liệu học tập, sức khỏe, thể chất và thói quen được giữ riêng để tránh suy diễn quá mức.</p></section>`; }
function portfolioPage(child) { if (!child) return emptyNoChild(); const list = child.portfolio.slice().reverse().map(p => `<div class="item"><div><div class="item-title">${escapeHtml(p.title)}</div><small>${formatDate(p.date)} · ${escapeHtml(p.type)}</small>${p.note ? `<div class="muted">${escapeHtml(p.note)}</div>` : ''}</div><span class="pill">Portfolio</span></div>`).join(''); return `<section class="grid two-col"><article class="card"><h2>Thêm dấu mốc</h2><form id="portfolioForm" class="form"><label><span>Tiêu đề</span><input name="title" required placeholder="Dự án, chứng chỉ, thành tích..."></label><div class="form-row"><label><span>Loại</span><select name="type"><option>Dự án</option><option>Chứng chỉ</option><option>Giải thưởng</option><option>Sản phẩm</option><option>Dấu mốc</option></select></label><label><span>Ngày</span><input name="date" type="date" value="${todayKey()}"></label></div><label><span>Mô tả</span><textarea name="note"></textarea></label><button class="primary">Lưu vào portfolio</button></form></article><article class="card"><h2>Hồ sơ phát triển</h2><div class="list">${list || '<div class="empty">Chưa có dấu mốc.</div>'}</div></article></section>`; }
function roadmapPage(child) { if (!child) return emptyNoChild(); const list = child.roadmap.slice().sort((a,b) => Number(a.age)-Number(b.age)).map(r => `<div class="item"><div><div class="item-title">${escapeHtml(r.goal)}</div><small>Mục tiêu khoảng ${r.age} tuổi · ${escapeHtml(r.area)}</small></div><span class="pill">${r.age} tuổi</span></div>`).join(''); return `<div class="notice" style="margin-bottom:16px">Roadmap là giả thuyết có thể thay đổi theo sở thích, năng lực, sức khỏe và bối cảnh xã hội; không xem là cam kết nghề nghiệp.</div><section class="grid two-col"><article class="card"><h2>Backward planning</h2><form id="roadmapForm" class="form"><label><span>Mục tiêu tương lai</span><input name="goal" required placeholder="Ví dụ: đạt năng lực tiếng Anh học thuật"></label><div class="form-row"><label><span>Tuổi dự kiến</span><input name="age" type="number" min="3" max="23" required value="18"></label><label><span>Lĩnh vực</span><select name="area"><option>Học thuật</option><option>Ngoại ngữ</option><option>Kỹ năng</option><option>Thể chất</option><option>Portfolio</option><option>Nghề nghiệp</option></select></label></div><button class="primary">Thêm mốc roadmap</button></form></article><article class="card"><h2>Lộ trình hiện tại</h2><div class="list">${list || '<div class="empty">Chưa có mốc dài hạn.</div>'}</div></article></section>`; }
function calendarPage(child) { if (!child) return emptyNoChild(); const list = child.reminders.slice().sort((a,b)=>a.date.localeCompare(b.date)).map(r => `<div class="item"><div><div class="item-title">${escapeHtml(r.title)}</div><small>${formatDate(r.date)} · ${escapeHtml(r.type)}</small></div><button class="${r.completed ? 'secondary' : 'primary'}" data-reminder-toggle="${r.id}">${r.completed ? 'Đã xong' : 'Hoàn thành'}</button></div>`).join(''); return `<section class="grid two-col"><article class="card"><h2>Lịch & nhắc nhở</h2><form id="reminderForm" class="form"><label><span>Nội dung</span><input name="title" required placeholder="Khám sức khỏe, thi, luyện tập..."></label><div class="form-row"><label><span>Ngày</span><input name="date" type="date" required></label><label><span>Loại</span><select name="type"><option>Học tập</option><option>Sức khỏe</option><option>Thể chất</option><option>Dinh dưỡng</option><option>Gia đình</option></select></label></div><button class="primary">Thêm nhắc nhở</button></form><p class="muted">Kết nối Google Calendar được dành cho lớp tích hợp sau khi có cơ chế đăng nhập và cấp quyền.</p></article><article class="card"><h2>Danh sách</h2><div class="list">${list || '<div class="empty">Chưa có sự kiện.</div>'}</div></article></section>`; }
function aiPage(child) { if (!child) return emptyNoChild(); const insights = buildInsights(child); return `<div class="notice" style="margin-bottom:16px">Bản v1 dùng quy tắc cục bộ, không gửi dữ liệu trẻ ra dịch vụ AI bên ngoài. Nội dung sức khỏe chỉ mang tính quản lý hồ sơ, không thay thế tư vấn y khoa.</div><section class="card"><h2>Gợi ý phát triển</h2><div class="list">${insights.map(i => `<div class="insight ${i.level}"><strong>${escapeHtml(i.title)}</strong><span>${escapeHtml(i.text)}</span></div>`).join('')}</div></section>`; }

function addChildDialog() { const backdrop = document.createElement('div'); backdrop.style.cssText = 'position:fixed;inset:0;background:rgba(20,35,40,.55);display:grid;place-items:center;padding:16px;z-index:100'; backdrop.innerHTML = `<div class="card" style="width:min(560px,100%);max-height:90vh;overflow:auto"><div style="display:flex;justify-content:space-between;gap:12px"><h2>Tạo hồ sơ trẻ</h2><button id="closeDialog" class="secondary">Đóng</button></div><form id="childForm" class="form"><label><span>Tên gọi</span><input name="name" required maxlength="80"></label><div class="form-row"><label><span>Ngày sinh</span><input type="date" name="dateOfBirth" required></label><label><span>Giới tính (tùy chọn)</span><select name="gender"><option value="">Không ghi</option><option>Nữ</option><option>Nam</option><option>Khác</option></select></label></div><div class="form-row"><label><span>Trường</span><input name="school"></label><label><span>Lớp</span><input name="className"></label></div><button class="primary">Tạo hồ sơ</button></form></div>`; document.body.appendChild(backdrop); backdrop.querySelector('#closeDialog').onclick = () => backdrop.remove(); backdrop.onclick = (e) => { if (e.target === backdrop) backdrop.remove(); }; backdrop.querySelector('#childForm').onsubmit = (e) => { e.preventDefault(); const data = Object.fromEntries(new FormData(e.currentTarget)); if (!data.name?.trim()) return; const child = childTemplate(data); state.children.push(child); state.selectedChildId = child.id; backdrop.remove(); commit('Đã tạo hồ sơ trẻ.'); }; }
function backupDialog() { const backdrop = document.createElement('div'); backdrop.style.cssText = 'position:fixed;inset:0;background:rgba(20,35,40,.55);display:grid;place-items:center;padding:16px;z-index:100'; backdrop.innerHTML = `<div class="card" style="width:min(720px,100%);max-height:90vh;overflow:auto"><div style="display:flex;justify-content:space-between;gap:12px"><h2>Sao lưu & phục hồi</h2><button id="closeBackup" class="secondary">Đóng</button></div><p class="muted">Xuất JSON để lưu riêng. Khi nhập, dữ liệu hiện tại trên thiết bị sẽ được thay thế.</p><div class="actions"><button class="primary" id="downloadBackup">Tải bản sao JSON</button><label class="secondary" style="cursor:pointer">Nhập JSON<input id="importBackup" type="file" accept="application/json" hidden></label></div>${selectedChild() ? `<hr style="border:0;border-top:1px solid var(--line);margin:20px 0"><button class="danger" id="deleteChild">Xóa hồ sơ ${escapeHtml(selectedChild().name)}</button>` : ''}</div>`; document.body.appendChild(backdrop); backdrop.querySelector('#closeBackup').onclick = () => backdrop.remove(); backdrop.querySelector('#downloadBackup').onclick = () => { const blob = new Blob([exportState(state)], { type: 'application/json' }); const url = URL.createObjectURL(blob), a = document.createElement('a'); a.href = url; a.download = `growup-backup-${todayKey()}.json`; a.click(); URL.revokeObjectURL(url); }; backdrop.querySelector('#importBackup').onchange = async (e) => { const file = e.target.files?.[0]; if (!file) return; try { state = validateImportedState(await file.text()); backdrop.remove(); commit('Đã phục hồi dữ liệu.'); } catch (err) { toast(err.message); } }; const del = backdrop.querySelector('#deleteChild'); if (del) del.onclick = () => { const child = selectedChild(); if (!child || !confirm(`Xóa hồ sơ ${child.name}? Dữ liệu cục bộ của hồ sơ này sẽ mất.`)) return; state.children = state.children.filter((c) => c.id !== child.id); state.selectedChildId = state.children[0]?.id || null; backdrop.remove(); commit('Đã xóa hồ sơ.'); }; }

function attachEvents() {
  document.querySelectorAll('[data-nav]').forEach((btn) => btn.onclick = () => { page = btn.dataset.nav; render(); });
  const mobileNav = document.querySelector('#mobileNav'); if (mobileNav) mobileNav.onchange = (e) => { page = e.target.value; render(); };
  const childSelect = document.querySelector('#childSelect'); if (childSelect) childSelect.onchange = (e) => { state.selectedChildId = e.target.value; commit(); };
  document.querySelector('#addChildBtn')?.addEventListener('click', addChildDialog); document.querySelector('#emptyAddChild')?.addEventListener('click', addChildDialog); document.querySelector('#backupBtn')?.addEventListener('click', backupDialog);
  const formHandler = (selector, handler, message) => { const form = document.querySelector(selector); if (form) form.onsubmit = (e) => { e.preventDefault(); handler(Object.fromEntries(new FormData(e.currentTarget)), e.currentTarget); commit(message); }; };
  formHandler('#learningForm', (d) => updateChildNoCommit(c => c.learningGoals.push({ id: makeId('goal'), title: d.title.trim(), subject: d.subject, dueDate: d.dueDate, completed: false, createdAt: new Date().toISOString() })), 'Đã thêm mục tiêu.');
  formHandler('#skillForm', (d) => updateChildNoCommit(c => { const old = c.skills.find(s => s.name.toLowerCase() === d.name.trim().toLowerCase()); if (old) { old.level = Number(d.level); old.date = todayKey(); } else c.skills.push({ id: makeId('skill'), name: d.name.trim(), level: Number(d.level), date: todayKey() }); }), 'Đã cập nhật năng lực.');
  formHandler('#healthForm', (d) => updateChildNoCommit(c => c.healthRecords.push({ id: makeId('health'), date: d.date, height: Number(d.height) || null, weight: Number(d.weight) || null, sleep: Number(d.sleep) || null, note: d.note.trim() })), 'Đã lưu sức khỏe.');
  formHandler('#physicalForm', (d) => updateChildNoCommit(c => c.physicalActivities.push({ id: makeId('physical'), activity: d.activity.trim(), date: d.date, minutes: Number(d.minutes) })), 'Đã ghi vận động.');
  const nutritionForm = document.querySelector('#nutritionForm'); if (nutritionForm) nutritionForm.onsubmit = (e) => { e.preventDefault(); const fd = new FormData(e.currentTarget), d = Object.fromEntries(fd); updateChildNoCommit(c => { const date = todayKey(), old = c.nutritionLogs.find(n => n.date === date), next = { id: old?.id || makeId('nutrition'), date, water: Number(d.water) || 0, plants: fd.has('plants'), protein: fd.has('protein'), note: d.note.trim() }; if (old) Object.assign(old, next); else c.nutritionLogs.push(next); }); commit('Đã lưu dinh dưỡng.'); };
  formHandler('#habitForm', (d) => updateChildNoCommit(c => c.habits.push({ id: makeId('habit'), title: d.title.trim(), frequency: d.frequency, logs: [] })), 'Đã thêm thói quen.');
  formHandler('#portfolioForm', (d) => updateChildNoCommit(c => c.portfolio.push({ id: makeId('portfolio'), title: d.title.trim(), type: d.type, date: d.date || todayKey(), note: d.note.trim() })), 'Đã thêm portfolio.');
  formHandler('#roadmapForm', (d) => updateChildNoCommit(c => c.roadmap.push({ id: makeId('roadmap'), goal: d.goal.trim(), age: Number(d.age), area: d.area })), 'Đã thêm mốc roadmap.');
  formHandler('#reminderForm', (d) => updateChildNoCommit(c => c.reminders.push({ id: makeId('reminder'), title: d.title.trim(), date: d.date, type: d.type, completed: false })), 'Đã thêm nhắc nhở.');
  document.querySelectorAll('[data-learning-toggle]').forEach(btn => btn.onclick = () => updateChild(c => { const x = c.learningGoals.find(g => g.id === btn.dataset.learningToggle); if (x) x.completed = !x.completed; }, 'Đã cập nhật mục tiêu.'));
  document.querySelectorAll('[data-habit-toggle]').forEach(btn => btn.onclick = () => updateChild(c => { const x = c.habits.find(h => h.id === btn.dataset.habitToggle); if (!x) return; x.logs ||= []; const today = todayKey(); x.logs = x.logs.includes(today) ? x.logs.filter(d => d !== today) : [...x.logs, today]; }, 'Đã cập nhật thói quen.'));
  document.querySelectorAll('[data-reminder-toggle]').forEach(btn => btn.onclick = () => updateChild(c => { const x = c.reminders.find(r => r.id === btn.dataset.reminderToggle); if (x) x.completed = !x.completed; }, 'Đã cập nhật nhắc nhở.'));
}
function render() { const child = selectedChild(); const details = child ? `${child.school ? `${child.school}${child.className ? ` · ${child.className}` : ''}` : 'Hồ sơ phát triển cá nhân'}` : 'Thiết kế lộ trình học tập, sức khỏe và phát triển dài hạn'; const pages = { overview: ['Tổng quan phát triển', overviewPage], learning: ['Học tập', learningPage], skills: ['Kỹ năng', skillsPage], health: ['Sức khỏe', healthPage], physical: ['Thể chất', physicalPage], nutrition: ['Dinh dưỡng', nutritionPage], habits: ['Thói quen & kỹ năng sống', habitsPage], assessment: ['Đánh giá', assessmentPage], portfolio: ['Portfolio', portfolioPage], roadmap: ['Lộ trình tương lai', roadmapPage], calendar: ['Lịch & nhắc nhở', calendarPage], ai: ['AI cố vấn phát triển', aiPage] }; const [title, renderer] = pages[page] || pages.overview; app.innerHTML = shell(renderer(child), title, details); attachEvents(); }
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('./sw.js').catch(() => {}));
render();
