import { migrateState } from './core/schema.js';
import { saveState, appendAudit } from './core/store.js';
import { childDataPortabilityMap, PORTABILITY_NOTE } from './core/portability-map.js';
import { familyWorkloadWindows, FAMILY_WORKLOAD_NOTE } from './core/family-workload.js';
import { savedSearchViews, saveSearchView, removeSearchView, SAVED_SEARCH_NOTE } from './core/saved-search.js';
import { recoverySchedule, setRecoverySchedule, recoveryReminderCandidate, RECOVERY_SCHEDULE_NOTE } from './core/recovery-schedule.js';
import { compatibilityUsageSnapshot, retirementCandidates, RUNTIME_COMPATIBILITY_NOTE } from './core/runtime-compatibility.js';

const STORAGE_KEY='growup_mychildren_v1';
let scheduled=false;
const observer=new MutationObserver(()=>queueMicrotask(enhanceV11));
function readState(){try{return migrateState(JSON.parse(localStorage.getItem(STORAGE_KEY)||'{"version":5,"children":[]}'));}catch{return migrateState({version:5,children:[]});}}
function esc(v=''){return String(v).replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function saveAudit(state,type,details={}){saveState(appendAudit(state,type,details));}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}

function portabilityPanel(state){const rows=childDataPortabilityMap(state);return `<section class="card v11-panel" data-v11="portability"><div class="v11-heading"><div><span class="v11-kicker">Lượt 76 · Portability</span><h2>Bản đồ đường đi dữ liệu</h2></div><span class="pill">${rows.length} module</span></div><div class="v11-table">${rows.map((r)=>`<div><strong>${esc(r.label)}</strong><span>${r.records} bản ghi</span><span>${esc(r.mode)}</span><span>${esc(r.cloud)}</span></div>`).join('')}</div><div class="v11-note">${esc(PORTABILITY_NOTE)}</div></section>`;}
function workloadPanel(state){const rows=familyWorkloadWindows(state.settings?.familyPlanItems||[],today());return `<section class="card v11-panel" data-v11="workload"><div class="v11-heading"><div><span class="v11-kicker">Lượt 77 · Workload</span><h2>Cửa sổ tải kế hoạch gia đình</h2></div></div><div class="v11-window-grid">${rows.map((r)=>`<div><strong>${r.days} ngày</strong><span>${r.commitments} kế hoạch</span><span>${r.totalMinutes} phút</span><small>${r.activeDays} ngày có kế hoạch · TB ${r.averageMinutesPerActiveDay} phút/ngày hoạt động</small></div>`).join('')}</div><div class="v11-note">${esc(FAMILY_WORKLOAD_NOTE)}</div></section>`;}
function savedSearchPanel(state){const views=savedSearchViews(state.settings||{});return `<section class="card v11-panel" data-v11="saved-search"><div class="v11-heading"><div><span class="v11-kicker">Lượt 78 · Saved search</span><h2>Bộ lọc tìm kiếm đã lưu</h2></div><span class="pill">${views.length}/20</span></div><form id="v11SaveSearchForm" class="form"><label><span>Tên bộ lọc</span><input name="name" maxlength="80" required placeholder="Ví dụ: mục tiêu Toán tháng này"></label><button class="secondary" type="submit">Lưu điều kiện hiện tại</button></form>${views.length?`<div class="v11-list">${views.map((v)=>`<div><div><strong>${esc(v.name)}</strong><small>${esc(v.query||'Không có từ khóa')} · ${v.datasets.length?v.datasets.map(esc).join(', '):'mọi dataset an toàn'}</small></div><div class="actions"><button type="button" class="secondary" data-v11-load-search="${esc(v.id)}">Nạp</button><button type="button" class="secondary" data-v11-delete-search="${esc(v.id)}">Xóa</button></div></div>`).join('')}</div>`:'<div class="empty">Chưa lưu bộ lọc nào.</div>'}<div class="v11-note">${esc(SAVED_SEARCH_NOTE)}</div></section>`;}
function recoverySchedulePanel(state){const s=recoverySchedule(state.settings||{});return `<section class="card v11-panel" data-v11="recovery-schedule"><div class="v11-heading"><div><span class="v11-kicker">Lượt 79 · Recovery schedule</span><h2>Lịch recovery drill</h2></div><span class="pill">${s.enabled?'Đang bật':'Đang tắt'}</span></div><form id="v11RecoveryScheduleForm" class="form"><label><input type="checkbox" name="enabled" ${s.enabled?'checked':''}> Bật lịch kiểm tra</label><div class="form-row"><label><span>Chu kỳ</span><select name="cadence"><option value="monthly" ${s.cadence==='monthly'?'selected':''}>Hàng tháng</option><option value="quarterly" ${s.cadence==='quarterly'?'selected':''}>Hàng quý</option><option value="semiannual" ${s.cadence==='semiannual'?'selected':''}>6 tháng</option><option value="annual" ${s.cadence==='annual'?'selected':''}>Hàng năm</option></select></label><label><span>Ngày kiểm tra kế tiếp</span><input type="date" name="nextDate" value="${esc(s.nextDate)}"></label></div><label><input type="checkbox" name="reminderEnabled" ${s.reminderEnabled?'checked':''}> Tạo ứng viên nhắc cục bộ</label><fieldset><legend>Checklist</legend><label><input type="checkbox" name="backupExists" ${s.checklist.backupExists?'checked':''}> Có file backup</label><label><input type="checkbox" name="passphraseAvailable" ${s.checklist.passphraseAvailable?'checked':''}> Người dùng xác nhận có passphrase</label><label><input type="checkbox" name="dryRunReviewed" ${s.checklist.dryRunReviewed?'checked':''}> Đã xem quy trình dry-run</label></fieldset><button class="primary" type="submit">Lưu lịch kiểm tra</button></form>${recoveryReminderCandidate(state.settings||{})?`<div class="v11-reminder">Nhắc cục bộ đề xuất: ${esc(recoveryReminderCandidate(state.settings||{}).date)} · ${esc(recoveryReminderCandidate(state.settings||{}).title)}</div>`:''}<div class="v11-note">${esc(RECOVERY_SCHEDULE_NOTE)}</div></section>`;}
function compatibilityPanel(){const snap=compatibilityUsageSnapshot(document);const inactive=retirementCandidates(snap);return `<section class="card v11-panel" data-v11="compatibility"><div class="v11-heading"><div><span class="v11-kicker">Lượt 80 · Compatibility</span><h2>Quan sát module legacy</h2></div><span class="pill">${snap.filter((x)=>x.active).length}/${snap.length} đang có dấu hiệu hoạt động</span></div><div class="v11-list">${snap.map((x)=>`<div><strong>${esc(x.module)}</strong><span>${x.active?'active-observed':'not-observed-this-view'}</span></div>`).join('')}</div><div class="v11-note">${esc(RUNTIME_COMPATIBILITY_NOTE)} ${inactive.length?'Chưa xóa module nào trong v1.1; các module chưa quan sát ở màn hình hiện tại cần thêm regression evidence.':'Không có ứng viên retire ở snapshot hiện tại.'}</div></section>`;}
function addPanels(){const main=document.querySelector('.main'),title=document.querySelector('.topbar h1')?.textContent?.trim();if(!main||title!=='Tổng quan phát triển'||document.querySelector('[data-v11="portability"]'))return;const state=readState();main.insertAdjacentHTML('beforeend',`<div class="v11-grid">${portabilityPanel(state)}${workloadPanel(state)}${savedSearchPanel(state)}${recoverySchedulePanel(state)}${compatibilityPanel()}</div>`);}
function enhanceV11(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;addPanels();});}

document.addEventListener('submit',(event)=>{
  if(event.target.id==='v11SaveSearchForm'){
    event.preventDefault();const search=document.querySelector('#v9SearchForm');if(!search)return;const fd=new FormData(search),name=new FormData(event.target).get('name');const state=readState();state.settings=saveSearchView(state.settings||{},{name,query:String(fd.get('query')||''),childId:String(fd.get('childId')||''),datasets:fd.getAll('datasets'),domainId:String(fd.get('domainId')||''),fromDate:String(fd.get('fromDate')||''),toDate:String(fd.get('toDate')||''),limit:Number(fd.get('limit'))||20});saveAudit(state,'safe_search_view_saved',{name:String(name||'').slice(0,80)});location.reload();return;
  }
  if(event.target.id==='v11RecoveryScheduleForm'){
    event.preventDefault();const fd=new FormData(event.target),state=readState();state.settings=setRecoverySchedule(state.settings||{},{enabled:fd.has('enabled'),cadence:fd.get('cadence'),nextDate:fd.get('nextDate'),reminderEnabled:fd.has('reminderEnabled'),checklist:{backupExists:fd.has('backupExists'),passphraseAvailable:fd.has('passphraseAvailable'),dryRunReviewed:fd.has('dryRunReviewed')}});saveAudit(state,'recovery_schedule_saved',{enabled:fd.has('enabled'),cadence:String(fd.get('cadence')||'')});location.reload();
  }
},true);
document.addEventListener('click',(event)=>{
  const load=event.target.closest('[data-v11-load-search]'),del=event.target.closest('[data-v11-delete-search]');if(!load&&!del)return;const state=readState();
  if(del){state.settings=removeSearchView(state.settings||{},del.dataset.v11DeleteSearch);saveAudit(state,'safe_search_view_removed',{});location.reload();return;}
  const view=savedSearchViews(state.settings||{}).find((v)=>v.id===load.dataset.v11LoadSearch),form=document.querySelector('#v9SearchForm');if(!view||!form)return;form.querySelector('[name="query"]').value=view.query;form.querySelector('[name="childId"]').value=view.childId;form.querySelector('[name="limit"]').value=String(view.limit);for(const box of form.querySelectorAll('[name="datasets"]'))box.checked=view.datasets.length?view.datasets.includes(box.value):true;const domain=form.querySelector('[name="domainId"]'),from=form.querySelector('[name="fromDate"]'),to=form.querySelector('[name="toDate"]');if(domain)domain.value=view.domainId;if(from)from.value=view.fromDate;if(to)to.value=view.toDate;form.scrollIntoView({block:'center'});form.querySelector('[name="query"]').focus();
});
observer.observe(document.querySelector('#app'),{childList:true,subtree:true});enhanceV11();
