import { migrateState } from './core/schema.js';
import { saveState, appendAudit } from './core/store.js';
import { buildReceiptHistoryVerificationReceiptIntegrityPackage, reviewReceiptHistoryVerificationReceiptIntegrityPackage, RECEIPT_HISTORY_VERIFICATION_RECEIPT_PACKAGE_INTEGRITY_NOTE } from './core/receipt-history-verification-receipt-package-integrity.js';
import { buildWorkloadPresetImportAuditReviewIntegrityPackage, reviewWorkloadPresetImportAuditReviewIntegrityPackage, WORKLOAD_PRESET_IMPORT_AUDIT_REVIEW_PACKAGE_INTEGRITY_NOTE } from './core/workload-preset-import-audit-review-package-integrity.js';
import { verifySavedSearchReceiptHistoryPackageAndRecord, savedSearchReceiptHistoryPackageVerificationReceipts, filterSavedSearchReceiptHistoryPackageVerificationReceipts, buildSavedSearchReceiptHistoryPackageVerificationReceiptPackage, clearSavedSearchReceiptHistoryPackageVerificationReceipts, SAVED_SEARCH_RECEIPT_HISTORY_PACKAGE_VERIFICATION_RECEIPTS_NOTE } from './core/saved-search-receipt-history-package-verification-receipts.js';
import { recoveryVerificationReceiptPackageVerificationReceipts } from './core/recovery-reconciliation-verification-receipt-package-integrity.js';
import { filterRecoveryVerificationPackageReceipts, buildRecoveryVerificationPackageReceiptManagementPackage, clearRecoveryVerificationPackageReceipts, RECOVERY_VERIFICATION_PACKAGE_RECEIPT_MANAGEMENT_NOTE } from './core/recovery-verification-package-receipt-management.js';
import { compatibilityAxeRecheckRequests } from './core/compatibility-evidence-freshness-review-package.js';
import { filterCompatibilityAxeRecheckRequests, clearCompatibilityAxeRecheckRequests, buildCompatibilityAxeRecheckFreshnessEvidencePackage, verifyCompatibilityAxeRecheckFreshnessEvidencePackage, COMPATIBILITY_AXE_RECHECK_MANAGEMENT_NOTE } from './core/compatibility-axe-recheck-management.js';

const STORAGE_KEY='growup_mychildren_v1';
let scheduled=false;
const observer=new MutationObserver(()=>queueMicrotask(enhanceV110));
function readState(){try{return migrateState(JSON.parse(localStorage.getItem(STORAGE_KEY)||'{"version":5,"children":[]}'));}catch{return migrateState({version:5,children:[]});}}
function auditedSave(state,type,details={}){saveState(appendAudit(state,type,details));}
function esc(value=''){return String(value).replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function activePage(){return document.querySelector('.nav [data-nav].active')?.dataset.nav||document.querySelector('#mobileNav')?.value||'';}
function downloadJson(name,payload){const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0);}
function retireForm(selector,statusSelector,message){const form=document.querySelector(selector),status=document.querySelector(statusSelector);if(form){form.hidden=true;form.setAttribute('aria-hidden','true');form.style.setProperty('display','none','important');form.querySelectorAll('input,select,textarea,button,fieldset').forEach((control)=>{control.disabled=true;control.setAttribute('tabindex','-1');});}if(status&&status.textContent!==message)status.textContent=message;}
function retireButton(selector,message){const button=document.querySelector(selector);if(!button)return;button.hidden=true;button.disabled=true;button.setAttribute('aria-hidden','true');button.setAttribute('tabindex','-1');button.style.setProperty('display','none','important');button.title=message;}
function last(items=[]){return items.length?items[items.length-1]:null;}
function filterFields(prefix,label='Format chính xác'){return `<label><span>Kết quả</span><select name="result"><option value="all">Tất cả</option><option value="valid">Hợp lệ</option><option value="invalid">Không hợp lệ</option></select></label><label><span>${label}</span><input name="format" maxlength="80" placeholder="Để trống = tất cả"></label>`;}

function receiptIntegrityPanel(){return `<section class="card v16-panel" data-v110="receipt-verification-integrity"><div class="v16-heading"><div><span class="v16-kicker">Lượt 121 · Verification receipt integrity</span><h2>Signed receipt package</h2></div><span class="pill">SHA-256</span></div><form id="v110ReceiptIntegrityExportForm" class="form">${filterFields('receipt')}<button class="secondary" type="submit">Xuất package SHA-256</button></form><form id="v110VerifyReceiptIntegrityForm" class="form"><label><span>Signed package cần verify</span><input name="file" type="file" accept="application/json,.json" required></label><button class="secondary" type="submit">Xác minh read-only</button></form><div id="v110ReceiptIntegrityStatus" class="v16-status">Không khôi phục source history.</div><div class="v16-note">${esc(RECEIPT_HISTORY_VERIFICATION_RECEIPT_PACKAGE_INTEGRITY_NOTE)}</div></section>`;}

function presetAuditPackagePanel(){return `<section class="card v16-panel" data-v110="preset-audit-package"><div class="v16-heading"><div><span class="v16-kicker">Lượt 122 · Preset audit portability</span><h2>Neutral review package</h2></div><span class="pill">read-only</span></div><form id="v110PresetAuditExportForm" class="form"><label><span>Strategy</span><select name="strategy"><option value="all">Tất cả</option><option value="skip">Skip</option><option value="rename">Rename</option></select></label><label><span>Status</span><select name="status"><option value="all">Tất cả</option><option value="accepted">Accepted</option><option value="resolved">Resolved</option><option value="conflict-skip">Conflict skip</option><option value="rejected">Rejected</option></select></label><label><input name="conflictOnly" type="checkbox"> Chỉ conflict</label><button class="secondary" type="submit">Xuất review SHA-256</button></form><form id="v110VerifyPresetAuditPackageForm" class="form"><label><span>Review package</span><input name="file" type="file" accept="application/json,.json" required></label><button class="secondary" type="submit">Xác minh read-only</button></form><div id="v110PresetAuditPackageStatus" class="v16-status">Không apply preset.</div><div class="v16-note">${esc(WORKLOAD_PRESET_IMPORT_AUDIT_REVIEW_PACKAGE_INTEGRITY_NOTE)}</div></section>`;}

function savedSearchVerificationPanel(state){const receipts=savedSearchReceiptHistoryPackageVerificationReceipts(state.settings||{}),latest=last(receipts);return `<section class="card v16-panel" data-v110="saved-search-history-verification"><div class="v16-heading"><div><span class="v16-kicker">Lượt 123 · Saved Search history verification</span><h2>Verify · receipt · manage</h2></div><span class="pill">${receipts.length}/50</span></div><form id="v110VerifySavedSearchHistoryForm" class="form"><label><span>Signed history package</span><input name="file" type="file" accept="application/json,.json" required></label><button class="primary" type="submit">Xác minh & ghi receipt</button></form><form id="v110SavedSearchVerificationFilter" class="form">${filterFields('saved')}<div class="v16-actions"><button class="secondary" type="submit">Lọc</button><button class="secondary" id="v110ExportSavedSearchVerificationReceipts" type="button">Xuất receipt metadata</button><button class="danger" id="v110ClearSavedSearchVerificationReceipts" type="button">Xóa phần đang lọc</button></div></form><div id="v110SavedSearchVerificationStatus" class="v16-status">${latest?`Gần nhất: ${esc(latest.at)} · ${latest.result} · ${latest.importCount} import / ${latest.receiptCount} receipt.`:'Chưa có verification receipt.'}</div><div class="v16-note">${esc(SAVED_SEARCH_RECEIPT_HISTORY_PACKAGE_VERIFICATION_RECEIPTS_NOTE)}</div></section>`;}

function recoveryManagementPanel(state){const receipts=recoveryVerificationReceiptPackageVerificationReceipts(state.settings||{}),latest=last(receipts);return `<section class="card v16-panel" data-v110="recovery-verification-management"><div class="v16-heading"><div><span class="v16-kicker">Lượt 124 · Recovery verification receipt management</span><h2>Filter · export · clear</h2></div><span class="pill">${receipts.length}/50</span></div><form id="v110RecoveryVerificationFilter" class="form">${filterFields('recovery')}<div class="v16-actions"><button class="secondary" type="submit">Lọc</button><button class="secondary" id="v110ExportRecoveryVerificationReceipts" type="button">Xuất receipt metadata</button><button class="danger" id="v110ClearRecoveryVerificationReceipts" type="button">Xóa phần đang lọc</button></div></form><div id="v110RecoveryVerificationStatus" class="v16-status">${latest?`Gần nhất: ${esc(latest.at)} · ${latest.result} · ${latest.receiptCount} receipt.`:'Chưa có verification receipt.'}</div><div class="v16-note">${esc(RECOVERY_VERIFICATION_PACKAGE_RECEIPT_MANAGEMENT_NOTE)}</div></section>`;}

function axeManagementPanel(state){const requests=compatibilityAxeRecheckRequests(state.settings||{}),pending=requests.filter((item)=>item.status==='pending').length,passed=requests.filter((item)=>item.status==='passed').length;return `<section class="card v16-panel" data-v110="axe-recheck-management"><div class="v16-heading"><div><span class="v16-kicker">Lượt 125 · Axe recheck history</span><h2>Manage + freshness evidence</h2></div><span class="pill">${pending} pending · ${passed} passed</span></div><form id="v110AxeManagementFilter" class="form"><label><span>Trạng thái</span><select name="status"><option value="all">Tất cả</option><option value="pending">Pending</option><option value="passed">Passed actual Axe</option></select></label><label><span>Module chính xác</span><input name="module" maxlength="80" placeholder="Để trống = tất cả"></label><div class="v16-actions"><button class="secondary" type="submit">Lọc</button><button class="secondary" id="v110ExportAxeFreshnessEvidence" type="button">Xuất evidence SHA-256</button><button class="danger" id="v110ClearAxeRequests" type="button">Xóa request metadata</button></div></form><form id="v110VerifyAxeFreshnessEvidenceForm" class="form"><label><span>Evidence package</span><input name="file" type="file" accept="application/json,.json" required></label><button class="secondary" type="submit">Xác minh read-only</button></form><div id="v110AxeManagementStatus" class="v16-status">Không có manual PASS · retirementAllowed=false · actionsApplied=false.</div><div class="v16-note">${esc(COMPATIBILITY_AXE_RECHECK_MANAGEMENT_NOTE)}</div></section>`;}

function addPanels(){const main=document.querySelector('.main');if(!main||activePage()!=='overview'||document.querySelector('[data-v110="receipt-verification-integrity"]'))return;const state=readState();main.insertAdjacentHTML('beforeend',`<div class="v16-grid" data-v110-grid>${receiptIntegrityPanel()}${presetAuditPackagePanel()}${savedSearchVerificationPanel(state)}${recoveryManagementPanel(state)}${axeManagementPanel(state)}</div>`);}
function enhanceV110(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;retireButton('#v19ExportReceiptVerificationReceipts','Unsigned L116 export đã chuyển sang L121 SHA-256.');retireForm('#v19VerifySavedSearchHistoryForm','#v19SavedSearchHistoryStatus','Verification đã chuyển sang Lượt 123 để luôn ghi bounded verification receipt.');addPanels();});}
function resultFormatCriteria(form){const data=new FormData(form);return {result:String(data.get('result')||'all'),format:String(data.get('format')||'')};}
function presetCriteria(form){const data=new FormData(form);return {strategy:String(data.get('strategy')||'all'),status:String(data.get('status')||'all'),conflictOnly:data.get('conflictOnly')==='on'};}
function axeCriteria(){const form=document.querySelector('#v110AxeManagementFilter');if(!form)return {};const data=new FormData(form);return {status:String(data.get('status')||'all'),module:String(data.get('module')||'')};}

addEventListener('submit',async(event)=>{
  if(event.target.id==='v110ReceiptIntegrityExportForm'){event.preventDefault();downloadJson('growup-receipt-history-verification-receipts-sha256.json',buildReceiptHistoryVerificationReceiptIntegrityPackage(readState().settings||{},resultFormatCriteria(event.target)));return;}
  if(event.target.id==='v110VerifyReceiptIntegrityForm'){event.preventDefault();const file=new FormData(event.target).get('file');try{const review=reviewReceiptHistoryVerificationReceiptIntegrityPackage(JSON.parse(await file.text()));document.querySelector('#v110ReceiptIntegrityStatus').textContent=review.valid?`HỢP LỆ · ${review.receiptCount} receipt · readOnly=true.`:'KHÔNG HỢP LỆ · không apply state.';}catch{document.querySelector('#v110ReceiptIntegrityStatus').textContent='JSON không hợp lệ.';}return;}
  if(event.target.id==='v110PresetAuditExportForm'){event.preventDefault();downloadJson('growup-workload-preset-audit-review-sha256.json',buildWorkloadPresetImportAuditReviewIntegrityPackage(readState().settings||{},presetCriteria(event.target)));return;}
  if(event.target.id==='v110VerifyPresetAuditPackageForm'){event.preventDefault();const file=new FormData(event.target).get('file');try{const review=reviewWorkloadPresetImportAuditReviewIntegrityPackage(JSON.parse(await file.text()));document.querySelector('#v110PresetAuditPackageStatus').textContent=review.valid?`HỢP LỆ · ${review.summary.auditCount} audit · ${review.summary.decisionCount} quyết định · readOnly=true.`:'KHÔNG HỢP LỆ · không apply preset.';}catch{document.querySelector('#v110PresetAuditPackageStatus').textContent='JSON không hợp lệ.';}return;}
  if(event.target.id==='v110VerifySavedSearchHistoryForm'){event.preventDefault();const file=new FormData(event.target).get('file');try{const pkg=JSON.parse(await file.text()),state=readState(),result=verifySavedSearchReceiptHistoryPackageAndRecord(state.settings||{},pkg);state.settings=result.settings;auditedSave(state,'saved_search_receipt_history_package_verified',{result:result.receipt.result,importCount:result.receipt.importCount,receiptCount:result.receipt.receiptCount});location.reload();}catch{document.querySelector('#v110SavedSearchVerificationStatus').textContent='JSON không hợp lệ; không ghi receipt.';}return;}
  if(event.target.id==='v110SavedSearchVerificationFilter'){event.preventDefault();const count=filterSavedSearchReceiptHistoryPackageVerificationReceipts(readState().settings||{},resultFormatCriteria(event.target)).length;document.querySelector('#v110SavedSearchVerificationStatus').textContent=`Bộ lọc hiện có ${count} verification receipt.`;return;}
  if(event.target.id==='v110RecoveryVerificationFilter'){event.preventDefault();const count=filterRecoveryVerificationPackageReceipts(readState().settings||{},resultFormatCriteria(event.target)).length;document.querySelector('#v110RecoveryVerificationStatus').textContent=`Bộ lọc hiện có ${count} verification receipt.`;return;}
  if(event.target.id==='v110AxeManagementFilter'){event.preventDefault();const count=filterCompatibilityAxeRecheckRequests(readState().settings||{},axeCriteria()).length;document.querySelector('#v110AxeManagementStatus').textContent=`Bộ lọc hiện có ${count} request · không có manual PASS.`;return;}
  if(event.target.id==='v110VerifyAxeFreshnessEvidenceForm'){event.preventDefault();const file=new FormData(event.target).get('file');try{const verification=verifyCompatibilityAxeRecheckFreshnessEvidencePackage(JSON.parse(await file.text()));document.querySelector('#v110AxeManagementStatus').textContent=verification.valid?`HỢP LỆ · ${verification.requestCount} request · retirementAllowed=false · actionsApplied=false.`:'KHÔNG HỢP LỆ · không apply state.';}catch{document.querySelector('#v110AxeManagementStatus').textContent='JSON không hợp lệ.';}return;}
});

addEventListener('click',(event)=>{
  if(event.target.id==='v110ExportSavedSearchVerificationReceipts'){downloadJson('growup-saved-search-history-verification-receipts.json',buildSavedSearchReceiptHistoryPackageVerificationReceiptPackage(readState().settings||{},resultFormatCriteria(document.querySelector('#v110SavedSearchVerificationFilter'))));return;}
  if(event.target.id==='v110ClearSavedSearchVerificationReceipts'){if(!confirm('Xóa verification receipt Saved Search đang lọc? History nguồn không bị thay đổi.'))return;const state=readState(),result=clearSavedSearchReceiptHistoryPackageVerificationReceipts(state.settings||{},resultFormatCriteria(document.querySelector('#v110SavedSearchVerificationFilter')),true);if(result.changed){state.settings=result.settings;auditedSave(state,'saved_search_receipt_history_verification_receipts_cleared',{removed:result.removed});location.reload();}return;}
  if(event.target.id==='v110ExportRecoveryVerificationReceipts'){downloadJson('growup-recovery-package-verification-receipts.json',buildRecoveryVerificationPackageReceiptManagementPackage(readState().settings||{},resultFormatCriteria(document.querySelector('#v110RecoveryVerificationFilter'))));return;}
  if(event.target.id==='v110ClearRecoveryVerificationReceipts'){if(!confirm('Xóa Recovery package verification receipt đang lọc? Report/reminder/calendar không bị thay đổi.'))return;const state=readState(),result=clearRecoveryVerificationPackageReceipts(state.settings||{},resultFormatCriteria(document.querySelector('#v110RecoveryVerificationFilter')),true);if(result.changed){state.settings=result.settings;auditedSave(state,'recovery_package_verification_receipts_cleared',{removed:result.removed});location.reload();}return;}
  if(event.target.id==='v110ExportAxeFreshnessEvidence'){downloadJson('growup-axe-recheck-freshness-evidence-sha256.json',buildCompatibilityAxeRecheckFreshnessEvidencePackage(readState().settings||{},axeCriteria()));return;}
  if(event.target.id==='v110ClearAxeRequests'){if(!confirm('Xóa request/history Axe đang lọc? Compatibility evidence đã ghi từ actual Axe PASS sẽ được giữ nguyên.'))return;const state=readState(),result=clearCompatibilityAxeRecheckRequests(state.settings||{},axeCriteria(),true);if(result.changed){state.settings=result.settings;auditedSave(state,'compatibility_axe_recheck_requests_cleared',{removed:result.removed});location.reload();}return;}
});

document.addEventListener('growup:page-change',enhanceV110);
observer.observe(document.documentElement,{childList:true,subtree:true});
enhanceV110();
