import { migrateState } from './core/schema.js';
import { saveState, appendAudit } from './core/store.js';
import { verifySafeExportIntegrity, EXPORT_INTEGRITY_NOTE } from './core/export-integrity.js';
import { workloadBandSettings, setWorkloadBandSettings, WORKLOAD_BAND_SETTINGS_NOTE } from './core/workload-band-settings.js';
import { familyWorkloadCalendar } from './core/workload-calendar.js';
import { savedSearchViews } from './core/saved-search.js';
import { duplicateSavedSearchIds, pinSavedSearch, moveSavedSearchToFolder, SAVED_SEARCH_ORGANIZER_NOTE } from './core/saved-search-organizer.js';
import { completeRecoveryReminder, rescheduleRecoveryReminder, removeRecoveryReminder, recoveryReminderLifecycleHistory, RECOVERY_LIFECYCLE_NOTE } from './core/recovery-reminder-lifecycle.js';
import { legacyModuleDefinitions, compatibilityUsageSnapshot } from './core/runtime-compatibility.js';
import { firstLegacyRetirementReview, RETIREMENT_REVIEW_NOTE } from './core/retirement-review.js';

const STORAGE_KEY='growup_mychildren_v1';
let scheduled=false;
const observer=new MutationObserver(()=>queueMicrotask(enhanceV13));
function readState(){try{return migrateState(JSON.parse(localStorage.getItem(STORAGE_KEY)||'{"version":5,"children":[]}'));}catch{return migrateState({version:5,children:[]});}}
function esc(value=''){return String(value).replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function auditedSave(state,type,details={}){saveState(appendAudit(state,type,details));}

function integrityPanel(){return `<section class="card v13-panel" data-v13="export-integrity"><div class="v13-heading"><div><span class="v13-kicker">Lượt 86 · Integrity</span><h2>Kiểm tra checksum gói safe export</h2></div><span class="pill">SHA-256</span></div><form id="v13VerifyExportForm" class="form"><label><span>Gói JSON nhận được</span><input name="file" type="file" accept="application/json,.json" required></label><button class="primary" type="submit">Kiểm tra toàn vẹn</button></form><div id="v13IntegrityResult" class="v13-status">Các gói safe export v1.3 có manifest SHA-256 ngay trong file.</div><div class="v13-note">${esc(EXPORT_INTEGRITY_NOTE)}</div></section>`;}

function workloadPanel(state){const config=workloadBandSettings(state.settings||{});return `<section class="card v13-panel" data-v13="workload-bands"><div class="v13-heading"><div><span class="v13-kicker">Lượt 87 · Workload bands</span><h2>Tùy chỉnh dải phút hiển thị</h2></div><span class="pill">Local only</span></div><form id="v13WorkloadBandsForm" class="form"><div class="form-row"><label><span>Ngưỡng dải 1 (phút)</span><input name="firstMax" type="number" min="1" max="720" value="${config.firstMax}" required></label><label><span>Ngưỡng dải 2 (phút)</span><input name="secondMax" type="number" min="2" max="1440" value="${config.secondMax}" required></label></div>${['none','light','moderate','extended'].map((key)=>`<label><span>Nhãn ${key}</span><input name="label-${key}" maxlength="60" value="${esc(config.labels[key])}" required></label>`).join('')}<button class="primary" type="submit">Lưu dải hiển thị</button></form><div class="v13-note">${esc(WORKLOAD_BAND_SETTINGS_NOTE)}</div></section>`;}

function savedSearchPanel(state){const views=savedSearchViews(state.settings||{}),duplicates=duplicateSavedSearchIds(state.settings||{});return `<section class="card v13-panel" data-v13="saved-search-organizer"><div class="v13-heading"><div><span class="v13-kicker">Lượt 88 · Search organizer</span><h2>Folder, ghim và phát hiện trùng</h2></div><span class="pill">${duplicates.length} nhóm trùng</span></div>${views.length?`<div class="v13-list">${views.map((view)=>`<div class="v13-search-row"><div><strong>${esc(view.name)}</strong><small>${view.pinned?'Đã ghim · ':''}${view.folder?`Folder: ${esc(view.folder)}`:'Chưa có folder'}</small></div><div class="v13-actions"><button class="secondary" type="button" data-v13-pin-search="${esc(view.id)}" data-pinned="${view.pinned?'0':'1'}">${view.pinned?'Bỏ ghim':'Ghim'}</button><form data-v13-folder-search="${esc(view.id)}"><input name="folder" maxlength="60" value="${esc(view.folder||'')}" placeholder="Tên folder"><button class="secondary" type="submit">Lưu folder</button></form></div></div>`).join('')}</div>`:'<div class="empty">Chưa có bộ lọc đã lưu.</div>'}${duplicates.length?`<div class="v13-status">Criteria trùng: ${duplicates.map((ids)=>ids.map(esc).join(' ↔ ')).join('; ')}</div>`:''}<div class="v13-note">${esc(SAVED_SEARCH_ORGANIZER_NOTE)}</div></section>`;}

function recoveryPanel(state){const child=state.children.find((item)=>item.id===state.selectedChildId)||state.children[0],reminders=(child?.reminders||[]).filter((item)=>item.source==='recovery-drill'&&item.type==='recovery'),history=recoveryReminderLifecycleHistory(state.settings||{});return `<section class="card v13-panel" data-v13="recovery-lifecycle"><div class="v13-heading"><div><span class="v13-kicker">Lượt 89 · Recovery lifecycle</span><h2>Vòng đời nhắc recovery</h2></div><span class="pill">${reminders.length} nhắc</span></div>${child&&reminders.length?`<div class="v13-list">${reminders.map((reminder)=>`<div class="v13-recovery-row"><div><strong>${esc(reminder.title)}</strong><small>${esc(reminder.date)} · ${reminder.completed?'Đã hoàn thành':'Chưa hoàn thành'} · gốc ${esc(reminder.lineage?.originDate||reminder.date)}</small></div><div class="v13-actions"><button class="secondary" type="button" data-v13-complete-recovery="${esc(reminder.id)}" data-completed="${reminder.completed?'0':'1'}">${reminder.completed?'Mở lại':'Hoàn thành'}</button><form data-v13-reschedule-recovery="${esc(reminder.id)}"><input name="date" type="date" value="${esc(reminder.date)}" required><button class="secondary" type="submit">Đổi ngày</button></form><button class="secondary" type="button" data-v13-remove-recovery="${esc(reminder.id)}">Xóa</button></div></div>`).join('')}</div>`:'<div class="empty">Chưa có recovery reminder cho hồ sơ hiện tại.</div>'}<div class="v13-status">Lifecycle history metadata: ${history.length} mục.</div><div class="v13-note">${esc(RECOVERY_LIFECYCLE_NOTE)}</div></section>`;}

function retirementPanel(){return `<section class="card v13-panel" data-v13="retirement-review"><div class="v13-heading"><div><span class="v13-kicker">Lượt 90 · Retirement review</span><h2>Review ứng viên legacy đầu tiên</h2></div><span class="pill">Không auto-remove</span></div><div id="v13RetirementResult" class="v13-list"><div>Đang đối chiếu dependency graph runtime…</div></div><div class="v13-note">${esc(RETIREMENT_REVIEW_NOTE)}</div></section>`;}

function renderConfiguredCalendar(state=readState(),force=false){const target=document.querySelector('#v12WorkloadCalendar'),month=document.querySelector('#v12WorkloadMonth')?.value;if(!target||!month)return;const config=workloadBandSettings(state.settings||{}),signature=JSON.stringify({month,config});if(!force&&target.dataset.v13BandSignature===signature)return;const calendar=familyWorkloadCalendar(state.settings?.familyPlanItems||[],`${month}-01`,config);target.innerHTML=`<div class="v12-heatmap" aria-hidden="true">${calendar.days.map((day)=>`<span class="v12-heat ${day.band}" title="${esc(day.text)}">${day.day}</span>`).join('')}</div><details class="v12-text-equivalent"><summary>Mô tả văn bản ${esc(calendar.monthLabel)}</summary><ul>${calendar.days.map((day)=>`<li tabindex="0">${esc(day.text)}</li>`).join('')}</ul></details>`;target.dataset.v13BandSignature=signature;}

async function renderRetirementReview(){const target=document.querySelector('#v13RetirementResult');if(!target)return;try{const source=await fetch('./src/runtime-entry.js',{cache:'no-store'}).then((response)=>response.text());const overview=compatibilityUsageSnapshot(document).map((item)=>({module:item.module,flow:'overview',observed:true,active:item.active}));const review=firstLegacyRetirementReview({evidenceRecords:overview,runtimeEntrySource:source,definitions:legacyModuleDefinitions()});target.innerHTML=review.rows.map((row)=>`<div><strong>${esc(row.module)}</strong><span>${row.runtimeReferenced?'runtime còn import':'không import'} · ${row.evidenceComplete?'đủ 6 flow':'chưa đủ 6 flow'} · ${row.decision}</span></div>`).join('');}catch{target.innerHTML='<div>Không đọc được dependency graph; giữ toàn bộ legacy module.</div>';}}

function addPanels(){const main=document.querySelector('.main'),title=document.querySelector('.topbar h1')?.textContent?.trim();if(!main||title!=='Tổng quan phát triển'||document.querySelector('[data-v13="export-integrity"]'))return;const state=readState();main.insertAdjacentHTML('beforeend',`<div class="v13-grid">${integrityPanel()}${workloadPanel(state)}${savedSearchPanel(state)}${recoveryPanel(state)}${retirementPanel()}</div>`);renderConfiguredCalendar(state,true);renderRetirementReview();}
function enhanceV13(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;addPanels();});}

document.addEventListener('submit',async(event)=>{
  if(event.target.id==='v13VerifyExportForm'){event.preventDefault();const file=new FormData(event.target).get('file'),target=document.querySelector('#v13IntegrityResult');try{const parsed=JSON.parse(await file.text()),result=verifySafeExportIntegrity(parsed);target.textContent=result.valid?`Checksum hợp lệ · ${result.actual}`:`Checksum KHÔNG hợp lệ · expected ${result.expected||'—'} · actual ${result.actual}`;}catch{target.textContent='Không thể kiểm tra: file JSON không hợp lệ.';}return;}
  if(event.target.id==='v13WorkloadBandsForm'){event.preventDefault();const fd=new FormData(event.target),state=readState();state.settings=setWorkloadBandSettings(state.settings||{},{firstMax:fd.get('firstMax'),secondMax:fd.get('secondMax'),labels:{none:fd.get('label-none'),light:fd.get('label-light'),moderate:fd.get('label-moderate'),extended:fd.get('label-extended')}});auditedSave(state,'workload_display_bands_saved',{});location.reload();return;}
  const folder=event.target.closest('[data-v13-folder-search]');if(folder){event.preventDefault();const state=readState(),id=folder.dataset.v13FolderSearch,name=new FormData(folder).get('folder');state.settings=moveSavedSearchToFolder(state.settings||{},id,name);auditedSave(state,'safe_search_folder_saved',{id});location.reload();return;}
  const reschedule=event.target.closest('[data-v13-reschedule-recovery]');if(reschedule){event.preventDefault();const state=readState(),child=state.children.find((item)=>item.id===state.selectedChildId)||state.children[0],result=rescheduleRecoveryReminder(state,child?.id||'',reschedule.dataset.v13RescheduleRecovery,new FormData(reschedule).get('date'));if(result.changed){auditedSave(result.state,'recovery_reminder_rescheduled',{reminderId:reschedule.dataset.v13RescheduleRecovery});location.reload();}else alert(result.reason||'Không thể đổi ngày.');}
},true);

document.addEventListener('click',(event)=>{
  const pin=event.target.closest('[data-v13-pin-search]');if(pin){const state=readState();state.settings=pinSavedSearch(state.settings||{},pin.dataset.v13PinSearch,pin.dataset.pinned==='1');auditedSave(state,'safe_search_pin_changed',{id:pin.dataset.v13PinSearch});location.reload();return;}
  const complete=event.target.closest('[data-v13-complete-recovery]');if(complete){const state=readState(),child=state.children.find((item)=>item.id===state.selectedChildId)||state.children[0],result=completeRecoveryReminder(state,child?.id||'',complete.dataset.v13CompleteRecovery,complete.dataset.completed==='1');if(result.changed){auditedSave(result.state,'recovery_reminder_completion_changed',{reminderId:complete.dataset.v13CompleteRecovery});location.reload();}return;}
  const remove=event.target.closest('[data-v13-remove-recovery]');if(remove){if(!confirm('Xóa recovery reminder này? Metadata lineage tối thiểu vẫn được giữ trong lifecycle history.'))return;const state=readState(),child=state.children.find((item)=>item.id===state.selectedChildId)||state.children[0],result=removeRecoveryReminder(state,child?.id||'',remove.dataset.v13RemoveRecovery);if(result.changed){auditedSave(result.state,'recovery_reminder_removed',{reminderId:remove.dataset.v13RemoveRecovery});location.reload();}return;}
});

document.addEventListener('change',(event)=>{if(event.target.id==='v12WorkloadMonth')queueMicrotask(()=>renderConfiguredCalendar(readState(),true));});
observer.observe(document.querySelector('#app'),{childList:true,subtree:true});enhanceV13();
