import { migrateState } from './core/schema.js';
import { saveState, appendAudit } from './core/store.js';
import { buildIntegrityExportVerificationReceiptPackage, previewExportVerificationReceiptImport, applyExportVerificationReceiptImport, EXPORT_VERIFICATION_RECEIPT_INTEGRITY_NOTE } from './core/export-verification-package-integrity.js';
import { buildIntegrityWorkloadPresetPackage, previewIntegrityWorkloadPresetImport, applyIntegrityWorkloadPresetImport, WORKLOAD_PRESET_INTEGRITY_NOTE } from './core/workload-preset-package-integrity.js';
import { filterSavedSearchIntegrityReceipts, savedSearchIntegrityReceiptFormats, buildSavedSearchIntegrityReceiptPackage, clearSavedSearchIntegrityReceipts, SAVED_SEARCH_RECEIPT_MANAGEMENT_NOTE } from './core/saved-search-integrity-receipt-management.js';
import { previewRecoveryIcsReconciliation } from './core/recovery-ics-reconciliation.js';
import { buildRecoveryReconciliationReport, RECOVERY_RECONCILIATION_REPORT_NOTE } from './core/recovery-reconciliation-report.js';
import { buildCompatibilityEvidencePackage, previewCompatibilityEvidenceImport, applyCompatibilityEvidenceImport, COMPATIBILITY_EVIDENCE_PACKAGE_NOTE } from './core/compatibility-evidence-package.js';

const STORAGE_KEY='growup_mychildren_v1';
let scheduled=false,pendingReceiptPackage=null,pendingPresetPackage=null,pendingEvidencePackage=null,pendingRecoveryPreview=null,savedReceiptFilter={};
const observer=new MutationObserver(()=>queueMicrotask(enhanceV16));
function readState(){try{return migrateState(JSON.parse(localStorage.getItem(STORAGE_KEY)||'{"version":5,"children":[]}'));}catch{return migrateState({version:5,children:[]});}}
function esc(value=''){return String(value).replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function auditedSave(state,type,details={}){saveState(appendAudit(state,type,details));}
function selectedChild(state){return state.children.find((item)=>item.id===state.selectedChildId)||state.children[0]||null;}
function activePage(){return document.querySelector('.nav [data-nav].active')?.dataset.nav||document.querySelector('#mobileNav')?.value||'';}
function downloadText(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0);}

function receiptIntegrityPanel(){return `<section class="card v16-panel" data-v16="receipt-integrity"><div class="v16-heading"><div><span class="v16-kicker">Lượt 101 · Receipt integrity</span><h2>Receipt package có checksum</h2></div><span class="pill">SHA-256</span></div><button class="secondary" type="button" id="v16ExportReceiptIntegrity">Xuất package receipt SHA-256</button><form id="v16ReceiptIntegrityImportForm" class="form"><label><span>Package receipt cần nhập</span><input name="file" type="file" accept="application/json,.json" required></label><div class="v16-actions"><button class="secondary" type="submit">Xác minh & preview</button><button class="primary" type="button" id="v16ApplyReceiptImport" disabled>Áp dụng import</button></div></form><div id="v16ReceiptIntegrityStatus" class="v16-status">Chưa xác minh package.</div><div class="v16-note">${esc(EXPORT_VERIFICATION_RECEIPT_INTEGRITY_NOTE)}</div></section>`;}

function presetIntegrityPanel(){return `<section class="card v16-panel" data-v16="preset-integrity"><div class="v16-heading"><div><span class="v16-kicker">Lượt 102 · Preset integrity</span><h2>Preset package + xử lý xung đột</h2></div><span class="pill">preview first</span></div><button class="secondary" type="button" id="v16ExportPresetIntegrity">Xuất preset package SHA-256</button><form id="v16PresetIntegrityImportForm" class="form"><label><span>Package preset</span><input name="file" type="file" accept="application/json,.json" required></label><label><span>Khi trùng tên/ID</span><select name="strategy"><option value="skip">Bỏ qua mục trùng</option><option value="rename">Tạo tên/ID mới</option></select></label><div class="v16-actions"><button class="secondary" type="submit">Xác minh & preview</button><button class="primary" type="button" id="v16ApplyPresetIntegrityImport" disabled>Áp dụng import</button></div></form><div id="v16PresetIntegrityStatus" class="v16-status">Chưa preview package.</div><div class="v16-note">${esc(WORKLOAD_PRESET_INTEGRITY_NOTE)}</div></section>`;}

function savedReceiptPanel(state){const settings=state.settings||{},items=filterSavedSearchIntegrityReceipts(settings,savedReceiptFilter),formats=savedSearchIntegrityReceiptFormats(settings);return `<section class="card v16-panel" data-v16="saved-search-receipts"><div class="v16-heading"><div><span class="v16-kicker">Lượt 103 · Saved Search receipts</span><h2>Quản lý receipt integrity</h2></div><span class="pill">${items.length} mục</span></div><form id="v16SavedReceiptFilterForm" class="form"><div class="form-row"><label><span>Kết quả</span><select name="result"><option value="">Tất cả</option><option value="valid" ${savedReceiptFilter.result==='valid'?'selected':''}>Hợp lệ</option><option value="invalid" ${savedReceiptFilter.result==='invalid'?'selected':''}>Không hợp lệ</option></select></label><label><span>Format</span><input name="format" value="${esc(savedReceiptFilter.format||'')}" list="v16SavedReceiptFormats"><datalist id="v16SavedReceiptFormats">${formats.map((item)=>`<option value="${esc(item)}"></option>`).join('')}</datalist></label></div><div class="form-row"><label><span>Từ ngày</span><input type="date" name="fromDate" value="${esc(savedReceiptFilter.fromDate||'')}"></label><label><span>Đến ngày</span><input type="date" name="toDate" value="${esc(savedReceiptFilter.toDate||'')}"></label></div><div class="v16-actions"><button class="secondary" type="submit">Lọc</button><button class="secondary" type="button" id="v16ExportSavedReceipts">Xuất receipt JSON</button><button class="danger" type="button" id="v16ClearSavedReceipts">Xóa lịch sử</button></div></form><div class="v16-list">${items.length?items.slice().reverse().slice(0,12).map((item)=>`<div><strong>${item.result==='valid'?'Hợp lệ':'Không hợp lệ'}</strong><span>${esc(item.at)} · ${esc(item.format)} · ${esc(item.algorithm)}</span></div>`).join(''):'<div class="empty">Không có receipt phù hợp.</div>'}</div><div class="v16-note">${esc(SAVED_SEARCH_RECEIPT_MANAGEMENT_NOTE)}</div></section>`;}

function recoveryReportPanel(state){const child=selectedChild(state);return `<section class="card v16-panel" data-v16="recovery-report"><div class="v16-heading"><div><span class="v16-kicker">Lượt 104 · Recovery report</span><h2>Xuất báo cáo reconciliation đã chọn</h2></div><span class="pill">metadata only</span></div>${child?`<form id="v16RecoveryReportPreviewForm" class="form"><label><span>File recovery .ics</span><input name="file" type="file" accept="text/calendar,.ics" required></label><button class="secondary" type="submit">Preview dòng so sánh</button></form>`:'<div class="empty">Cần có hồ sơ trẻ.</div>'}<form id="v16RecoveryReportExportForm" class="form"><div id="v16RecoveryReportRows" class="v16-checks"><div class="empty">Chưa có preview để chọn.</div></div><button class="primary" type="submit" disabled>Xuất report các dòng đã chọn</button></form><div id="v16RecoveryReportStatus" class="v16-status">Không áp dụng thay đổi lên reminder.</div><div class="v16-note">${esc(RECOVERY_RECONCILIATION_REPORT_NOTE)}</div></section>`;}

function evidencePackagePanel(){return `<section class="card v16-panel" data-v16="evidence-package"><div class="v16-heading"><div><span class="v16-kicker">Lượt 105 · Evidence package</span><h2>Compatibility evidence package</h2></div><span class="pill">6-flow metadata</span></div><button class="secondary" type="button" id="v16ExportEvidencePackage">Xuất evidence SHA-256</button><form id="v16EvidenceImportForm" class="form"><label><span>Evidence package cần nhập</span><input name="file" type="file" accept="application/json,.json" required></label><div class="v16-actions"><button class="secondary" type="submit">Xác minh & preview</button><button class="primary" type="button" id="v16ApplyEvidenceImport" disabled>Áp dụng import</button></div></form><div id="v16EvidenceStatus" class="v16-status">Chưa xác minh package.</div><div class="v16-note">${esc(COMPATIBILITY_EVIDENCE_PACKAGE_NOTE)}</div></section>`;}

function addPanels(){const main=document.querySelector('.main');if(!main||activePage()!=='overview'||document.querySelector('[data-v16="receipt-integrity"]'))return;const state=readState();main.insertAdjacentHTML('beforeend',`<div class="v16-grid">${receiptIntegrityPanel()}${presetIntegrityPanel()}${savedReceiptPanel(state)}${recoveryReportPanel(state)}${evidencePackagePanel()}</div>`);}
function refreshSavedReceiptPanel(){const panel=document.querySelector('[data-v16="saved-search-receipts"]');if(panel)panel.outerHTML=savedReceiptPanel(readState());}
function enhanceV16(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;addPanels();});}

document.addEventListener('submit',async(event)=>{
  if(event.target.id==='v16ReceiptIntegrityImportForm'){
    event.preventDefault();const file=new FormData(event.target).get('file'),status=document.querySelector('#v16ReceiptIntegrityStatus'),apply=document.querySelector('#v16ApplyReceiptImport');pendingReceiptPackage=null;apply.disabled=true;try{const pkg=JSON.parse(await file.text()),preview=previewExportVerificationReceiptImport(pkg,readState().settings||{});if(!preview.valid){status.textContent='Checksum/format không hợp lệ. Import bị khóa.';return;}pendingReceiptPackage=pkg;apply.disabled=false;status.textContent=`Checksum hợp lệ · ${preview.accepted.length} receipt có thể thêm · ${preview.duplicates} trùng · ${preview.rejected} bị loại.`;}catch{status.textContent='JSON không hợp lệ. Import bị khóa.';}return;
  }
  if(event.target.id==='v16PresetIntegrityImportForm'){
    event.preventDefault();const form=new FormData(event.target),file=form.get('file'),strategy=String(form.get('strategy')||'skip'),status=document.querySelector('#v16PresetIntegrityStatus'),apply=document.querySelector('#v16ApplyPresetIntegrityImport');pendingPresetPackage=null;apply.disabled=true;try{const pkg=JSON.parse(await file.text()),preview=previewIntegrityWorkloadPresetImport(pkg,readState().settings||{},{conflictStrategy:strategy});if(!preview.valid){status.textContent='Checksum/format không hợp lệ. Import bị khóa.';return;}pendingPresetPackage={pkg,strategy};apply.disabled=false;status.textContent=`Preview: ${preview.accepted} có thể thêm · ${preview.conflicts} xung đột · ${preview.rejected} bị từ chối · chiến lược ${preview.strategy}.`;}catch{status.textContent='JSON không hợp lệ. Import bị khóa.';}return;
  }
  if(event.target.id==='v16SavedReceiptFilterForm'){
    event.preventDefault();const form=new FormData(event.target);savedReceiptFilter={result:String(form.get('result')||''),format:String(form.get('format')||''),fromDate:String(form.get('fromDate')||''),toDate:String(form.get('toDate')||'')};refreshSavedReceiptPanel();return;
  }
  if(event.target.id==='v16RecoveryReportPreviewForm'){
    event.preventDefault();const state=readState(),child=selectedChild(state),file=new FormData(event.target).get('file'),rows=document.querySelector('#v16RecoveryReportRows'),button=document.querySelector('#v16RecoveryReportExportForm button[type="submit"]'),status=document.querySelector('#v16RecoveryReportStatus');pendingRecoveryPreview=null;button.disabled=true;if(!child||!(file instanceof File)){status.textContent='Thiếu hồ sơ hoặc file .ics.';return;}const preview=previewRecoveryIcsReconciliation(state,child.id,await file.text());if(!preview.validCalendar){status.textContent='File không có cấu trúc VCALENDAR hợp lệ.';rows.innerHTML='<div class="empty">Không có dòng hợp lệ để chọn.</div>';return;}pendingRecoveryPreview=preview;rows.innerHTML=preview.items.length?preview.items.map((item)=>`<label><input type="checkbox" name="rowIds" value="${esc(item.id)}"><span><strong>${esc(item.id)}</strong> · ${esc(item.status)} · local ${esc(item.localDate||'—')} · file ${esc(item.fileDate||'—')}</span></label>`).join(''):'<div class="empty">Không có dòng reconciliation.</div>';button.disabled=!preview.items.length;status.textContent=`Preview ${preview.items.length} dòng. Chọn dòng cần xuất; không thay đổi reminder.`;return;
  }
  if(event.target.id==='v16RecoveryReportExportForm'){
    event.preventDefault();const status=document.querySelector('#v16RecoveryReportStatus');if(!pendingRecoveryPreview){status.textContent='Cần preview file .ics trước.';return;}const ids=new FormData(event.target).getAll('rowIds').map(String);if(!ids.length){status.textContent='Hãy chọn ít nhất một dòng.';return;}const report=buildRecoveryReconciliationReport(pendingRecoveryPreview,ids);downloadText('growup-recovery-reconciliation-report.json',JSON.stringify(report,null,2));status.textContent=`Đã xuất ${report.summary.selected} dòng metadata; không áp dụng thay đổi.`;return;
  }
  if(event.target.id==='v16EvidenceImportForm'){
    event.preventDefault();const file=new FormData(event.target).get('file'),status=document.querySelector('#v16EvidenceStatus'),apply=document.querySelector('#v16ApplyEvidenceImport');pendingEvidencePackage=null;apply.disabled=true;try{const pkg=JSON.parse(await file.text()),preview=previewCompatibilityEvidenceImport(pkg,readState().settings||{});if(!preview.valid){status.textContent='Checksum/schema/format không hợp lệ. Import bị khóa.';return;}pendingEvidencePackage=pkg;apply.disabled=false;status.textContent=`Checksum hợp lệ · ${preview.accepted.length} record có thể thêm · ${preview.duplicates} trùng · ${preview.rejected} bị loại · flow: ${preview.coveredFlows.join(', ')||'không'}.`;}catch{status.textContent='JSON không hợp lệ. Import bị khóa.';}return;
  }
},true);

document.addEventListener('click',(event)=>{
  if(event.target.closest('#v16ExportReceiptIntegrity')){downloadText('growup-safe-export-receipts-integrity.json',JSON.stringify(buildIntegrityExportVerificationReceiptPackage(readState().settings||{}),null,2));return;}
  if(event.target.closest('#v16ApplyReceiptImport')){if(!pendingReceiptPackage)return;const state=readState(),result=applyExportVerificationReceiptImport(state.settings||{},pendingReceiptPackage);if(result.changed){state.settings=result.settings;auditedSave(state,'safe_export_receipt_package_imported',{added:result.added,duplicates:result.duplicates,rejected:result.rejected});pendingReceiptPackage=null;location.reload();}else document.querySelector('#v16ReceiptIntegrityStatus').textContent='Không có receipt mới để nhập.';return;}
  if(event.target.closest('#v16ExportPresetIntegrity')){downloadText('growup-workload-presets-integrity.json',JSON.stringify(buildIntegrityWorkloadPresetPackage(readState().settings||{}),null,2));return;}
  if(event.target.closest('#v16ApplyPresetIntegrityImport')){if(!pendingPresetPackage)return;const state=readState(),result=applyIntegrityWorkloadPresetImport(state.settings||{},pendingPresetPackage.pkg,{conflictStrategy:pendingPresetPackage.strategy});if(result.changed){state.settings=result.settings;auditedSave(state,'workload_preset_integrity_imported',{added:result.added,conflicts:result.conflicts,rejected:result.rejected,strategy:result.strategy});pendingPresetPackage=null;location.reload();}else document.querySelector('#v16PresetIntegrityStatus').textContent='Không có preset mới để nhập.';return;}
  if(event.target.closest('#v16ExportSavedReceipts')){downloadText('growup-saved-search-integrity-receipts.json',JSON.stringify(buildSavedSearchIntegrityReceiptPackage(readState().settings||{},savedReceiptFilter),null,2));return;}
  if(event.target.closest('#v16ClearSavedReceipts')){if(!confirm('Xóa toàn bộ lịch sử receipt Saved Search integrity cục bộ?'))return;const state=readState();state.settings=clearSavedSearchIntegrityReceipts(state.settings||{});auditedSave(state,'saved_search_integrity_receipts_cleared',{});refreshSavedReceiptPanel();return;}
  if(event.target.closest('#v16ExportEvidencePackage')){downloadText('growup-compatibility-evidence-integrity.json',JSON.stringify(buildCompatibilityEvidencePackage(readState().settings||{}),null,2));return;}
  if(event.target.closest('#v16ApplyEvidenceImport')){if(!pendingEvidencePackage)return;const state=readState(),result=applyCompatibilityEvidenceImport(state.settings||{},pendingEvidencePackage);if(result.changed){state.settings=result.settings;auditedSave(state,'compatibility_evidence_package_imported',{added:result.added,duplicates:result.duplicates,rejected:result.rejected});pendingEvidencePackage=null;location.reload();}else document.querySelector('#v16EvidenceStatus').textContent='Không có evidence mới để nhập.';return;}
});

document.addEventListener('change',(event)=>{
  if(event.target.closest('#v16ReceiptIntegrityImportForm input[name="file"]')){pendingReceiptPackage=null;const b=document.querySelector('#v16ApplyReceiptImport');if(b)b.disabled=true;}
  if(event.target.closest('#v16PresetIntegrityImportForm input[name="file"],#v16PresetIntegrityImportForm select[name="strategy"]')){pendingPresetPackage=null;const b=document.querySelector('#v16ApplyPresetIntegrityImport');if(b)b.disabled=true;}
  if(event.target.closest('#v16EvidenceImportForm input[name="file"]')){pendingEvidencePackage=null;const b=document.querySelector('#v16ApplyEvidenceImport');if(b)b.disabled=true;}
});
observer.observe(document.querySelector('#app'),{childList:true,subtree:true});enhanceV16();
