import { migrateState } from './core/schema.js';
import { saveState, appendAudit } from './core/store.js';
import { previewExportVerificationReceiptImport } from './core/export-verification-package-integrity.js';
import { receiptImportHistory, applyReceiptImportWithHistory, undoLastReceiptImport, RECEIPT_IMPORT_HISTORY_NOTE } from './core/receipt-import-history.js';
import { previewIntegrityWorkloadPresetImport } from './core/workload-preset-package-integrity.js';
import { workloadPresetImportHistory, applyWorkloadPresetImportWithHistory, undoLastWorkloadPresetImport, WORKLOAD_PRESET_IMPORT_HISTORY_NOTE } from './core/workload-preset-import-history.js';
import { buildIntegritySavedSearchReceiptPackage, previewSavedSearchReceiptImport, applySavedSearchReceiptImport, SAVED_SEARCH_RECEIPT_INTEGRITY_NOTE } from './core/saved-search-receipt-package-integrity.js';
import { previewRecoveryIcsReconciliation } from './core/recovery-ics-reconciliation.js';
import { buildIntegrityRecoveryReconciliationReport, verifyRecoveryReconciliationReportIntegrity, recoveryReconciliationReportVerificationReceipts, recordRecoveryReconciliationReportVerificationReceipt, RECOVERY_RECONCILIATION_REPORT_INTEGRITY_NOTE } from './core/recovery-reconciliation-report-integrity.js';
import { previewCompatibilityEvidenceImport } from './core/compatibility-evidence-package.js';
import { compatibilityEvidenceImportHistory, applyCompatibilityEvidenceImportWithHistory, undoLastCompatibilityEvidenceImport, compatibilityEvidenceFreshnessSummary, COMPATIBILITY_EVIDENCE_IMPORT_HISTORY_NOTE } from './core/compatibility-evidence-import-history.js';

const STORAGE_KEY='growup_mychildren_v1';
let scheduled=false,pendingReceipt=null,pendingPreset=null,pendingSavedReceipt=null,pendingRecovery=null,pendingEvidence=null;
const observer=new MutationObserver(()=>queueMicrotask(enhanceV17));
function readState(){try{return migrateState(JSON.parse(localStorage.getItem(STORAGE_KEY)||'{"version":5,"children":[]}'));}catch{return migrateState({version:5,children:[]});}}
function auditedSave(state,type,details={}){saveState(appendAudit(state,type,details));}
function esc(value=''){return String(value).replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function activePage(){return document.querySelector('.nav [data-nav].active')?.dataset.nav||document.querySelector('#mobileNav')?.value||'';}
function selectedChild(state){return state.children.find((item)=>item.id===state.selectedChildId)||state.children[0]||null;}
function downloadText(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0);}
function last(list){return list.length?list[list.length-1]:null;}

function managedReceiptPanel(state){const history=receiptImportHistory(state.settings||{}),latest=last(history);return `<section class="card v16-panel" data-v17="receipt-history"><div class="v16-heading"><div><span class="v16-kicker">Lượt 106 · Managed receipt import</span><h2>Import history + undo an toàn</h2></div><span class="pill">${history.length} lượt</span></div><form id="v17ReceiptImportForm" class="form"><label><span>Receipt package SHA-256</span><input name="file" type="file" accept="application/json,.json" required></label><div class="v16-actions"><button class="secondary" type="submit">Xác minh & preview</button><button class="primary" type="button" id="v17ApplyReceipt" disabled>Import có lịch sử</button><button class="danger" type="button" id="v17UndoReceipt" ${latest?'':'disabled'}>Undo lần import cuối</button></div></form><div id="v17ReceiptStatus" class="v16-status">${latest?`Lần gần nhất: ${esc(latest.at)} · ${latest.added.length} metadata receipt.`:'Chưa có lịch sử import được quản lý.'}</div><div class="v16-note">${esc(RECEIPT_IMPORT_HISTORY_NOTE)}</div></section>`;}

function managedPresetPanel(state){const history=workloadPresetImportHistory(state.settings||{}),latest=last(history);return `<section class="card v16-panel" data-v17="preset-history"><div class="v16-heading"><div><span class="v16-kicker">Lượt 107 · Managed preset import</span><h2>Conflict audit + undo</h2></div><span class="pill">${history.length} lượt</span></div><form id="v17PresetImportForm" class="form"><label><span>Preset package SHA-256</span><input name="file" type="file" accept="application/json,.json" required></label><label><span>Xử lý xung đột</span><select name="strategy"><option value="skip">Skip</option><option value="rename">Rename</option></select></label><div class="v16-actions"><button class="secondary" type="submit">Xác minh & preview</button><button class="primary" type="button" id="v17ApplyPreset" disabled>Import có audit</button><button class="danger" type="button" id="v17UndoPreset" ${latest?'':'disabled'}>Undo lần import cuối</button></div></form><div id="v17PresetStatus" class="v16-status">${latest?`Lần gần nhất: ${esc(latest.at)} · ${latest.strategy} · ${latest.added.length} preset.`:'Chưa có lịch sử import preset.'}</div><div class="v16-note">${esc(WORKLOAD_PRESET_IMPORT_HISTORY_NOTE)}</div></section>`;}

function savedReceiptIntegrityPanel(){return `<section class="card v16-panel" data-v17="saved-receipt-integrity"><div class="v16-heading"><div><span class="v16-kicker">Lượt 108 · Saved Search receipt integrity</span><h2>Receipt package SHA-256</h2></div><span class="pill">duplicate-safe</span></div><div class="v16-actions"><button class="secondary" type="button" id="v17ExportSavedReceipts">Xuất package SHA-256</button></div><form id="v17SavedReceiptImportForm" class="form"><label><span>Receipt package cần nhập</span><input name="file" type="file" accept="application/json,.json" required></label><div class="v16-actions"><button class="secondary" type="submit">Xác minh & preview</button><button class="primary" type="button" id="v17ApplySavedReceipt" disabled>Áp dụng import</button></div></form><div id="v17SavedReceiptStatus" class="v16-status">Chưa xác minh package.</div><div class="v16-note">${esc(SAVED_SEARCH_RECEIPT_INTEGRITY_NOTE)}</div></section>`;}

function recoveryIntegrityPanel(state){const child=selectedChild(state),receipts=recoveryReconciliationReportVerificationReceipts(state.settings||{}),latest=last(receipts);return `<section class="card v16-panel" data-v17="recovery-integrity"><div class="v16-heading"><div><span class="v16-kicker">Lượt 109 · Recovery report integrity</span><h2>Signed report + local receipt</h2></div><span class="pill">SHA-256</span></div>${child?`<form id="v17RecoveryPreviewForm" class="form"><label><span>File recovery .ics</span><input name="file" type="file" accept="text/calendar,.ics" required></label><button class="secondary" type="submit">Preview reconciliation</button></form><form id="v17RecoveryExportForm" class="form"><div id="v17RecoveryRows" class="v16-checks"><div class="empty">Chưa có preview.</div></div><button class="primary" type="submit" disabled>Xuất signed report</button></form>`:'<div class="empty">Cần có hồ sơ trẻ.</div>'}<form id="v17RecoveryVerifyForm" class="form"><label><span>Signed report cần xác minh</span><input name="file" type="file" accept="application/json,.json" required></label><button class="secondary" type="submit">Xác minh & ghi receipt cục bộ</button></form><div id="v17RecoveryStatus" class="v16-status">${latest?`Receipt gần nhất: ${esc(latest.at)} · ${latest.result} · ${latest.rowCount} dòng.`:'Chưa có receipt xác minh report.'}</div><div class="v16-note">${esc(RECOVERY_RECONCILIATION_REPORT_INTEGRITY_NOTE)}</div></section>`;}

function evidenceAuditPanel(state){const history=compatibilityEvidenceImportHistory(state.settings||{}),latest=last(history),fresh=compatibilityEvidenceFreshnessSummary(state.settings||{});return `<section class="card v16-panel" data-v17="evidence-audit"><div class="v16-heading"><div><span class="v16-kicker">Lượt 110 · Evidence audit & freshness</span><h2>Import undo + tuổi bằng chứng</h2></div><span class="pill">${fresh.freshModules.length}/${fresh.modules.length} fresh</span></div><form id="v17EvidenceImportForm" class="form"><label><span>Compatibility evidence package</span><input name="file" type="file" accept="application/json,.json" required></label><div class="v16-actions"><button class="secondary" type="submit">Xác minh & preview</button><button class="primary" type="button" id="v17ApplyEvidence" disabled>Import có audit</button><button class="danger" type="button" id="v17UndoEvidence" ${latest?'':'disabled'}>Undo import cuối</button></div></form><div class="v16-list">${fresh.modules.length?fresh.modules.slice(0,12).map((row)=>`<div><strong>${esc(row.module)}</strong><span>${row.fresh?'fresh':`cần chú ý · thiếu ${row.missingFlows.length} · stale ${row.staleFlows.length}`}${row.axeRecheckRequired?' · Axe cần local recheck':''}</span></div>`).join(''):'<div class="empty">Chưa có evidence để đánh giá freshness.</div>'}</div><div id="v17EvidenceStatus" class="v16-status">${latest?`Import gần nhất: ${esc(latest.at)} · ${latest.deltas.length} non-Axe delta.`:'Chưa có import audit.'}</div><div class="v16-note">${esc(COMPATIBILITY_EVIDENCE_IMPORT_HISTORY_NOTE)}</div></section>`;}

function retireOldImportPaths(){
  const pairs=[['#v16ReceiptIntegrityImportForm','#v16ReceiptIntegrityStatus','Import apply đã chuyển sang Lượt 106 để luôn có history/undo.'],['#v16PresetIntegrityImportForm','#v16PresetIntegrityStatus','Import apply đã chuyển sang Lượt 107 để luôn có conflict audit/undo.'],['#v16EvidenceImportForm','#v16EvidenceStatus','Import apply đã chuyển sang Lượt 110 để luôn có audit/undo và giữ Axe local-only.']];
  for(const [formSel,statusSel,message] of pairs){
    const form=document.querySelector(formSel),status=document.querySelector(statusSel);
    if(form){
      form.hidden=true;
      form.setAttribute('aria-hidden','true');
      form.style.setProperty('display','none','important');
      form.querySelectorAll('input,select,textarea,button,fieldset').forEach((control)=>{control.disabled=true;control.setAttribute('tabindex','-1');});
    }
    if(status&&status.textContent!==message)status.textContent=message;
  }
}
function addPanels(){const main=document.querySelector('.main');if(!main||activePage()!=='overview'||document.querySelector('[data-v17="receipt-history"]'))return;const state=readState();main.insertAdjacentHTML('beforeend',`<div class="v16-grid" data-v17-grid>${managedReceiptPanel(state)}${managedPresetPanel(state)}${savedReceiptIntegrityPanel()}${recoveryIntegrityPanel(state)}${evidenceAuditPanel(state)}</div>`);}
function enhanceV17(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;retireOldImportPaths();addPanels();});}

document.addEventListener('submit',async(event)=>{
  if(event.target.id==='v17ReceiptImportForm'){
    event.preventDefault();const file=new FormData(event.target).get('file'),status=document.querySelector('#v17ReceiptStatus'),apply=document.querySelector('#v17ApplyReceipt');pendingReceipt=null;apply.disabled=true;try{const pkg=JSON.parse(await file.text()),preview=previewExportVerificationReceiptImport(pkg,readState().settings||{});if(!preview.valid){status.textContent='Checksum/format không hợp lệ. Import bị khóa.';return;}pendingReceipt=pkg;apply.disabled=false;status.textContent=`Preview: ${preview.accepted.length} thêm mới · ${preview.duplicates} trùng · ${preview.rejected} loại.`;}catch{status.textContent='JSON không hợp lệ.';}return;
  }
  if(event.target.id==='v17PresetImportForm'){
    event.preventDefault();const form=new FormData(event.target),file=form.get('file'),strategy=String(form.get('strategy')||'skip'),status=document.querySelector('#v17PresetStatus'),apply=document.querySelector('#v17ApplyPreset');pendingPreset=null;apply.disabled=true;try{const pkg=JSON.parse(await file.text()),preview=previewIntegrityWorkloadPresetImport(pkg,readState().settings||{},{conflictStrategy:strategy});if(!preview.valid){status.textContent='Checksum/format không hợp lệ.';return;}pendingPreset={pkg,strategy};apply.disabled=false;status.textContent=`Preview: ${preview.accepted} thêm · ${preview.conflicts} xung đột · ${preview.rejected} từ chối · ${preview.strategy}.`;}catch{status.textContent='JSON không hợp lệ.';}return;
  }
  if(event.target.id==='v17SavedReceiptImportForm'){
    event.preventDefault();const file=new FormData(event.target).get('file'),status=document.querySelector('#v17SavedReceiptStatus'),apply=document.querySelector('#v17ApplySavedReceipt');pendingSavedReceipt=null;apply.disabled=true;try{const pkg=JSON.parse(await file.text()),preview=previewSavedSearchReceiptImport(pkg,readState().settings||{});if(!preview.valid){status.textContent='Checksum/format không hợp lệ.';return;}pendingSavedReceipt=pkg;apply.disabled=false;status.textContent=`Preview: ${preview.accepted.length} thêm · ${preview.duplicates} trùng · ${preview.rejected} loại.`;}catch{status.textContent='JSON không hợp lệ.';}return;
  }
  if(event.target.id==='v17RecoveryPreviewForm'){
    event.preventDefault();const state=readState(),child=selectedChild(state),file=new FormData(event.target).get('file'),rows=document.querySelector('#v17RecoveryRows'),button=document.querySelector('#v17RecoveryExportForm button[type="submit"]'),status=document.querySelector('#v17RecoveryStatus');pendingRecovery=null;button.disabled=true;if(!child||!(file instanceof File)){status.textContent='Thiếu hồ sơ hoặc file .ics.';return;}const preview=previewRecoveryIcsReconciliation(state,child.id,await file.text());if(!preview.validCalendar){rows.innerHTML='<div class="empty">VCALENDAR không hợp lệ.</div>';status.textContent='Không thể tạo signed report.';return;}pendingRecovery=preview;rows.innerHTML=preview.items.length?preview.items.map((item)=>`<label><input type="checkbox" name="rowIds" value="${esc(item.id)}"><span><strong>${esc(item.id)}</strong> · ${esc(item.status)} · local ${esc(item.localDate||'—')} · file ${esc(item.fileDate||'—')}</span></label>`).join(''):'<div class="empty">Không có dòng reconciliation.</div>';button.disabled=!preview.items.length;status.textContent=`Preview ${preview.items.length} dòng; chọn dòng để xuất signed report.`;return;
  }
  if(event.target.id==='v17RecoveryExportForm'){
    event.preventDefault();const status=document.querySelector('#v17RecoveryStatus');if(!pendingRecovery){status.textContent='Cần preview .ics trước.';return;}const ids=new FormData(event.target).getAll('rowIds').map(String);if(!ids.length){status.textContent='Hãy chọn ít nhất một dòng.';return;}const report=buildIntegrityRecoveryReconciliationReport(pendingRecovery,ids);downloadText('growup-recovery-reconciliation-report-integrity.json',JSON.stringify(report,null,2));status.textContent=`Đã xuất ${report.rows.length} dòng với SHA-256; không apply reminder/calendar.`;return;
  }
  if(event.target.id==='v17RecoveryVerifyForm'){
    event.preventDefault();const file=new FormData(event.target).get('file'),status=document.querySelector('#v17RecoveryStatus');try{const report=JSON.parse(await file.text()),verification=verifyRecoveryReconciliationReportIntegrity(report),state=readState();state.settings=recordRecoveryReconciliationReportVerificationReceipt(state.settings||{},verification);auditedSave(state,'recovery_reconciliation_report_verified',{result:verification.valid?'valid':'invalid',format:verification.format||'unknown',rowCount:verification.rowCount});status.textContent=`Đã ghi receipt local: ${verification.valid?'HỢP LỆ':'KHÔNG HỢP LỆ'} · ${verification.rowCount} dòng.`;}catch{status.textContent='JSON report không hợp lệ; chưa ghi receipt.';}return;
  }
  if(event.target.id==='v17EvidenceImportForm'){
    event.preventDefault();const file=new FormData(event.target).get('file'),status=document.querySelector('#v17EvidenceStatus'),apply=document.querySelector('#v17ApplyEvidence');pendingEvidence=null;apply.disabled=true;try{const pkg=JSON.parse(await file.text()),preview=previewCompatibilityEvidenceImport(pkg,readState().settings||{});if(!preview.valid){status.textContent='Checksum/schema không hợp lệ.';return;}pendingEvidence=pkg;apply.disabled=false;status.textContent=`Preview: ${preview.accepted.length} non-Axe thêm/cập nhật · ${preview.duplicates} trùng · ${preview.axeRecheckRequired} Axe phải chạy local.`;}catch{status.textContent='JSON không hợp lệ.';}return;
  }
},true);

document.addEventListener('click',(event)=>{
  if(event.target.closest('#v17ApplyReceipt')){if(!pendingReceipt)return;const state=readState(),result=applyReceiptImportWithHistory(state.settings||{},pendingReceipt);if(result.changed){state.settings=result.settings;auditedSave(state,'safe_export_receipt_import_with_history',{added:result.added});pendingReceipt=null;location.reload();}else document.querySelector('#v17ReceiptStatus').textContent='Không có receipt mới để nhập.';return;}
  if(event.target.closest('#v17UndoReceipt')){if(!confirm('Undo đúng metadata của lần receipt import gần nhất?'))return;const state=readState(),result=undoLastReceiptImport(state.settings||{});if(result.changed){state.settings=result.settings;auditedSave(state,'safe_export_receipt_import_undone',{removed:result.removed,missing:result.missing});location.reload();}else document.querySelector('#v17ReceiptStatus').textContent='Không có delta phù hợp để undo.';return;}
  if(event.target.closest('#v17ApplyPreset')){if(!pendingPreset)return;const state=readState(),result=applyWorkloadPresetImportWithHistory(state.settings||{},pendingPreset.pkg,{conflictStrategy:pendingPreset.strategy});if(result.changed){state.settings=result.settings;auditedSave(state,'workload_preset_import_with_history',{added:result.added,strategy:result.strategy,conflicts:result.conflicts});pendingPreset=null;location.reload();}else document.querySelector('#v17PresetStatus').textContent='Không có preset mới để nhập.';return;}
  if(event.target.closest('#v17UndoPreset')){if(!confirm('Undo preset của lần import gần nhất? Preset đã sửa sau import sẽ được giữ.'))return;const state=readState(),result=undoLastWorkloadPresetImport(state.settings||{});if(result.changed){state.settings=result.settings;auditedSave(state,'workload_preset_import_undone',{removed:result.removed,preservedModified:result.preservedModified});location.reload();}else document.querySelector('#v17PresetStatus').textContent='Không có delta phù hợp để undo.';return;}
  if(event.target.closest('#v17ExportSavedReceipts')){downloadText('growup-saved-search-integrity-receipts-sha256.json',JSON.stringify(buildIntegritySavedSearchReceiptPackage(readState().settings||{}),null,2));return;}
  if(event.target.closest('#v17ApplySavedReceipt')){if(!pendingSavedReceipt)return;const state=readState(),result=applySavedSearchReceiptImport(state.settings||{},pendingSavedReceipt);if(result.changed){state.settings=result.settings;auditedSave(state,'saved_search_integrity_receipts_imported',{added:result.added,duplicates:result.duplicates,rejected:result.rejected});pendingSavedReceipt=null;location.reload();}else document.querySelector('#v17SavedReceiptStatus').textContent='Không có receipt mới để nhập.';return;}
  if(event.target.closest('#v17ApplyEvidence')){if(!pendingEvidence)return;const state=readState(),result=applyCompatibilityEvidenceImportWithHistory(state.settings||{},pendingEvidence);if(result.changed){state.settings=result.settings;auditedSave(state,'compatibility_evidence_import_with_history',{added:result.added,axeRecheckRequired:result.axeRecheckRequired});pendingEvidence=null;location.reload();}else document.querySelector('#v17EvidenceStatus').textContent='Không có evidence mới để nhập.';return;}
  if(event.target.closest('#v17UndoEvidence')){if(!confirm('Undo non-Axe evidence của lần import gần nhất? Record đã đổi sau import sẽ được giữ.'))return;const state=readState(),result=undoLastCompatibilityEvidenceImport(state.settings||{});if(result.changed){state.settings=result.settings;auditedSave(state,'compatibility_evidence_import_undone',{reverted:result.reverted,preservedModified:result.preservedModified});location.reload();}else document.querySelector('#v17EvidenceStatus').textContent='Không có delta phù hợp để undo.';return;}
});

document.addEventListener('change',(event)=>{
  if(event.target.closest('#v17ReceiptImportForm input[name="file"]')){pendingReceipt=null;const b=document.querySelector('#v17ApplyReceipt');if(b)b.disabled=true;}
  if(event.target.closest('#v17PresetImportForm input[name="file"],#v17PresetImportForm select[name="strategy"]')){pendingPreset=null;const b=document.querySelector('#v17ApplyPreset');if(b)b.disabled=true;}
  if(event.target.closest('#v17SavedReceiptImportForm input[name="file"]')){pendingSavedReceipt=null;const b=document.querySelector('#v17ApplySavedReceipt');if(b)b.disabled=true;}
  if(event.target.closest('#v17RecoveryPreviewForm input[name="file"]')){pendingRecovery=null;const rows=document.querySelector('#v17RecoveryRows'),b=document.querySelector('#v17RecoveryExportForm button[type="submit"]');if(rows)rows.innerHTML='<div class="empty">File đã đổi; hãy preview lại.</div>';if(b)b.disabled=true;}
  if(event.target.closest('#v17EvidenceImportForm input[name="file"]')){pendingEvidence=null;const b=document.querySelector('#v17ApplyEvidence');if(b)b.disabled=true;}
});
observer.observe(document.querySelector('#app'),{childList:true,subtree:true});enhanceV17();
