import { migrateState } from './core/schema.js';
import { saveState, appendAudit } from './core/store.js';
import { exportVerificationImportHistory, undoLastExportVerificationReceiptImport, EXPORT_VERIFICATION_IMPORT_HISTORY_NOTE } from './core/export-verification-import-history.js';
import { workloadPresetImportHistory, undoLastWorkloadPresetImport, WORKLOAD_PRESET_IMPORT_HISTORY_NOTE } from './core/workload-preset-import-history.js';
import { buildIntegritySavedSearchReceiptPackage, previewSavedSearchIntegrityReceiptImport, applySavedSearchIntegrityReceiptImport, SAVED_SEARCH_RECEIPT_PACKAGE_INTEGRITY_NOTE } from './core/saved-search-integrity-receipt-package.js';
import { verifyRecoveryReconciliationReportIntegrity, recoveryReconciliationReportVerificationReceipts, recordRecoveryReconciliationReportVerificationReceipt, RECOVERY_RECONCILIATION_REPORT_INTEGRITY_NOTE } from './core/recovery-reconciliation-report-integrity.js';
import { compatibilityEvidenceImportHistory, undoLastCompatibilityEvidenceImport, compatibilityEvidenceFreshness, COMPATIBILITY_EVIDENCE_IMPORT_AUDIT_NOTE } from './core/compatibility-evidence-import-audit.js';

const STORAGE_KEY='growup_mychildren_v1';
let scheduled=false,pendingSavedReceiptPackage=null,freshnessDays=30;
const observer=new MutationObserver(()=>queueMicrotask(enhanceV17));
function readState(){try{return migrateState(JSON.parse(localStorage.getItem(STORAGE_KEY)||'{"version":5,"children":[]}'));}catch{return migrateState({version:5,children:[]});}}
function esc(value=''){return String(value).replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function auditedSave(state,type,details={}){saveState(appendAudit(state,type,details));}
function activePage(){return document.querySelector('.nav [data-nav].active')?.dataset.nav||document.querySelector('#mobileNav')?.value||'';}
function downloadText(name,text){const url=URL.createObjectURL(new Blob([text],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0);}
function latestOpen(history=[]){return [...history].reverse().find((item)=>!item.undoneAt)||null;}
function when(value){return value?new Date(value).toLocaleString('vi-VN'):'—';}

function receiptUndoPanel(state){const history=exportVerificationImportHistory(state.settings||{}),last=latestOpen(history);return `<section class="card v17-panel" data-v17="receipt-import-history"><div class="v17-heading"><div><span class="v17-kicker">Lượt 106 · Receipt import history</span><h2>Lịch sử import và hoàn tác</h2></div><span class="pill">${history.length} lượt</span></div>${last?`<div class="v17-summary"><strong>Lượt gần nhất</strong><span>${esc(when(last.at))} · ${last.addedCount} receipt · ${last.duplicates} trùng · ${last.rejected} loại</span></div><button class="danger" type="button" id="v17UndoReceiptImport">Hoàn tác lượt import gần nhất</button>`:'<div class="empty">Chưa có lượt import receipt có thể hoàn tác.</div>'}<div id="v17ReceiptUndoStatus" class="v17-status">Undo chỉ chạy khi metadata receipt chưa bị thay đổi/xóa.</div><div class="v17-note">${esc(EXPORT_VERIFICATION_IMPORT_HISTORY_NOTE)}</div></section>`;}

function presetUndoPanel(state){const history=workloadPresetImportHistory(state.settings||{}),last=latestOpen(history);return `<section class="card v17-panel" data-v17="preset-import-history"><div class="v17-heading"><div><span class="v17-kicker">Lượt 107 · Preset import audit</span><h2>Quyết định import và hoàn tác</h2></div><span class="pill">${history.length} lượt</span></div>${last?`<div class="v17-summary"><strong>Lượt gần nhất</strong><span>${esc(when(last.at))} · ${last.addedCount} preset · ${last.conflicts} conflict · chiến lược ${esc(last.strategy)}</span></div><div class="v17-decisions">${last.decisions.slice(0,8).map((item)=>`<span>${item.index+1}. ${esc(item.action)}${item.id?` · ${esc(item.id)}`:''}</span>`).join('')}</div><button class="danger" type="button" id="v17UndoPresetImport">Hoàn tác lượt import preset gần nhất</button>`:'<div class="empty">Chưa có lượt import preset có thể hoàn tác.</div>'}<div id="v17PresetUndoStatus" class="v17-status">Preset đã sửa sau import sẽ không bị xóa nhầm.</div><div class="v17-note">${esc(WORKLOAD_PRESET_IMPORT_HISTORY_NOTE)}</div></section>`;}

function savedReceiptIntegrityPanel(){return `<section class="card v17-panel" data-v17="saved-search-receipt-integrity"><div class="v17-heading"><div><span class="v17-kicker">Lượt 108 · Saved Search receipt package</span><h2>Checksum + duplicate-safe import</h2></div><span class="pill">SHA-256</span></div><button class="secondary" type="button" id="v17ExportSavedReceiptIntegrity">Xuất receipt package SHA-256</button><form id="v17SavedReceiptIntegrityImportForm" class="form"><label><span>Package receipt Saved Search</span><input name="file" type="file" accept="application/json,.json" required></label><div class="v17-actions"><button class="secondary" type="submit">Xác minh & preview</button><button class="primary" type="button" id="v17ApplySavedReceiptImport" disabled>Áp dụng import</button></div></form><div id="v17SavedReceiptIntegrityStatus" class="v17-status">Chưa xác minh package.</div><div class="v17-note">${esc(SAVED_SEARCH_RECEIPT_PACKAGE_INTEGRITY_NOTE)}</div></section>`;}

function recoveryIntegrityPanel(state){const receipts=recoveryReconciliationReportVerificationReceipts(state.settings||{});return `<section class="card v17-panel" data-v17="recovery-report-integrity"><div class="v17-heading"><div><span class="v17-kicker">Lượt 109 · Recovery report verifier</span><h2>Xác minh report SHA-256</h2></div><span class="pill">${receipts.length} receipt</span></div><form id="v17RecoveryReportVerifyForm" class="form"><label><span>Recovery reconciliation report JSON</span><input name="file" type="file" accept="application/json,.json" required></label><button class="secondary" type="submit">Xác minh report</button></form><div id="v17RecoveryVerifyStatus" class="v17-status">Receipt chỉ được ghi sau khi JSON được đọc và verifier chạy.</div><div class="v17-list">${receipts.length?receipts.slice().reverse().slice(0,8).map((item)=>`<div><strong>${item.result==='valid'?'Hợp lệ':'Không hợp lệ'}</strong><span>${esc(when(item.at))} · ${item.rowCount} dòng · ${esc(item.algorithm)}</span></div>`).join(''):'<div class="empty">Chưa có receipt xác minh Recovery report.</div>'}</div><div class="v17-note">${esc(RECOVERY_RECONCILIATION_REPORT_INTEGRITY_NOTE)}</div></section>`;}

function evidenceAuditPanel(state){const settings=state.settings||{},history=compatibilityEvidenceImportHistory(settings),last=latestOpen(history),fresh=compatibilityEvidenceFreshness(settings,{staleAfterDays:freshnessDays});return `<section class="card v17-panel" data-v17="evidence-import-audit"><div class="v17-heading"><div><span class="v17-kicker">Lượt 110 · Evidence audit & freshness</span><h2>Audit import, undo và độ mới evidence</h2></div><span class="pill">Axe local-only</span></div>${last?`<div class="v17-summary"><strong>Import gần nhất</strong><span>${esc(when(last.at))} · thêm ${last.addedCount} · thay ${last.replacedCount} · Axe cần chạy lại ${last.axeRecheckRequired}</span></div><button class="danger" type="button" id="v17UndoEvidenceImport">Hoàn tác import evidence gần nhất</button>`:'<div class="empty">Chưa có import evidence non-Axe có thể hoàn tác.</div>'}<form id="v17FreshnessForm" class="form v17-freshness-form"><label><span>Ngưỡng cũ sau số ngày</span><input type="number" name="days" min="1" max="365" value="${freshnessDays}"></label><button class="secondary" type="submit">Tính lại độ mới</button></form><div class="v17-flow-grid">${fresh.flows.map((item)=>`<div><strong>${esc(item.flow)}</strong><span>${esc(item.status)}${item.ageDays==null?'':` · ${item.ageDays} ngày`}</span></div>`).join('')}</div><div id="v17EvidenceAuditStatus" class="v17-status">Freshness chỉ là mô tả; không cho phép retirement tự động.</div><div class="v17-note">${esc(COMPATIBILITY_EVIDENCE_IMPORT_AUDIT_NOTE)}</div></section>`;}

function allPanels(state){return `<div class="v17-grid">${receiptUndoPanel(state)}${presetUndoPanel(state)}${savedReceiptIntegrityPanel()}${recoveryIntegrityPanel(state)}${evidenceAuditPanel(state)}</div>`;}
function addPanels(){const main=document.querySelector('.main');if(!main||activePage()!=='overview'||document.querySelector('[data-v17="receipt-import-history"]'))return;main.insertAdjacentHTML('beforeend',allPanels(readState()));}
function refreshPanels(){const grid=document.querySelector('.v17-grid');if(grid)grid.outerHTML=allPanels(readState());}
function enhanceV17(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;addPanels();});}

document.addEventListener('submit',async(event)=>{
  if(event.target.id==='v17SavedReceiptIntegrityImportForm'){
    event.preventDefault();const file=new FormData(event.target).get('file'),status=document.querySelector('#v17SavedReceiptIntegrityStatus'),apply=document.querySelector('#v17ApplySavedReceiptImport');pendingSavedReceiptPackage=null;apply.disabled=true;if(!(file instanceof File)){status.textContent='Thiếu file package.';return;}try{const pkg=JSON.parse(await file.text()),preview=previewSavedSearchIntegrityReceiptImport(pkg,readState().settings||{});if(!preview.valid){status.textContent='Checksum/format không hợp lệ. Import bị khóa.';return;}pendingSavedReceiptPackage=pkg;apply.disabled=false;status.textContent=`Checksum hợp lệ · ${preview.accepted.length} receipt có thể thêm · ${preview.duplicates} trùng · ${preview.rejected} bị loại.`;}catch{status.textContent='JSON không hợp lệ. Import bị khóa.';}return;
  }
  if(event.target.id==='v17RecoveryReportVerifyForm'){
    event.preventDefault();const file=new FormData(event.target).get('file'),status=document.querySelector('#v17RecoveryVerifyStatus');if(!(file instanceof File)){status.textContent='Thiếu file report.';return;}try{const pkg=JSON.parse(await file.text()),verification=verifyRecoveryReconciliationReportIntegrity(pkg),state=readState();state.settings=recordRecoveryReconciliationReportVerificationReceipt(state.settings||{},verification);auditedSave(state,'recovery_reconciliation_report_verified',{valid:verification.valid,rowCount:verification.rowCount,format:verification.format||'unknown'});status.textContent=verification.valid?`Report hợp lệ · ${verification.rowCount} dòng · receipt metadata đã lưu.`:`Report không hợp lệ · ${verification.rowCount} dòng · receipt invalid đã lưu.`;refreshPanels();}catch{status.textContent='JSON không hợp lệ; chưa ghi receipt.';}return;
  }
  if(event.target.id==='v17FreshnessForm'){
    event.preventDefault();const days=Number(new FormData(event.target).get('days'));freshnessDays=Math.min(365,Math.max(1,Number.isFinite(days)?Math.round(days):30));refreshPanels();return;
  }
},true);

document.addEventListener('click',(event)=>{
  if(event.target.closest('#v17UndoReceiptImport')){if(!confirm('Hoàn tác lượt import receipt gần nhất? Chỉ metadata của lượt import đó sẽ được gỡ.'))return;const state=readState(),result=undoLastExportVerificationReceiptImport(state.settings||{});if(result.changed){state.settings=result.settings;auditedSave(state,'safe_export_receipt_import_undone',{removed:result.removed});refreshPanels();}else{const status=document.querySelector('#v17ReceiptUndoStatus');if(status)status.textContent=result.reason==='receipt-state-diverged'?'Không hoàn tác: receipt đã thay đổi/xóa sau import.':'Không có lượt import để hoàn tác.';}return;}
  if(event.target.closest('#v17UndoPresetImport')){if(!confirm('Hoàn tác lượt import preset gần nhất? Preset đã sửa sau import sẽ được giữ nguyên và thao tác bị từ chối.'))return;const state=readState(),result=undoLastWorkloadPresetImport(state.settings||{});if(result.changed){state.settings=result.settings;auditedSave(state,'workload_preset_import_undone',{removed:result.removed});refreshPanels();}else{const status=document.querySelector('#v17PresetUndoStatus');if(status)status.textContent=result.reason==='preset-state-diverged'?'Không hoàn tác: preset đã thay đổi sau import.':'Không có lượt import để hoàn tác.';}return;}
  if(event.target.closest('#v17ExportSavedReceiptIntegrity')){downloadText('growup-saved-search-integrity-receipts-sha256.json',JSON.stringify(buildIntegritySavedSearchReceiptPackage(readState().settings||{}),null,2));return;}
  if(event.target.closest('#v17ApplySavedReceiptImport')){if(!pendingSavedReceiptPackage)return;const state=readState(),result=applySavedSearchIntegrityReceiptImport(state.settings||{},pendingSavedReceiptPackage);if(result.changed){state.settings=result.settings;auditedSave(state,'saved_search_integrity_receipts_imported',{added:result.added,duplicates:result.duplicates,rejected:result.rejected});pendingSavedReceiptPackage=null;refreshPanels();}else{const status=document.querySelector('#v17SavedReceiptIntegrityStatus');if(status)status.textContent='Không có receipt mới để nhập.';}return;}
  if(event.target.closest('#v17UndoEvidenceImport')){if(!confirm('Hoàn tác import evidence non-Axe gần nhất? Evidence đã thay đổi sau import sẽ không bị ghi đè.'))return;const state=readState(),result=undoLastCompatibilityEvidenceImport(state.settings||{});if(result.changed){state.settings=result.settings;auditedSave(state,'compatibility_evidence_import_undone',{restored:result.restored,removed:result.removed});refreshPanels();}else{const status=document.querySelector('#v17EvidenceAuditStatus');if(status)status.textContent=result.reason==='evidence-state-diverged'?'Không hoàn tác: evidence đã thay đổi sau import.':'Không có import evidence để hoàn tác.';}return;}
});

document.addEventListener('change',(event)=>{if(event.target.closest('#v17SavedReceiptIntegrityImportForm input[name="file"]')){pendingSavedReceiptPackage=null;const b=document.querySelector('#v17ApplySavedReceiptImport');if(b)b.disabled=true;const s=document.querySelector('#v17SavedReceiptIntegrityStatus');if(s)s.textContent='File đã thay đổi; hãy xác minh lại.';}});
observer.observe(document.querySelector('#app'),{childList:true,subtree:true});enhanceV17();
