import { migrateState } from './core/schema.js';
import { saveState, appendAudit } from './core/store.js';
import { buildReceiptImportHistoryPackage, reviewReceiptImportHistoryPackage, RECEIPT_IMPORT_HISTORY_PACKAGE_NOTE } from './core/receipt-import-history-package-integrity.js';
import { buildWorkloadPresetImportAuditPackage, reviewWorkloadPresetImportAuditPackage, WORKLOAD_PRESET_IMPORT_AUDIT_PACKAGE_NOTE } from './core/workload-preset-import-audit-package-integrity.js';
import { previewSavedSearchReceiptImport } from './core/saved-search-receipt-package-integrity.js';
import { savedSearchReceiptImportHistory, applySavedSearchReceiptImportWithHistory, undoLastSavedSearchReceiptImport, SAVED_SEARCH_RECEIPT_IMPORT_HISTORY_NOTE } from './core/saved-search-receipt-import-history.js';
import { filterRecoveryReconciliationVerificationReceipts, buildRecoveryReconciliationVerificationReceiptPackage, clearRecoveryReconciliationVerificationReceipts, RECOVERY_RECONCILIATION_VERIFICATION_RECEIPT_MANAGEMENT_NOTE } from './core/recovery-reconciliation-verification-receipt-management.js';
import { compatibilityEvidenceFreshnessPolicy, setCompatibilityEvidenceFreshnessPolicy, resetCompatibilityEvidenceFreshnessPolicy, buildCompatibilityEvidenceFreshnessReview, COMPATIBILITY_EVIDENCE_FRESHNESS_POLICY_NOTE } from './core/compatibility-evidence-freshness-policy.js';

const STORAGE_KEY='growup_mychildren_v1';
let scheduled=false,pendingSavedReceipt=null;
const observer=new MutationObserver(()=>queueMicrotask(enhanceV18));
function readState(){try{return migrateState(JSON.parse(localStorage.getItem(STORAGE_KEY)||'{"version":5,"children":[]}'));}catch{return migrateState({version:5,children:[]});}}
function auditedSave(state,type,details={}){saveState(appendAudit(state,type,details));}
function esc(value=''){return String(value).replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function activePage(){return document.querySelector('.nav [data-nav].active')?.dataset.nav||document.querySelector('#mobileNav')?.value||'';}
function downloadJson(name,payload){const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0);}
function retireForm(selector,statusSelector,message){const form=document.querySelector(selector),status=document.querySelector(statusSelector);if(form){form.hidden=true;form.setAttribute('aria-hidden','true');form.style.setProperty('display','none','important');form.querySelectorAll('input,select,textarea,button,fieldset').forEach((control)=>{control.disabled=true;control.setAttribute('tabindex','-1');});}if(status&&status.textContent!==message)status.textContent=message;}

function historyPackagePanel(state){return `<section class="card v16-panel" data-v18="receipt-history-package"><div class="v16-heading"><div><span class="v16-kicker">Lượt 111 · Receipt import-history portability</span><h2>Signed history package</h2></div><span class="pill">read-only</span></div><div class="v16-actions"><button class="secondary" id="v18ExportReceiptHistory" type="button">Xuất history SHA-256</button></div><form id="v18VerifyReceiptHistoryForm" class="form"><label><span>History package cần xác minh</span><input name="file" type="file" accept="application/json,.json" required></label><button class="secondary" type="submit">Xác minh & review</button></form><div id="v18ReceiptHistoryStatus" class="v16-status">${state.settings?.receiptImportHistory?.length||0} lượt import đang được quản lý cục bộ.</div><div class="v16-note">${esc(RECEIPT_IMPORT_HISTORY_PACKAGE_NOTE)}</div></section>`;}
function presetAuditPanel(state){return `<section class="card v16-panel" data-v18="preset-audit-package"><div class="v16-heading"><div><span class="v16-kicker">Lượt 112 · Preset import audit portability</span><h2>Signed conflict audit</h2></div><span class="pill">review-only</span></div><div class="v16-actions"><button class="secondary" id="v18ExportPresetAudit" type="button">Xuất audit SHA-256</button></div><form id="v18VerifyPresetAuditForm" class="form"><label><span>Audit package cần review</span><input name="file" type="file" accept="application/json,.json" required></label><button class="secondary" type="submit">Xác minh & review</button></form><div id="v18PresetAuditStatus" class="v16-status">${state.settings?.workloadPresetImportHistory?.length||0} lượt audit cục bộ.</div><div class="v16-note">${esc(WORKLOAD_PRESET_IMPORT_AUDIT_PACKAGE_NOTE)}</div></section>`;}
function savedReceiptManagedPanel(state){const history=savedSearchReceiptImportHistory(state.settings||{}),latest=history.at(-1);return `<section class="card v16-panel" data-v18="saved-receipt-history"><div class="v16-heading"><div><span class="v16-kicker">Lượt 113 · Managed Saved Search receipt import</span><h2>History + undo</h2></div><span class="pill">${history.length} lượt</span></div><form id="v18SavedReceiptImportForm" class="form"><label><span>Saved Search receipt package SHA-256</span><input name="file" type="file" accept="application/json,.json" required></label><div class="v16-actions"><button class="secondary" type="submit">Xác minh & preview</button><button class="primary" id="v18ApplySavedReceipt" type="button" disabled>Import có history</button><button class="danger" id="v18UndoSavedReceipt" type="button" ${latest?'':'disabled'}>Undo import cuối</button></div></form><div id="v18SavedReceiptStatus" class="v16-status">${latest?`Gần nhất: ${esc(latest.at)} · ${latest.added.length} receipt.`:'Chưa có managed Saved Search receipt import.'}</div><div class="v16-note">${esc(SAVED_SEARCH_RECEIPT_IMPORT_HISTORY_NOTE)}</div></section>`;}
function recoveryReceiptPanel(state){const total=filterRecoveryReconciliationVerificationReceipts(state.settings||{},{}).length;return `<section class="card v16-panel" data-v18="recovery-receipt-management"><div class="v16-heading"><div><span class="v16-kicker">Lượt 114 · Recovery verification receipts</span><h2>Filter · export · clear</h2></div><span class="pill">${total} receipt</span></div><form id="v18RecoveryReceiptFilter" class="form"><label><span>Kết quả</span><select name="result"><option value="all">Tất cả</option><option value="valid">Hợp lệ</option><option value="invalid">Không hợp lệ</option></select></label><label><span>Format chính xác</span><input name="format" maxlength="80" placeholder="Để trống = tất cả"></label><div class="v16-actions"><button class="secondary" type="submit">Lọc</button><button class="secondary" id="v18ExportRecoveryReceipts" type="button">Xuất metadata</button><button class="danger" id="v18ClearRecoveryReceipts" type="button">Xóa phần đang lọc</button></div></form><div id="v18RecoveryReceiptStatus" class="v16-status">${total} receipt metadata cục bộ.</div><div class="v16-note">${esc(RECOVERY_RECONCILIATION_VERIFICATION_RECEIPT_MANAGEMENT_NOTE)}</div></section>`;}
function freshnessPanel(state){const policy=compatibilityEvidenceFreshnessPolicy(state.settings||{}),review=buildCompatibilityEvidenceFreshnessReview(state.settings||{});return `<section class="card v16-panel" data-v18="freshness-policy"><div class="v16-heading"><div><span class="v16-kicker">Lượt 115 · Evidence freshness policy</span><h2>Stale-evidence review gate</h2></div><span class="pill">${review.attentionRequired?review.modules.length+' cần review':'fresh'}</span></div><form id="v18FreshnessForm" class="form"><label><span>Ngưỡng fresh (ngày)</span><input name="freshDays" type="number" min="1" max="3650" value="${policy.freshDays}" required></label><div class="v16-actions"><button class="primary" type="submit">Lưu policy</button><button class="secondary" id="v18ResetFreshness" type="button">Reset 30 ngày</button></div></form><div class="v16-list">${review.modules.length?review.modules.slice(0,12).map((row)=>`<div><strong>${esc(row.module)}</strong><span>thiếu ${row.missingFlows.length} · stale ${row.staleFlows.length}${row.axeRecheckRequired?' · Axe cần chạy local':''}</span></div>`).join(''):'<div class="empty">Không có module cần stale/missing review theo policy hiện tại.</div>'}</div><div id="v18FreshnessStatus" class="v16-status">retirementAllowed=false · actionsApplied=false</div><div class="v16-note">${esc(COMPATIBILITY_EVIDENCE_FRESHNESS_POLICY_NOTE)}</div></section>`;}

function addPanels(){const main=document.querySelector('.main');if(!main||activePage()!=='overview'||document.querySelector('[data-v18="receipt-history-package"]'))return;const state=readState();main.insertAdjacentHTML('beforeend',`<div class="v16-grid" data-v18-grid>${historyPackagePanel(state)}${presetAuditPanel(state)}${savedReceiptManagedPanel(state)}${recoveryReceiptPanel(state)}${freshnessPanel(state)}</div>`);}
function enhanceV18(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;retireForm('#v17SavedReceiptImportForm','#v17SavedReceiptStatus','Import apply đã chuyển sang Lượt 113 để luôn có managed history/undo.');addPanels();});}
function recoveryCriteria(){const form=document.querySelector('#v18RecoveryReceiptFilter');if(!form)return {};const data=new FormData(form);return {result:String(data.get('result')||'all'),format:String(data.get('format')||'')};}

document.addEventListener('submit',async(event)=>{
  if(event.target.id==='v18VerifyReceiptHistoryForm'){event.preventDefault();const status=document.querySelector('#v18ReceiptHistoryStatus'),file=new FormData(event.target).get('file');try{const review=reviewReceiptImportHistoryPackage(JSON.parse(await file.text()));status.textContent=review.valid?`HỢP LỆ · ${review.importCount} lượt · ${review.receiptCount} receipt metadata.`:'KHÔNG HỢP LỆ · không apply state.';}catch{status.textContent='JSON không hợp lệ.';}return;}
  if(event.target.id==='v18VerifyPresetAuditForm'){event.preventDefault();const status=document.querySelector('#v18PresetAuditStatus'),file=new FormData(event.target).get('file');try{const review=reviewWorkloadPresetImportAuditPackage(JSON.parse(await file.text()));status.textContent=review.valid?`HỢP LỆ · ${review.summary.auditCount} audit · ${review.summary.conflicts} conflict · ${review.summary.resolved} resolved.`:'KHÔNG HỢP LỆ · review bị khóa.';}catch{status.textContent='JSON không hợp lệ.';}return;}
  if(event.target.id==='v18SavedReceiptImportForm'){event.preventDefault();const status=document.querySelector('#v18SavedReceiptStatus'),apply=document.querySelector('#v18ApplySavedReceipt'),file=new FormData(event.target).get('file');pendingSavedReceipt=null;apply.disabled=true;try{const pkg=JSON.parse(await file.text()),preview=previewSavedSearchReceiptImport(pkg,readState().settings||{});if(!preview.valid){status.textContent='Checksum/format không hợp lệ.';return;}pendingSavedReceipt=pkg;apply.disabled=false;status.textContent=`Preview: ${preview.accepted.length} thêm · ${preview.duplicates} trùng · ${preview.rejected} loại.`;}catch{status.textContent='JSON không hợp lệ.';}return;}
  if(event.target.id==='v18RecoveryReceiptFilter'){event.preventDefault();const count=filterRecoveryReconciliationVerificationReceipts(readState().settings||{},recoveryCriteria()).length;document.querySelector('#v18RecoveryReceiptStatus').textContent=`Bộ lọc hiện có ${count} receipt metadata.`;return;}
  if(event.target.id==='v18FreshnessForm'){event.preventDefault();const state=readState(),freshDays=Number(new FormData(event.target).get('freshDays'));state.settings=setCompatibilityEvidenceFreshnessPolicy(state.settings||{},freshDays);auditedSave(state,'compatibility_evidence_freshness_policy_updated',{freshDays:compatibilityEvidenceFreshnessPolicy(state.settings).freshDays});location.reload();return;}
},true);

document.addEventListener('click',(event)=>{
  if(event.target.closest('#v18ExportReceiptHistory')){downloadJson('growup-receipt-import-history-sha256.json',buildReceiptImportHistoryPackage(readState().settings||{}));return;}
  if(event.target.closest('#v18ExportPresetAudit')){downloadJson('growup-workload-preset-import-audit-sha256.json',buildWorkloadPresetImportAuditPackage(readState().settings||{}));return;}
  if(event.target.closest('#v18ApplySavedReceipt')){if(!pendingSavedReceipt)return;const state=readState(),result=applySavedSearchReceiptImportWithHistory(state.settings||{},pendingSavedReceipt);if(result.changed){state.settings=result.settings;auditedSave(state,'saved_search_receipt_import_with_history',{added:result.added,duplicates:result.duplicates,rejected:result.rejected});pendingSavedReceipt=null;location.reload();}else document.querySelector('#v18SavedReceiptStatus').textContent='Không có receipt mới để nhập.';return;}
  if(event.target.closest('#v18UndoSavedReceipt')){if(!confirm('Undo đúng metadata của lần Saved Search receipt import gần nhất?'))return;const state=readState(),result=undoLastSavedSearchReceiptImport(state.settings||{});if(result.changed){state.settings=result.settings;auditedSave(state,'saved_search_receipt_import_undone',{removed:result.removed,missing:result.missing});location.reload();}else document.querySelector('#v18SavedReceiptStatus').textContent='Không có delta phù hợp để undo.';return;}
  if(event.target.closest('#v18ExportRecoveryReceipts')){downloadJson('growup-recovery-verification-receipts.json',buildRecoveryReconciliationVerificationReceiptPackage(readState().settings||{},recoveryCriteria()));return;}
  if(event.target.closest('#v18ClearRecoveryReceipts')){if(!confirm('Xóa vĩnh viễn các recovery verification receipt metadata đang khớp bộ lọc?'))return;const state=readState(),result=clearRecoveryReconciliationVerificationReceipts(state.settings||{},recoveryCriteria(),true);if(result.changed){state.settings=result.settings;auditedSave(state,'recovery_verification_receipts_cleared',{removed:result.removed});location.reload();}else document.querySelector('#v18RecoveryReceiptStatus').textContent='Không có receipt khớp bộ lọc để xóa.';return;}
  if(event.target.closest('#v18ResetFreshness')){if(!confirm('Reset evidence freshness policy về 30 ngày?'))return;const state=readState();state.settings=resetCompatibilityEvidenceFreshnessPolicy(state.settings||{});auditedSave(state,'compatibility_evidence_freshness_policy_reset',{freshDays:30});location.reload();return;}
});

document.addEventListener('change',(event)=>{if(event.target.closest('#v18SavedReceiptImportForm input[name="file"]')){pendingSavedReceipt=null;const button=document.querySelector('#v18ApplySavedReceipt');if(button)button.disabled=true;}});
observer.observe(document.querySelector('#app'),{childList:true,subtree:true});enhanceV18();
