import { migrateState } from './core/schema.js';
import { saveState, appendAudit } from './core/store.js';
import { verifyReceiptImportHistoryPackageAndRecord, receiptImportHistoryPackageVerificationReceipts, filterReceiptImportHistoryPackageVerificationReceipts, buildReceiptImportHistoryPackageVerificationReceiptPackage, clearReceiptImportHistoryPackageVerificationReceipts, RECEIPT_IMPORT_HISTORY_PACKAGE_VERIFICATION_RECEIPTS_NOTE } from './core/receipt-import-history-package-verification-receipts.js';
import { buildWorkloadPresetImportAuditReview, WORKLOAD_PRESET_IMPORT_AUDIT_REVIEW_NOTE } from './core/workload-preset-import-audit-review.js';
import { buildSavedSearchReceiptImportHistoryPackage, reviewSavedSearchReceiptImportHistoryPackage, SAVED_SEARCH_RECEIPT_IMPORT_HISTORY_PACKAGE_NOTE } from './core/saved-search-receipt-import-history-package-integrity.js';
import { buildIntegrityRecoveryReconciliationVerificationReceiptPackage, verifyRecoveryReconciliationVerificationReceiptPackage, recoveryVerificationReceiptPackageVerificationReceipts, recordRecoveryVerificationReceiptPackageVerification, RECOVERY_RECONCILIATION_VERIFICATION_RECEIPT_PACKAGE_INTEGRITY_NOTE } from './core/recovery-reconciliation-verification-receipt-package-integrity.js';
import { buildCompatibilityEvidenceFreshnessReviewPackage, verifyCompatibilityEvidenceFreshnessReviewPackage, compatibilityAxeRecheckRequests, requestCompatibilityAxeRecheck, COMPATIBILITY_EVIDENCE_FRESHNESS_REVIEW_PACKAGE_NOTE } from './core/compatibility-evidence-freshness-review-package.js';
import { buildCompatibilityEvidenceFreshnessReview } from './core/compatibility-evidence-freshness-policy.js';

const STORAGE_KEY='growup_mychildren_v1';
let scheduled=false;
const observer=new MutationObserver(()=>queueMicrotask(enhanceV19));
function readState(){try{return migrateState(JSON.parse(localStorage.getItem(STORAGE_KEY)||'{"version":5,"children":[]}'));}catch{return migrateState({version:5,children:[]});}}
function auditedSave(state,type,details={}){saveState(appendAudit(state,type,details));}
function esc(value=''){return String(value).replace(/[&<>"']/g,(c)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function activePage(){return document.querySelector('.nav [data-nav].active')?.dataset.nav||document.querySelector('#mobileNav')?.value||'';}
function downloadJson(name,payload){const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),0);}
function retireForm(selector,statusSelector,message){const form=document.querySelector(selector),status=document.querySelector(statusSelector);if(form){form.hidden=true;form.setAttribute('aria-hidden','true');form.style.setProperty('display','none','important');form.querySelectorAll('input,select,textarea,button,fieldset').forEach((control)=>{control.disabled=true;control.setAttribute('tabindex','-1');});}if(status&&status.textContent!==message)status.textContent=message;}
function retireButton(selector,message){const button=document.querySelector(selector);if(!button)return;button.hidden=true;button.disabled=true;button.setAttribute('aria-hidden','true');button.setAttribute('tabindex','-1');button.style.setProperty('display','none','important');button.title=message;}
function last(items=[]){return items.length?items[items.length-1]:null;}

function receiptVerificationPanel(state){const receipts=receiptImportHistoryPackageVerificationReceipts(state.settings||{}),latest=last(receipts);return `<section class="card v16-panel" data-v19="receipt-history-verification"><div class="v16-heading"><div><span class="v16-kicker">Lượt 116 · History package verification receipts</span><h2>Verify · receipt · manage</h2></div><span class="pill">${receipts.length}/50</span></div><form id="v19VerifyReceiptHistoryForm" class="form"><label><span>History package SHA-256</span><input name="file" type="file" accept="application/json,.json" required></label><button class="primary" type="submit">Xác minh & ghi receipt</button></form><form id="v19ReceiptVerificationFilter" class="form"><label><span>Kết quả</span><select name="result"><option value="all">Tất cả</option><option value="valid">Hợp lệ</option><option value="invalid">Không hợp lệ</option></select></label><label><span>Format chính xác</span><input name="format" maxlength="80" placeholder="Để trống = tất cả"></label><div class="v16-actions"><button class="secondary" type="submit">Lọc</button><button class="secondary" id="v19ExportReceiptVerificationReceipts" type="button">Xuất receipt metadata</button><button class="danger" id="v19ClearReceiptVerificationReceipts" type="button">Xóa phần đang lọc</button></div></form><div id="v19ReceiptVerificationStatus" class="v16-status">${latest?`Gần nhất: ${esc(latest.at)} · ${latest.result} · ${latest.importCount} import / ${latest.receiptCount} receipt.`:'Chưa có verification receipt.'}</div><div class="v16-note">${esc(RECEIPT_IMPORT_HISTORY_PACKAGE_VERIFICATION_RECEIPTS_NOTE)}</div></section>`;}

function presetAuditReviewPanel(state){const review=buildWorkloadPresetImportAuditReview(state.settings||{});return `<section class="card v16-panel" data-v19="preset-audit-review"><div class="v16-heading"><div><span class="v16-kicker">Lượt 117 · Preset audit review</span><h2>Filter + comparison summary</h2></div><span class="pill">read-only</span></div><form id="v19PresetAuditReviewForm" class="form"><label><span>Strategy</span><select name="strategy"><option value="all">Tất cả</option><option value="skip">Skip</option><option value="rename">Rename</option></select></label><label><span>Status</span><select name="status"><option value="all">Tất cả</option><option value="accepted">Accepted</option><option value="resolved">Resolved</option><option value="conflict-skip">Conflict skip</option><option value="rejected">Rejected</option></select></label><label><input name="conflictOnly" type="checkbox"> Chỉ quyết định có conflict</label><button class="secondary" type="submit">Review</button></form><div id="v19PresetAuditReviewStatus" class="v16-status">${review.summary.auditCount} audit · ${review.summary.decisionCount} quyết định · ${review.summary.conflicts} conflict · ${review.summary.sourceToResolvedChanges} source→resolved thay đổi.</div><div class="v16-note">${esc(WORKLOAD_PRESET_IMPORT_AUDIT_REVIEW_NOTE)}</div></section>`;}

function savedSearchHistoryPanel(state){const count=state.settings?.savedSearchReceiptImportHistory?.length||0;return `<section class="card v16-panel" data-v19="saved-search-history-package"><div class="v16-heading"><div><span class="v16-kicker">Lượt 118 · Saved Search import-history portability</span><h2>Signed history package</h2></div><span class="pill">${count} lượt</span></div><div class="v16-actions"><button class="secondary" id="v19ExportSavedSearchHistory" type="button">Xuất SHA-256</button></div><form id="v19VerifySavedSearchHistoryForm" class="form"><label><span>History package cần verify</span><input name="file" type="file" accept="application/json,.json" required></label><button class="secondary" type="submit">Xác minh & review</button></form><div id="v19SavedSearchHistoryStatus" class="v16-status">Portability package chỉ review; undo vẫn là local managed state.</div><div class="v16-note">${esc(SAVED_SEARCH_RECEIPT_IMPORT_HISTORY_PACKAGE_NOTE)}</div></section>`;}

function recoveryIntegrityPanel(state){const receipts=recoveryVerificationReceiptPackageVerificationReceipts(state.settings||{}),latest=last(receipts);return `<section class="card v16-panel" data-v19="recovery-receipt-integrity"><div class="v16-heading"><div><span class="v16-kicker">Lượt 119 · Recovery receipt package integrity</span><h2>Signed export + verify history</h2></div><span class="pill">${receipts.length}/50 verify</span></div><form id="v19RecoverySignedExportForm" class="form"><label><span>Kết quả</span><select name="result"><option value="all">Tất cả</option><option value="valid">Hợp lệ</option><option value="invalid">Không hợp lệ</option></select></label><label><span>Format chính xác</span><input name="format" maxlength="80" placeholder="Để trống = tất cả"></label><button class="secondary" type="submit">Xuất package SHA-256</button></form><form id="v19VerifyRecoveryReceiptPackageForm" class="form"><label><span>Signed receipt package cần verify</span><input name="file" type="file" accept="application/json,.json" required></label><button class="primary" type="submit">Xác minh & ghi receipt</button></form><div id="v19RecoveryIntegrityStatus" class="v16-status">${latest?`Gần nhất: ${esc(latest.at)} · ${latest.result} · ${latest.receiptCount} receipt.`:'Chưa có package verification receipt.'}</div><div class="v16-note">${esc(RECOVERY_RECONCILIATION_VERIFICATION_RECEIPT_PACKAGE_INTEGRITY_NOTE)}</div></section>`;}

function freshnessReviewPanel(state){const review=buildCompatibilityEvidenceFreshnessReview(state.settings||{}),requests=compatibilityAxeRecheckRequests(state.settings||{}),pending=requests.filter((item)=>item.status==='pending'),passed=requests.filter((item)=>item.status==='passed');const options=review.axeRecheckModules.map((module)=>`<option value="${esc(module)}">${esc(module)}</option>`).join('');return `<section class="card v16-panel" data-v19="freshness-review-package"><div class="v16-heading"><div><span class="v16-kicker">Lượt 120 · Freshness review + Axe recheck</span><h2>Signed review · explicit local Axe</h2></div><span class="pill">${pending.length} pending · ${passed.length} passed</span></div><div class="v16-actions"><button class="secondary" id="v19ExportFreshnessReview" type="button">Xuất review SHA-256</button></div><form id="v19VerifyFreshnessReviewForm" class="form"><label><span>Freshness review package</span><input name="file" type="file" accept="application/json,.json" required></label><button class="secondary" type="submit">Xác minh read-only</button></form><form id="v19AxeRecheckRequestForm" class="form"><label><span>Module cần Axe local recheck</span><select name="module" ${options?'':'disabled'}>${options||'<option value="">Không có module cần recheck</option>'}</select></label><button class="primary" type="submit" ${options?'':'disabled'}>Tạo yêu cầu Axe recheck</button></form><div class="v16-list">${requests.length?requests.slice(-12).reverse().map((item)=>`<div><strong>${esc(item.module)}</strong><span>${item.status==='passed'?`PASS actual local Axe · ${esc(item.completedAt||'')}`:`pending từ ${esc(item.requestedAt)}`}</span></div>`).join(''):'<div class="empty">Chưa có yêu cầu Axe recheck.</div>'}</div><div id="v19FreshnessReviewStatus" class="v16-status">retirementAllowed=false · actionsApplied=false · không có nút manual PASS.</div><div class="v16-note">${esc(COMPATIBILITY_EVIDENCE_FRESHNESS_REVIEW_PACKAGE_NOTE)}</div></section>`;}

function addPanels(){const main=document.querySelector('.main');if(!main||activePage()!=='overview'||document.querySelector('[data-v19="receipt-history-verification"]'))return;const state=readState();main.insertAdjacentHTML('beforeend',`<div class="v16-grid" data-v19-grid>${receiptVerificationPanel(state)}${presetAuditReviewPanel(state)}${savedSearchHistoryPanel(state)}${recoveryIntegrityPanel(state)}${freshnessReviewPanel(state)}</div>`);}
function enhanceV19(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;retireForm('#v18VerifyReceiptHistoryForm','#v18ReceiptHistoryStatus','Verification đã chuyển sang Lượt 116 để luôn ghi bounded verification receipt.');retireButton('#v18ExportRecoveryReceipts','Unsigned export đã chuyển sang Lượt 119 SHA-256.');addPanels();});}
function receiptVerificationCriteria(){const form=document.querySelector('#v19ReceiptVerificationFilter');if(!form)return {};const data=new FormData(form);return {result:String(data.get('result')||'all'),format:String(data.get('format')||'')};}
function recoveryExportCriteria(form){const data=new FormData(form);return {result:String(data.get('result')||'all'),format:String(data.get('format')||'')};}
function presetReviewCriteria(form){const data=new FormData(form);return {strategy:String(data.get('strategy')||'all'),status:String(data.get('status')||'all'),conflictOnly:data.get('conflictOnly')==='on'};}

document.addEventListener('submit',async(event)=>{
  if(event.target.id==='v19VerifyReceiptHistoryForm'){event.preventDefault();const file=new FormData(event.target).get('file');try{const pkg=JSON.parse(await file.text()),state=readState(),result=verifyReceiptImportHistoryPackageAndRecord(state.settings||{},pkg);state.settings=result.settings;auditedSave(state,'receipt_import_history_package_verified',{result:result.receipt.result,importCount:result.receipt.importCount,receiptCount:result.receipt.receiptCount});location.reload();}catch{document.querySelector('#v19ReceiptVerificationStatus').textContent='JSON không hợp lệ; không ghi receipt.';}return;}
  if(event.target.id==='v19ReceiptVerificationFilter'){event.preventDefault();const count=filterReceiptImportHistoryPackageVerificationReceipts(readState().settings||{},receiptVerificationCriteria()).length;document.querySelector('#v19ReceiptVerificationStatus').textContent=`Bộ lọc hiện có ${count} verification receipt.`;return;}
  if(event.target.id==='v19PresetAuditReviewForm'){event.preventDefault();const review=buildWorkloadPresetImportAuditReview(readState().settings||{},presetReviewCriteria(event.target));document.querySelector('#v19PresetAuditReviewStatus').textContent=`${review.summary.auditCount} audit · ${review.summary.decisionCount} quyết định · ${review.summary.conflicts} conflict · ${review.summary.resolved} resolved · ${review.summary.sourceToResolvedChanges} source→resolved thay đổi · readOnly=true.`;return;}
  if(event.target.id==='v19VerifySavedSearchHistoryForm'){event.preventDefault();const file=new FormData(event.target).get('file');try{const review=reviewSavedSearchReceiptImportHistoryPackage(JSON.parse(await file.text()));document.querySelector('#v19SavedSearchHistoryStatus').textContent=review.valid?`HỢP LỆ · ${review.importCount} import · ${review.receiptCount} receipt metadata · readOnly=true.`:'KHÔNG HỢP LỆ · không apply state.';}catch{document.querySelector('#v19SavedSearchHistoryStatus').textContent='JSON không hợp lệ.';}return;}
  if(event.target.id==='v19RecoverySignedExportForm'){event.preventDefault();downloadJson('growup-recovery-verification-receipts-sha256.json',buildIntegrityRecoveryReconciliationVerificationReceiptPackage(readState().settings||{},recoveryExportCriteria(event.target)));return;}
  if(event.target.id==='v19VerifyRecoveryReceiptPackageForm'){event.preventDefault();const file=new FormData(event.target).get('file');try{const pkg=JSON.parse(await file.text()),verification=verifyRecoveryReconciliationVerificationReceiptPackage(pkg),state=readState();state.settings=recordRecoveryVerificationReceiptPackageVerification(state.settings||{},verification);auditedSave(state,'recovery_verification_receipt_package_verified',{result:verification.valid?'valid':'invalid',receiptCount:verification.valid?verification.receiptCount:0});location.reload();}catch{document.querySelector('#v19RecoveryIntegrityStatus').textContent='JSON không hợp lệ; không ghi receipt.';}return;}
  if(event.target.id==='v19VerifyFreshnessReviewForm'){event.preventDefault();const file=new FormData(event.target).get('file');try{const verification=verifyCompatibilityEvidenceFreshnessReviewPackage(JSON.parse(await file.text()));document.querySelector('#v19FreshnessReviewStatus').textContent=verification.valid?`HỢP LỆ · ${verification.moduleCount} module · retirementAllowed=false · actionsApplied=false.`:'KHÔNG HỢP LỆ · không apply state.';}catch{document.querySelector('#v19FreshnessReviewStatus').textContent='JSON không hợp lệ.';}return;}
  if(event.target.id==='v19AxeRecheckRequestForm'){event.preventDefault();const module=String(new FormData(event.target).get('module')||''),state=readState(),result=requestCompatibilityAxeRecheck(state.settings||{},module);if(result.changed){state.settings=result.settings;auditedSave(state,'compatibility_axe_recheck_requested',{module:result.request.module});location.reload();}else document.querySelector('#v19FreshnessReviewStatus').textContent=result.reason==='already-pending'?'Module này đã có yêu cầu Axe pending.':'Không thể tạo yêu cầu Axe recheck.';return;}
},true);

document.addEventListener('click',(event)=>{
  if(event.target.closest('#v19ExportReceiptVerificationReceipts')){downloadJson('growup-receipt-history-package-verification-receipts.json',buildReceiptImportHistoryPackageVerificationReceiptPackage(readState().settings||{},receiptVerificationCriteria()));return;}
  if(event.target.closest('#v19ClearReceiptVerificationReceipts')){if(!confirm('Xóa vĩnh viễn verification receipt metadata đang khớp bộ lọc?'))return;const state=readState(),result=clearReceiptImportHistoryPackageVerificationReceipts(state.settings||{},receiptVerificationCriteria(),true);if(result.changed){state.settings=result.settings;auditedSave(state,'receipt_import_history_package_verification_receipts_cleared',{removed:result.removed});location.reload();}else document.querySelector('#v19ReceiptVerificationStatus').textContent='Không có receipt khớp bộ lọc để xóa.';return;}
  if(event.target.closest('#v19ExportSavedSearchHistory')){downloadJson('growup-saved-search-receipt-import-history-sha256.json',buildSavedSearchReceiptImportHistoryPackage(readState().settings||{}));return;}
  if(event.target.closest('#v19ExportFreshnessReview')){downloadJson('growup-compatibility-freshness-review-sha256.json',buildCompatibilityEvidenceFreshnessReviewPackage(readState().settings||{}));return;}
});

observer.observe(document.querySelector('#app'),{childList:true,subtree:true});enhanceV19();
